### ISSUE TITLE
FR: Colour branch names

### ISSUE THREAD

**Issue by Gruntfuggly** [mhutchie/vscode-git-graph#1]
Could you colour local and remote branches so that they stand out more?

**Comment by mhutchie** [comment]
Great suggestion! I'll add this for the next release.

**Comment by mhutchie** [comment]
What do you think of the labels shown here?
![image](https://user-images.githubusercontent.com/5315753/52674033-807f8d00-2f76-11e9-91e9-e6c878a9ace6.png)

**Comment by Gruntfuggly** [comment]
Nice.

**Comment by mhutchie** [comment]
Ready for release in 1.3.0 (should be in the next day or so)
