### ISSUE TITLE
Master branch is not continuous on the graph when it is merged into another branch

### ISSUE THREAD

**Issue by krupenja** [mhutchie/vscode-git-graph#10]
**What does the bug relate to**
- [x] Graph Rendering
- [ ] Git Command
- [ ] Responsiveness

**To reproduce**
Steps to reproduce the behaviour:
1. Clone VSCode repo: https://github.com/Microsoft/vscode/
2. Open Git Graph.
3. Scroll down to commit b3fd242ad3e4e74a4faddcba6c9318d5b0b5e613.

Notice how the blue line for master branch is not continuous near that commit (see screenshot). Have seen this with another repo in the same circumstances (master branch merged into another branch).

**Expected behaviour**
Graph is continuous.

**Environment**
 - OS: [e.g. Windows 10]
 - Visual Studio Code Version: [e.g. 1.31.1]

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/26354715/53207203-cd7cf680-363b-11e9-985e-ea1ca8aedca8.png)

**Comment by mhutchie** [comment]
This is an easy fix & will be included in the next release. When it is determining the width of the graph, it is only considering the commit node x positions. In this case, there is no node on the portion of the line which is cropped off, so it is not extending the width correctly.

**Comment by mhutchie** [comment]
Completed. This will be in the next release. Thanks for finding this issue.

**Comment by mhutchie** [comment]
This has just been released in the final version of 1.3.3. As I forgot to flag the pre-release version as a beta, and you manually installed it, you won't automatically get the final 1.3.3 update in Visual Studio Code. To get the final version:
1. Download the final release https://github.com/mhutchie/vscode-git-graph/releases/download/v1.3.3/git-graph-1.3.3.vsix
2. Open a terminal to the directory containing the newly downloaded package.
3. Run `code --install-extension git-graph-1.3.3.vsix`
4. Restart Visual Studio Code

Apologies for the inconvenience, I'll make sure I flag beta releases appropriately in the future.

**Comment by krupenja** [comment]
Great, thanks for explaining this!
