### ISSUE TITLE
Show merge commits with a muted text color

### ISSUE THREAD

**Issue by sebastianlay** [mhutchie/vscode-git-graph#100]
Some git worflows generate a lot of automated merge commits.
Often these are not very interesting and should be less emphasized than other commits.
Similar to solutions used in [other IDEs](https://www.jetbrains.com/help/img/idea/2018.2/merge_commit.png).

**Comment by mhutchie** [comment]
Thanks for making this suggestion, and also implementing it! Thank you for also taking the time to add it as an extension setting, your consideration & effort is much appreciated.

I've just merged your changes now, so it will be included in the next beta release (should be available within the next day). I'll reply to this issue when it's available, along with installation steps so you can use it straight away.

I'll add your handle `@sebastianlay` to the changelog for this issue, like I do with all changes made by contributors.

**Comment by mhutchie** [comment]
This will be available in v1.9.0.

If you'd like to use it before the next release, you can download [v1.9.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.9.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

FYI: @sebastianlay, @rinukkusu
