### ISSUE TITLE
ability to amend commit message

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#103]
Add the possibility to amend the message of a commit.

UI proposal : Adding a "create" icon there
![image](https://user-images.githubusercontent.com/44493964/59413067-1e695400-8dbf-11e9-865b-dd69995630e1.png)

*Maybe disable it for already pushed commit?*

**Comment by mhutchie** [comment]
Thanks for the suggestion!

I'm not sure what additional value this would add for users, as this functionality is already available from the Visual Studio Code SCM View (along with many other options). The built in functionality also clearly indicates any staged files that would be committed in the process of amending the commit (this would also be required to be duplicated in Git Graph).

The methods I'm aware of amending commit messages are:
- If it's the last commit:
    - By the commit --amend command.
    - In this case only the top row of the graph would have the option, so it doesn't really benefit from being on the graph, as opposed to the SCM view. The graph is a huge advantage when the user is wanting to run a command at any commit historically, not if it's only possible on the most recent commit.
- If it's a prior commit:
    - By the rebase command.
    - This is already available in Git Graph on any commit or branch.

Ideally with this extension I want to focus of adding functionality that is not already available in Visual Studio Code, especially when:
- A significant amount of duplication would be required.
- Visual Studio Code already provides a much larger variety of options for the same task than would be reasonably achievable in the extension.

Please let me if their would be additional value not already available in Visual Studio Code that I have not thought about & mentioned above. If not, we can close this request for now, although I'll keep it in the backlog in case other functionality comes up that would work well with this request to achieve combined value.

**Comment by rbalet** [comment]
You're right, I didn't saw the undo commit commande from vscode.
Sry for the lost of time.
