### ISSUE TITLE
Add information for troubleshooting repositories in subfolders

### ISSUE THREAD

**Issue by 0x5c** [mhutchie/vscode-git-graph#105]
**Describe the bug**
When in a workspace with multiple repositories in subfolders, using the `View Git Graph (git log)` command fails, and the default message about not having either a repository or git shows.

However, using the per-repository Git Graph button in the Source Control panel works as-expected. Further attempts at using the command will then work, but only for that specific repository.

**What does the bug relate to**
List the area(s) this issue relates to, for example:
- Showing the graph

**To reproduce**
Steps to reproduce the behaviour:
1. Have a workspace containing multiple repositories.
2. `View Git Graph (git log)` in the command palette.
3. See default failure screen.

**Expected behaviour**
The graph loads for the current directory.

**Environment**
 - OS: Windows 10
 - Visual Studio Code Version: 1.35.1
 - Git Graph: 1.8.0

**Comment by mhutchie** [comment]
What is the structure of the multi-root workspace you are working in? Could you provide a simple example of the file tree indicating which folders are roots in VSCode, and which folders are repos.

What value have you set [git-graph.maxDepthOfRepoSearch](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#max-depth-of-repo-search) to? (is it a suitable depth for the depth of subfolders you have)

Have you tried running the command “Git Graph: Add Git Repository” to manually add repos?

**Comment by 0x5c** [comment]
I was not aware of that setting (I probably should have checked the doc). this solves the issue.

As for the `Add Git Repository` command, I am not so proud of missing it.

Sorry for that!

**Comment by mhutchie** [comment]
No problem at all!

The default error message that appears when no repositories exist should definitely be clearer and mention this setting (you shouldn’t have to search docs to resolve the issue).

I’ll add this in the next release.

**Comment by mhutchie** [comment]
This will be available in v1.9.0.
