### ISSUE TITLE
Open file from commit details

### ISSUE THREAD

**Issue by orjandesmet** [mhutchie/vscode-git-graph#108]
**Describe the feature that you'd like**
At the moment we can see the file difference from the commit details. It would be nice if we could directly open the file in an editor too (screenshot 1). Or at least through the diff view (screenshot 2). Currently this seems to only exist on the "Uncommitted Changes" line.

This would be great to continue work on a feature that has, for example, code review remarks.

**Additional context (optional)**
1. <img width="403" alt="Schermafbeelding 2019-06-19 om 14 31 07" src="https://user-images.githubusercontent.com/75660/59765969-7dd3d200-929f-11e9-9cfa-679db6f350c0.png">

2. <img width="1101" alt="Schermafbeelding 2019-06-19 om 14 32 26" src="https://user-images.githubusercontent.com/75660/59765968-7dd3d200-929f-11e9-9c56-31f4ea3f2081.png">

**Comment by mhutchie** [comment]
Thanks for this suggestion, this would be great to have and very useful!

**Comment by mhutchie** [comment]
This will be available in v1.10.0, which will be released in the next day.

I also made some minor UI improvements to the Commit Details View file tree when implementing this feature request.

FYI: @orjandesmet, @realfreebird

**Comment by orjandesmet** [comment]
Nice, thanks!
