### ISSUE TITLE
Support for deleting remote tags

### ISSUE THREAD

**Issue by GOST-UA** [mhutchie/vscode-git-graph#109]
It would be nice if Git Graph would be able to show and delete remote tags.

**Comment by mhutchie** [comment]
Thanks for these suggestions!

Deleting remote tags would definitely be useful, and would be great for to have in Git Graph!

For “show remote tags”, are you referring to showing remote tags before you’ve fetched from remotes (as that automatically adds them to the local repo)? By getting the “non-fetched” tags, it would mean that they could be on commits that aren’t fetched, and consequently the tags and commits being displayed in Git Graph to be out of sync. I don’t think this would be advisable, as I think it should be left to the user to press the “Fetch from Remote(s)” button on the control bar to fetch branches + commits + tags to maintain a consistent representation of the repository from remotes. Additionally, to get the “non-fetched” tags would require running a git command that has to contact the remote repository to obtain the information, and would therefore cause the Git Graph view to load significantly slower (which I also don’t want to do).

**Comment by GOST-UA** [comment]
About "Show remote tags": my bad. I didn't fetch the whole repo and as a result, didn't see tags.

**Comment by mhutchie** [comment]
All good, I'll rename this issue specifically for support deleting remote tags.

**Comment by mhutchie** [comment]
This will be available in v1.9.0, which will be released in the next few hours.
