### ISSUE TITLE
Context menu disappears when you move the cursor away.

### ISSUE THREAD

**Issue by krupenja** [mhutchie/vscode-git-graph#11]
**Describe the bug**
Context menu disappears when you move the cursor away.

**What does the bug relate to**
List the area(s) this issue relates to, for example:
- Context menu

**To reproduce**
Steps to reproduce the behaviour:
1. Open Git Graph.
2. Right-click on a commit.
3. Move the mouse cursor away.

The context menu disappears.

**Expected behaviour**
I am not sure if this is by design but I have not seen this behaviour with any other apps/plugins.

**Environment**
 - OS: macOS 14.0.2
 - Visual Studio Code Version: 1.31.1

**Comment by mhutchie** [comment]
This is the expected behaviour (currently), although it would definitely be better to make this match typical right click menus, which are dismissed when the mouse next interacts with the page (not when it leave the right click menu as it is currently doing). Thanks for the feedback.

**Comment by mhutchie** [comment]
This will be available in v1.4.0.

If you'd like to use it before the next release, you can download [v1.4.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
