### ISSUE TITLE
add filter by author

### ISSUE THREAD

**Issue by solitaire12** [mhutchie/vscode-git-graph#111]
can git graph add filter by author,so i can see what someone commits

**Comment by mhutchie** [comment]
This has already been implemented, and will be available in v1.9.0.

If you'd like to use it before the next release, you can download [v1.9.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.9.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
