### ISSUE TITLE
Delete local remote branch ref when running "Delete Remote Branch...", and the branch is already deleted on the remote

### ISSUE THREAD

**Issue by mhutchie** [mhutchie/vscode-git-graph#115]
**Describe the improvement that you'd like**
Delete local remote branch ref when running "Delete Remote Branch...", and the branch is already deleted on the remote.

This would be the user doesn't need to run `git fetch --prune`.

**Additional context (optional)**
`git branch -d -r <remote-branch>`

@MrCreosote

**Comment by MrCreosote** [comment]
It's a bit more complex than I thought after looking into it a little more: https://stackoverflow.com/questions/3046436/how-do-you-stop-tracking-a-remote-branch-in-git

**Comment by mhutchie** [comment]
This will be available in v1.10.0, which will be released in the next day.
