### ISSUE TITLE
Detect HTTP/HTTPS urls in the commit body and make them clickable in the Commit Details View.

### ISSUE THREAD

**Issue by mhutchie** [mhutchie/vscode-git-graph#116]
**Describe the feature that you'd like**
Detect HTTP/HTTPS urls in the commit body and make them clickable in the Commit Details View.

**Additional context (optional)**
Prior work by @sebastianlay in PR #110.

**Comment by mhutchie** [comment]
This will be available in v1.10.0, which will be released in the next day.

@sebastianlay, I decided to implement my own HTTP/HTTPS url detection client side as:
- I'd prefer something lightweight that does the job for most urls that developers would include in a commit message. Other applications such as messaging & email apps benefit far more from [autolinker's](https://www.npmjs.com/package/autolinker) additional functionality.
- Because links are UI related, I don't think the server should be generating html tags for them. (The server should produce data for the client to render)
- I'm only detecting urls in the commit body shown in the Commit Details View, as I don't want clicking long links in the Git Graph table to inhibit / interfere with clicking the table row to open the Commit Details or Commit Comparison View.
- I'd prefer not to bring in a dependency when only a small amount of the code would actually be used.

Thanks for your work with investigating [autolinker](https://www.npmjs.com/package/autolinker)! I hadn't heard of it before, but I'll definitely consider using it in future projects.

**Comment by sebastianlay** [comment]
I guess you could make the detection of urls arbitrarily complex. One thing I like about the autolinker implementation is that the urls don't have to start with http(s). One example is the [gitmoji repository](https://github.com/carloscuesta/gitmoji/commits/gh-pages) which has automated commit messages like:

`Deploy gitmoji.carloscuesta.me to github.com/carloscuesta/gitmoji.git:gh-pages`

But I can completely understand your argument against unnecessary dependecies.
