### ISSUE TITLE
Sort Commits By...

### ISSUE THREAD

**Issue by P-N-L** [mhutchie/vscode-git-graph#117]
**Describe the feature that you'd like**
Good morning! First of all, I love this tool; for most things, this integrated GUI does everything I need to visualize and understand my repositories, which is awesome.

One small feature that I like about the standalone git GUI that I use, git-fork (https://git-fork.com/) (I am sure this feature is available in others) is the ability to decide how commits are sorted/grouped. For example, at my job, multiple people make commits throughout the day. When sorted by commit time, these branches begin to look tangled up and interwoven; when sorted "topologically", all commits from each individual branch are grouped together, and the sorting is based only on the latest available commit for that branch. I would love to see this feature in vscode-git-graph (and if I can find some time I will try to see if I can help out!).

Thank you!

**Additional context (optional)**
Using git-fork as an example, I cloned the gitlab-ce repo.

Sorting by date, see how the commits from origin/12077-move-cycle-analytics-to-group-level-ce-backport (red) interrupt the two latest commits from origin/clusters-group-cte (blue).
![image](https://user-images.githubusercontent.com/30122827/60509905-0db04d80-9c9c-11e9-803c-2853e1b209a1.png)

However, sorting topologically, the emphasis is on the commits from a given branch staying together (because frequently it doesn't matter WHEN commits happen). In this new sorting scheme screenshot, origin/12077-... is green, and origin/clusters-group-cte is gray, but all of their commits are contiguous and easier to follow.
![image](https://user-images.githubusercontent.com/30122827/60510083-9202d080-9c9c-11e9-8a93-57ef1179dc54.png)

**Comment by mhutchie** [comment]
Thanks for making this suggestion, this would be great to have as a new setting in Git Graph!

From an implementation perspective, it should just be a matter of retrieving the value of the new setting and passing the corresponding argument into the `DataSource.getGitLog()` method (currently it uses the `--date-order` argument [here](https://github.com/mhutchie/vscode-git-graph/blob/master/src/dataSource.ts#L376)). The only constraint posed by the graph rendering algorithm is that for each commit, all of its parent commits must occur before it.

Also, thanks for providing the screenshots illustrating this behaviour and an example repository to work with. It's much appreciated!

**Comment by mhutchie** [comment]
This will be available in v1.11.0.

If you'd like to use it before the next release, you can download [v1.11.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.11.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by P-N-L** [comment]
This is great, thank you so much!
