### ISSUE TITLE
Checkout newly created branch

### ISSUE THREAD

**Issue by morganlombard** [mhutchie/vscode-git-graph#119]
When creating a new branch at a commit, can you add a checkbox option (unchecked by default) to also checkout the branch after it is created?

When I want to start a new feature branch, I normally have to create a new branch at the desired commit and then check it out. It would be nice to have this two step process in one action.

This can be done with similarly to checkoutBranch()
by adding branchName parameter to checkoutCommit()

**Comment by mhutchie** [comment]
Thanks for this suggestion, this would definitely be a great improvement to speed up this workflow!

**Comment by mhutchie** [comment]
This will be available in v1.11.0.

If you'd like to use it before the next release, you can download [v1.11.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.11.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
