### ISSUE TITLE
Ability to cherry-pick / revert a commit from the context menu

### ISSUE THREAD

**Issue by pomdtr** [mhutchie/vscode-git-graph#12]
**Describe the feature that you'd like**
In the commit context menu, the ability to cherry-pick a commit into the current branch or to revert it
There are other fonctionnalities in the screenshot, but they seems less critical to me.
Thanks for your work, your extension is very usefull

**Additional context (optional)**
An example from the most popular extension (but less usefull than yours :p)

![image](https://user-images.githubusercontent.com/36007425/53275644-23b16e80-36fc-11e9-85fe-481e44051007.png)

**Comment by mhutchie** [comment]
Thanks for the suggestions! I'll add these for the next release.

PS: I might also add merging to the branch context menu.

**Comment by pomdtr** [comment]
Thank you, i'll make sure to test the feature when you release it.

Indeed, the merge option seems like a great idea

**Comment by mhutchie** [comment]
This will be available in v1.4.0.

If you'd like to use it before the next release, you can download [v1.4.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation). If you have any feedback on the beta release, please let me know by replying to this issue.

**Comment by pomdtr** [comment]
I tested the ability to cherry-pick, revert a commit and merge branch and did not encounter any issue.
