### ISSUE TITLE
Add merge actions in diff editor

### ISSUE THREAD

**Issue by postb99** [mhutchie/vscode-git-graph#121]
**Describe the feature that you'd like**
I'd like to get the merge actions inside the diff editor (when merging) of Git Graph, as in VS Code diffeditor.
I am not sure that I saw anything above the conflict mark when hovering.

**Additional context (optional)**
See highlighted part:
![image](https://user-images.githubusercontent.com/173565/60678027-7f96bb80-9e83-11e9-8141-dbdb8a828708.png)

Using v1.10.0

**Comment by mhutchie** [comment]
I'm not sure if I'm fully understanding what you are requesting, so please provide more information if I have misinterpreted your request.

Scenario: 
* When a merge conflict occurs, and you view the conflict by clicking on the file listed under "MERGE CHANGES" on the built in VSCode Source Control View (in the left sidebar), merge conflicts automatically have four merge actions above the merge conflict(s) (e.g. "Accept Both Changes" etc.).
* You are requesting that when you view the merge conflict by clicking on the file in the (Uncommitted) Commit Details View in Git Graph, these same four merge actions appear above the merge conflict(s).

Unfortunately this is not possible within Visual Studio Code. Buttons like "Accept Both Changes" are only visible for single files, and not files that are on one side of a Visual Studio Code Diff View (which is used by Git Graph) to show file diffs. When you click to view a merge conflict file from the VSCode Source Control View, it actually opens the file itself (allowing the buttons to show), not on one side of a Visual Studio Code Diff View. If you were to click the "Open File" button on the right of the merge conflict file in the Git Graph (Uncommitted) Commit Details View tree, the merge actions are visible. The merge actions are not shown if you just click on the file name itself to view the diff, as this opens the file on the right side of a Visual Studio Code Diff View (which doesn't show such actions).

FYI: You can see this difference in behaviour if you stage a file which still has a merge conflict in it. When you click on the staged change, the right side of the Visual Studio Code Diff view will no longer have the merge actions above the merge conflict.

**Comment by postb99** [comment]
Thanks a lot for taking the time to write down the explaination and give the solution of clicking on "open file" instead of on the file name in the Git Graph window. Yes, you understood my request well. I'm waiting for my next merge now ;-) because I give a chance to your extension to replace my usual use of Source Tree.
