### ISSUE TITLE
Keep track of last opened file in commit's listed files

### ISSUE THREAD

**Issue by postb99** [mhutchie/vscode-git-graph#122]
**Describe the feature that you'd like**
When viewing a commit's changed files, clicking on a file opens the diff editor. Would it be possible to change the appearence of the file I clicked onto, so that it keeps track of the the last opened file from the list. This is especially useful for commit review.

**Additional context (optional)**
The commit's changed files list:
![image](https://user-images.githubusercontent.com/173565/60678371-8f62cf80-9e84-11e9-8947-76dd31d87f1b.png)

**Comment by mhutchie** [comment]
Thanks for making this suggestion, this would be awesome to have in Git Graph!

As you suggested, having an indicator of the last opened file from the tree would be really useful for commit reviews! Perhaps this could be extended one step further, so it would indicate all files that have been opened from the tree - this would mean that the user can review the files in any order, and have confidence they have reviewed each file (similar to the BitBucket PR / Code Review process works). What are your thoughts on this?

**Comment by postb99** [comment]
I like your extended proposal as it would be really helpful. I just admit that the appearence of the visual clue is out of my head right now :-p, but if you were to make some design proposals we could comment them if you desire.

**Comment by mmghv** [comment]
One option is to dim the names of the viewed files :

![1](https://user-images.githubusercontent.com/5418859/61837497-5adfa380-ae85-11e9-88c7-5095d05001ba.jpg)

---

Another option is to put an "Unread" mark next to file names and remove it once a file is viewed :

![2](https://user-images.githubusercontent.com/5418859/61837546-8cf10580-ae85-11e9-9320-b3e244eb1667.jpg)

Personally, I prefer the latter.

**Comment by mhutchie** [comment]
I've implemented both:
* Code Reviews - Keep track of which files you have reviewed in the Commit Details & Comparison View.
* Last File Viewed Indicator - Indicates which file was last viewed (doesn't need to part of a Code Review).

These will both be available in v1.14.0, which will be released in the next day.
