### ISSUE TITLE
".git" is not a Git repository

### ISSUE THREAD

**Issue by PaszaVonPomiot** [mhutchie/vscode-git-graph#127]
**Describe the bug**
Error: The folder ".git" is not a Git repository, and therefore could not be added to Git Graph.

**What does the bug relate to**
Recognizing git repo

**To reproduce**

- F1
- Git Graph: Add git repository
- select .git folder

**Expected behaviour**
Recognise git repo

**Environment**
 - Windows 10
 - Visual Studio Code Version: 1.36.1

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/5560454/61089488-96b54a80-a43b-11e9-8a2d-f4b31b747aa4.png)

--
Apart from that this git repo works just fine with VS Code

**Comment by mhutchie** [comment]
You need to select the folder of the Git repository, not the .git folder itself.

For example:
* RepoExample <- select this folder.
    * .git
    * index.js

**Comment by PaszaVonPomiot** [comment]
Yeah I've already tried that. 
```
The folder "project" is not a Git repository, and therefore could not be added to Git Graph.
```

**Comment by mhutchie** [comment]
When you run the command “View Git Graph” do you get an error message, or does it a show another git repository in your workspace.

**Comment by PaszaVonPomiot** [comment]
I get the error message from Git Graph view with instructions which I followed with no success. I have standalone version of Git. Git Graph doesn't show any repos. I select following folder with `Git Graph: Add Git Repository` command - `D:\projects\project` which is also root folder of my workspace. It contains:
```
.git/
.vscode/
__pycache__/
env/
temp/
files.py
...
```

**Comment by mhutchie** [comment]
If you are getting the error message, then that also explains why the `Git Graph: Add Git Repository` command is failing. The extension is unable to execute the git executable.

What value have you set `git.path` to?

**Comment by PaszaVonPomiot** [comment]
I have set now the `git.path` workspace settings in VS Code to 
`"git.path": "C:\\Program Files\\Git\\bin\\git.exe"`
and run cmd command `"C:\Program Files\Git\bin\git.exe" --version`
which results in `git version 2.16.1.windows.2`

Git Graph still displays "Unable to load Git Graph" page.

**Comment by PaszaVonPomiot** [comment]
OK I fixed it, the git.path needs to go to user settings not workspace settings. My recommendation is to automatically detect Git path to avoid such issues.
Thanks for support.

**Comment by mhutchie** [comment]
Glad to hear that this is fixed for you!

Under normal circumstances when `git` is in the path, Git Graph will automatically detect it and `git.path` doesn't need to be defined. If the user is using a stand-alone git installation, I'm unaware of a good way of detecting it, as it could be located anywhere on the users file system (the Visual Studio Code `git.path` setting is designed for this purpose).

It shouldn't matter whether `git.path` is defined in the user or workspace settings, as long as it is not being overridden by a higher precedence version of the setting. You may need to restart VSCode after changing the setting though for the repos to be automatically detected (workspace scanning for existing repos only runs on VSCode startup). However, you should be able to add repos via the `Git Graph: Add Git Repository` command, or by opening the Git Graph view via the VSCode SCM Provider's Git Graph menu icon, as soon as the setting is correctly set. I was already designing an improved flow after `git.path` is changed to ensure that repos will appear immediately, without needing to restart VSCode (this will be coming in the next release).

**Comment by PaszaVonPomiot** [comment]
VS Code somehow detects git path automatically so there has to be a way. Or maybe it just checks default installation path. 

`git.path` in workspace settings is not accepted at all:
![image](https://user-images.githubusercontent.com/5560454/61172831-a3948400-a58a-11e9-91aa-94bcca2169b4.png)
better put that info into instructions

Thanks!

**Comment by mhutchie** [comment]
After looking at the source code, VSCode checks a variety of hard coded platform specific directories in addition to the path for Git installations (not a particularly efficient, complete, or clean way of doing it). I’ll look into performing equivalent checks so this extension behaves closer to VSCode, and will help some users get started using Git Graph much smoother.

Thanks for letting me know about the workspace settings message, that is new in a recent VSCode update.
