### ISSUE TITLE
Update branch without checkouting

### ISSUE THREAD

**Issue by AndreyWV** [mhutchie/vscode-git-graph#128]
**Description**
It could be a small time saving if there was a possibility to update branch without checkouting to it.

**Additional context**
It can be carried out like in [this answer](https://stackoverflow.com/questions/3216360/merge-update-and-pull-git-branches-without-using-checkouts) with command `git fetch origin foo:foo` where `foo` is selected branch.

**Comment by mhutchie** [comment]
Thanks for this suggestion, this would definitely be nice to have in Git Graph!

**Comment by mhutchie** [comment]
Apologies for the delay in implementing this feature request. This will be available in v1.17.0.

If you'd like to use it before the next release, you can download [v1.17.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.17.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
