### ISSUE TITLE
Error: Unable to load branches

### ISSUE THREAD

**Issue by SholomAber** [mhutchie/vscode-git-graph#130]
Receiving an error when loading remote branches via SSH. Getting error attached.

Can't seem to find any logs to debug this further. Please let me know if I can provide any helpful info.
Thanks!

![image](https://user-images.githubusercontent.com/17561417/61307331-251f2880-a7bc-11e9-9b76-2c24124bd95e.png)

**Comment by mhutchie** [comment]
Thanks for reporting this!

The screenshot you have provided lists stdout + stderr of the command `git branch -a`, and seems to suggest via the long scroll bar that by including remotes the list of branches becomes extremely long. This suggests to me that possibly the maximum output limit of Node.js child_process.exec() may have been reached. I've switched the branch loading command to use Node.js child_process.spawn(), like other git commands that produce a lot of output.

Could you please download and extract `git-graph-1.12.0-alpha.0.vsix` from [git-graph-1.12.0-alpha.0.zip](https://github.com/mhutchie/vscode-git-graph/files/3399411/git-graph-1.12.0-alpha.0.zip), and then install it from Step 3 - 5 of [Manual Installation](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation). Please let me know if this resolves this issue.

If not, could you please respond with the following information:
* Does this occur for you with other repos, with a smaller number of branches (less than 100)?
* Does this **only** occur when show remote branches is checked?

**Comment by SholomAber** [comment]
Hi @mhutchie,
Thank you for the quick response! This worked! 🎉 💪

**Comment by mhutchie** [comment]
Glad to hear that this fixed this issue for you. It will be available in v1.12.0.

I also replaced all other usages of Node.js child_process.exec() with child_process.spawn() to avoid any other similar issues in the future. (Although none of the other usages with git commands could generate enough data to cause a similar issue)

If you'd like to use it before the next release, you can download [v1.12.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.12.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
