### ISSUE TITLE
Checkout to local branch if it exists

### ISSUE THREAD

**Issue by AndreyWV** [mhutchie/vscode-git-graph#131]
**Description**
Checkout to existed local branch if selected remote branch with `origin/` prefix.

**Additional context**
When try to checkout to remote branch we have this prompt:
![image](https://user-images.githubusercontent.com/29225873/61356074-40eb0300-a87e-11e9-927f-93b9718c096f.png)
And if local branch with this name exists we have this error:
![image](https://user-images.githubusercontent.com/29225873/61356090-48121100-a87e-11e9-8ba8-0a87ad63a961.png)

> Fatal: branch with name "master" already exists.

It hould check if we have local branch matches with selected remote branch, and if it exists - checkout to it.

**Comment by mhutchie** [comment]
Thanks for making this suggestion, this would be great to have.

I think it would be best if when the user submits the current dialog, it checks if the branch already exists. If the branch already exists, a new dialog is shown asking “A branch named master already exists, would you like to check it out?”.
* If the user selects “Yes”, Git Graph would check out the existing branch.
* If the user selects “No”, Git Graph returns to the existing dialog so the user can enter an alternative name.

I think a prompt is necessary, as the user could mistakenly type an existing branch name, in which case automatically checking out the existing branch could be misleading as it could be at a different point in history, and the user could start working at the wrong point if they don’t notice what happened.

**Comment by mhutchie** [comment]
This will be available in v1.12.0, which will be released within the next day.
