### ISSUE TITLE
Commits are not correctly grayed out

### ISSUE THREAD

**Issue by basvdlinden** [mhutchie/vscode-git-graph#138]
**Describe the bug**
Commits not part of current branch (and Uncommitted Changes) are highlighted.

**What does the bug relate to**
List the area(s) this issue relates to, for example:
- UX

**To reproduce**
Steps to reproduce the behaviour:
1. Create GIT repository
2. Create new branch and commit a change
3. Check out "master"
4. Change a file
5. Open Git Graph view

**Expected behaviour**
commits not part of the branch should be grayed out.

**Environment**
VS Code:
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Git Graph: 1.12.0

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/775650/61617980-2b098380-ac6c-11e9-89ed-e413e536f310.png)

**Additional context (optional)**

**Comment by mhutchie** [comment]
Merge commits are greyed out (can be toggled by the setting `git-graph.muteMergeCommits`), NOT commits that are not on the current branch.

I hope this explains why the current behaviour is expected.

**Comment by basvdlinden** [comment]
I understand now. Makes sense. I can always use the Branch filter in order to hide commit not part of the current branch.

I am used to other tools that have the behaviour, I was expecting. So when showing **multiple** branches it can make decition making easier if it is clear what is not part of the current branch.

Do you think it makes sense to add a feature request for this?

Thanks.

**Comment by mhutchie** [comment]
If you would find this useful, please raise it as a feature request.

I’d be happy to add it in an upcoming release!
