### ISSUE TITLE
brilliant

### ISSUE THREAD

**Issue by marchage** [mhutchie/vscode-git-graph#14]
Sorry for abusing an issue for this but... 

Love the extension, absolutely brilliant, 
# a missing feature in vscode

You had that other git log extension but it had rendering isssues which required me te browse a page in history and back every time I opened it (still, better then nothing). But I will see if I can post a review for you on MS's marketplace, in a few hours.

Cheers.

**Comment by mhutchie** [comment]
Thank you for your feedback & the review!
