### ISSUE TITLE
Support .mailmap file for displaying author names

### ISSUE THREAD

**Issue by t-gehring** [mhutchie/vscode-git-graph#143]
**Describe the feature that you'd like**
Git supports using a .mailmap file, so that if a person has made commits under several names or email addresses, these commits can still be grouped together. The extension seems to currently ignore this, but it would be great if the Author column and commit views made use of it.

**Additional context (optional)**
More information about the .mailmap file is [here](https://git-scm.com/docs/git-check-mailmap).

**Comment by mhutchie** [comment]
Thanks for this suggestion! This would definitely be nice functionality to have in Git Graph!

**Comment by mhutchie** [comment]
There is now a new setting `git-graph.useMailmap` that enables the use of .mailmap files when displaying author & committer names and email addresses. By default it is disabled.

This will be available in v1.13.0.

If you'd like to use it before the next release, you can download [v1.13.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.13.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
