### ISSUE TITLE
Make possible to open from CLI

### ISSUE THREAD

**Issue by voxpelli** [mhutchie/vscode-git-graph#144]
I've traditionally used GitX, but is now moving towards using Git Graph, but my muscle memory still writes `gitx` in the CLI to open a graphical view of all changes.

Would it be possible to create a way to open Git Graph for a specific folder from the CLI? Does VS Code allow extensions to do such thing? (Else this would have to result in a feature request towards VS Code as well)

**Comment by t-gehring** [comment]
As far as I can tell, this seems to be a missing feature in VS Code. If you could provide a command to run at startup, then you could alias `gitx` to `code -n --run-command git-graph.view`, but that's not something that it lets you do yet.

You can kind of fake it with an extension called "Auto Run Command", which will run a command for you at startup with a few potential conditions, such as a file existing. You could sort of get the desired behaviour by installing the extension, adding
```
"auto-run-command.rules": [
    {
        "condition": "hasFile: launch-git-graph",
        "command": "git-graph.view",
        "message": "Opening Git Graph"
    }
]
```
and having a script `gitx` that does something like
```
touch launch-git-graph
code -nw
rm launch-git-graph
```
which is fairly messy, and slow as the extension has a 5s delay, but until VS Code lets you run a command at startup it's probably the closest you'll get.

**Comment by mhutchie** [comment]
@voxpelli Thanks for raising this feature request, this would definitely be nice to have!

Thanks @t-gehring for your approach, I hadn't heard of the "Auto Run Command" Extension before.

I couldn't find anything in the Visual Studio Code API documentation that enables this functionality for extensions (thanks @t-gehring for confirming this).

I also checked that command line arguments (e.g. `code ./ --git-graph`) are not passed to Node.js's `process.argv` (which I had hoped might work).

I'll close this issue for now until Visual Studio Code provides a mechanism to do so. If you'd like this functionality, please raise a feature request in [vscode](https://github.com/Microsoft/vscode), I'll look out for when it becomes available, and reopen this request then.

**Comment by t-gehring** [comment]
VS Code currently has [an open issue](https://github.com/microsoft/vscode/issues/68148) for implementing this, though it doesn't seem to be getting much attention at the moment.
