### ISSUE TITLE
Ability to memorize "ignore date" option

### ISSUE THREAD

**Issue by ffxsam** [mhutchie/vscode-git-graph#145]
**Describe the feature that you'd like**

It would be nice if the extension remembered our last choice for "Ignore Date". Every time I rebase, I have to uncheck it.

**Additional context (optional)**

![image](https://user-images.githubusercontent.com/12532733/61966583-90c17c80-af98-11e9-9985-14ef0e2f2e6b.png)

**Comment by mhutchie** [comment]
Thanks for making this suggestion, this would definitely be nice to have.

This is actually quite easy to implement, however some thought needs to go into if (all / which subset) of dialog checkboxes should remember the users last choice. I think it would be confusing / mistake prone if only this one dialog checkbox is remembered, as I think it would be a natural assumption for users that if one is remembered, then they all are. However, I think some dialog checkboxes shouldn’t be remembered (e.g. force delete for branches).

What are your thoughts on this?

**Comment by mhutchie** [comment]
There are now four new extension settings to set the default options on the following dialogs:
* Add Tag
* Create Branch
* Rebase

This will be available in v1.13.0.

If you'd like to use it before the next release, you can download [v1.13.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.13.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by ffxsam** [comment]
@mhutchie Hey Michael, sorry I didn't get back to you! Having them as settings makes sense, I think. Looking forward to the update!
