### ISSUE TITLE
Add setting for the shell used when a terminal is opened

### ISSUE THREAD

**Issue by t-gehring** [mhutchie/vscode-git-graph#149]
**Describe the improvement that you'd like**
Starting an interactive rebase opens a new terminal pane. It would be nice if there was an option for the shell used for this, e.g. using Git Bash on Windows instead of cmd or PowerShell. I don't want to set Git Bash as the global default in VS Code, but for interacting with git it's far superior.

**Comment by mhutchie** [comment]
Thanks for this suggestion, I’ll add support for this in an upcoming release!

**Comment by mhutchie** [comment]
This will be available in v1.13.0.

If you'd like to use it before the next release, you can download [v1.13.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.13.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
