### ISSUE TITLE
Add support for CP1252 encoded files

### ISSUE THREAD

**Issue by alanFaccin** [mhutchie/vscode-git-graph#150]
Como faço para definir a codificação cp1252 no git graph ? 

https://uploaddeimagens.com.br/imagens/screen_shot_2019-07-30_at_15-53-18-png

**Comment by mhutchie** [comment]
Git Graph currently doesn’t support alternative character encodings. I’ll definitely add support for this in an upcoming release!

Would it be possible for you to provide a CP1252 encoded file (even if it just contains a single line where there is currently an encoding issue)? This way I can be 100% sure that my implementation will work for you.

**Comment by mhutchie** [comment]
There is now a new setting `git-graph.fileEncoding` that lets you specify the encoding used by the extension when retrieving a specific version of repository files (e.g. in the Diff View). In your case, you would set it to `cp1252`. This will be available in v1.13.0.

If you'd like to use it before the next release, you can download [v1.13.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.13.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
