### ISSUE TITLE
Allow resizing of the Commit Details View

### ISSUE THREAD

**Issue by charlesg99** [mhutchie/vscode-git-graph#151]
Thanks so much for this extension! Really clean and useful!

It would be nice to be able to resize the Commit Details View to display all files in a large commit. Ideally it would be done dynamically with the mouse by dragging (like the column headers), but adding a setting to set a custom fixed size could be an alternative.

**Comment by mhutchie** [comment]
Thanks for making this suggestion, this would be great to have in Git Graph!

**Comment by mhutchie** [comment]
Which dimension(s) would you like to be resized (file tree width, height or both)?

**Comment by charlesg99** [comment]
I'd love to be able to resize the height of the whole "Commit Details View". Hopefully I'm naming it correctly, but I'm referring to the linear "window" that appears when selecting a commit and that contains the commit information as well as the files changed in that commit (file tree). It would also be nice to be able to resize the width of the file tree, but it feels much less important from my standpoint. 

Thanks!

**Comment by mhutchie** [comment]
Thanks for providing the extra information @charlesg99! You are correct in calling it the Commit Details View.

I’ll add support for changing the height of the Commit Details View, and the width of the file tree, by dragging the appropriate border, just like the column headers.

Changing the height would be useful in situations where there are many files changed in the commit (as in your case), whereas changing the width of the file tree is useful when the repository contains a deep directory hierarchy and long file names.

**Comment by mhutchie** [comment]
This will be available in v1.14.0.

If you'd like to use it before the next release, you can download [v1.14.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.14.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by charlesg99** [comment]
Works great! Thanks!
