### ISSUE TITLE
Prune option for Fetch button

### ISSUE THREAD

**Issue by Kira-Lappo** [mhutchie/vscode-git-graph#154]
Currently Fetch button does simple `git fetch` command

But remote branch can be deleted after PR is completed and branch was deleted on the remote.

I'd like to have configuration for fetch button, or additional call option with the ability to prune deleted remote branches.

Git Graph : 1.12.1
VSCode : 1.36.1

**Comment by mhutchie** [comment]
Thanks for making this suggestion, this would definitely be great to have in Git Graph! I'll implement a method to prune deleted remote branches in an upcoming release.

**Comment by mhutchie** [comment]
This will be available in v1.12.0. I ended up implementing:
* A New setting `git-graph.fetchAndPrune` that enables pruning when fetching from remote(s) using the Fetch button on the Git Graph View Control Bar. Default: false (disabled)
* Fetch or Prune a specific remote from the Repository Settings widget.

If you'd like to use it before the next release, you can download [v1.13.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.13.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
