### ISSUE TITLE
Show root foler name, not opened folder name in "repo" droplist

### ISSUE THREAD

**Issue by thesoftwarejedi** [mhutchie/vscode-git-graph#158]
**Describe the improvement that you'd like**
Currently the "repo" drop list shows each directory name of the folder that is opened in the project.  If subfolders of the root are the folders opened, the names of these folders are shown instead of the folder name of the root of the repo.

**Additional context (optional)**
- I have 2 repos: "SharedTerraform" and "SharedPolicies", and each has a folder named "MyProject"
- I open SharedTerraform/MyProject and SharedPolicies/MyProject in VSCode resulting in 2 open folders in explorer named the same "MyProject" and "MyProject".
- Similarly in the git graph, it uses these identical names as the repo name instead of the root repo folder name.

**Currently, "repo" is not the repo, but the name of the folder within the repo.**

**Comment by mhutchie** [comment]
Thanks for raising this request! The current behaviour is definitely not ideal in your specific project / directory layout.

Currently, when the extension scans the workspace for repositories, the path it stores for the repo is not necessarily the root of the repository, it stores the highest level directory in your workspace that is within the repo. This was done to work around some limitations of the VSCode API.

I’ve come up with an alternative solution that will work for the project / directory layout you have, while still working within the limitations of the VSCode API. This would allow the extension to use the root directories of the repo, meaning that the repos shown for you are the actual repos "SharedTerraform" and "SharedPolicies".

**Comment by mhutchie** [comment]
This will be available in v1.13.0, which will be released in the next day. I took this opportunity to overhaul repository management to better deal with a variety of edge case project structures.
