### ISSUE TITLE
branch name display error

### ISSUE THREAD

**Issue by HeavenSky** [mhutchie/vscode-git-graph#160]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7927784/63096655-08d00080-bfa1-11e9-9ce5-2d68755b3a2d.png)

**Expected behaviour**
no shell color code

**Environment**
 - OS: MAC 10.14.6
 - Visual Studio Code Version:
version: 1.38.0-insider
commit : 8985ff7c9d38bd2ce7d1e6b58e40d27c5bbdb67b
date: 2019-08-15T07:34:22.748Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Screenshots (optional)**
Add any screenshots to help explain your problem.

**Additional context (optional)**

**Comment by mhutchie** [comment]
Thanks for reporting this issue.

1. What version of the extension are you using?
2. What configuration have you done to have shell color codes in branch names (please provide steps)? None of the 85,000+ extension users have reported this, and I can't replicate it either.

**Comment by mhutchie** [comment]
I found that setting the git config `color.branch` to `always` (instead of its default value `auto`) caused this issue to occur.

This has been fixed, and will be released in v1.13.0 (which will be released within a few hours).
