### ISSUE TITLE
Delete both local and remote branch

### ISSUE THREAD

**Issue by BryanHunt** [mhutchie/vscode-git-graph#161]
**Describe the feature that you'd like**
It would be nice if there was the option to delete the remote branch at the same time you are deleting the local branch.

**Comment by mhutchie** [comment]
Thanks for making this suggestion, this would definitely be a useful addition to Git Graph!

I'll add this in an upcoming release.

**Comment by mhutchie** [comment]
I've added a new option on the "Delete Branch" dialog to also delete the branch on the remote(s). This only appears if one or more remotes contain a branch with the same name as the branch being deleted.

This will be available in v1.16.0, which will be released in the next day.
