### ISSUE TITLE
Default to only showing the current branch

### ISSUE THREAD

**Issue by pgsandstrom** [mhutchie/vscode-git-graph#162]
**Describe the feature that you'd like**
I currently work in a huge project with dozens of branches. When I open Git Graph I'm most often only interested in viewing my current branch. I have two options to help resolve my use case:

1. Git Graph remembers what branch I was looking at the last time it was opened. In the "Branches" filtering dropdown an option is "HEAD" which always shows the current branch. This would imitate IntelliJ:s excellent version control viewer and is my own preferred solution. Then I would simply set "Branches" to "HEAD" and leave it there forever.

2. An alternative solution would be to add an option to simply default to filtering to the current branch when Git Graph is opened.

**Comment by mhutchie** [comment]
Have you tried using the extension setting [git-graph.showCurrentBranchByDefault](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#show-current-branch-by-default)? This will open the Git Graph to the current branch by default.

It seems like this setting solves the feature you're requesting (option 2). Please let me know if it does, or if you have tried it and are requesting something else.

**Comment by pgsandstrom** [comment]
Yes, that fixed it! So strange that I missed it. Thank you for the help, and thanks for the great extension!

**Comment by mhutchie** [comment]
I'm glad to hear that the setting solved what you were looking for!

I've been exploring for a while now how to make extension settings more apparent to users. With 35 settings (and constantly growing), the specific setting a user is looking for is easily lost in the Visual Studio Code Settings interface. Ultimately the volume of settings is necessitated by the huge spectrum of ways developers operate and the projects they work on, which requires customisations that are beneficial to some users but detrimental to others.

**Comment by Gerst20051** [comment]
This setting no longer seems to be available, but I believe that selecting `Auto` in the dropdown achieves the same behavior.

**Comment by TinyuZhao** [comment]
> This setting no longer seems to be available, but I believe that selecting `Auto` in the dropdown achieves the same behavior.

I couldn't find where `auto` is.
