### ISSUE TITLE
Automatic refresh

### ISSUE THREAD

**Issue by bboehmke** [mhutchie/vscode-git-graph#17]
**Describe the feature that you'd like**
Automatic update the graph on changes (commit/pull/merge/...) to the git repository.

**Additional context (optional)**
I would like to use this plugin for git trainings or demonstrations. 
Here it would be perfect if the graph will update automatically to the current state of the repository.
Actually the graph must be refreshed manually with a focus change or a click on refresh.

Similar to [GitUp](https://gitup.co/) (sadly Mac only).

**Comment by mhutchie** [comment]
Thanks for the suggestion! I work to have this available within the next two weeks.

**Comment by mhutchie** [comment]
This is now completed, and will be available in 1.4.3.

**Comment by bboehmke** [comment]
Works fine.

**Comment by rndmerle** [comment]
Hello.
Apparently this feature has been implemented a long time ago but it seems it doesn't work the way I expected it to work, or I misunderstood something.
Currently, with Git Graph being open and my local branch being behind origin, if I `git pull` in the VSCode terminal Git Graph do not refresh to reflect that (it only does later from automatic refreshing)

**Comment by mhutchie** [comment]
Hi @rndmerle,

Git Graph utilises Visual Studio Code’s File System Watcher to detect file changes within the repository, and then it will automatically refresh the Git Graph View to reflect the changes. This is the only way to achieve this in Visual Studio Code extensions.

Unfortunately the Visual Studio Code File System Watcher has some known limitations, some of them are (but not limited to):
* It only triggers events from files within the Visual Studio Code workspace, even if a watcher is set on the root of the repository that is outside of the workspace.
* It can be a bit flaky for File System events from network attached storage.
* It has its own internal processing & filtering of events that can make it hard to detect that a file change actually occurs.
* It handles events from some Operating Systems subtlety different than others.

I expect that one of these scenarios, or another known limitation of the Visual Studio Code’s File System Watcher is unfortunately preventing the automatic refresh mechanism of the Git Graph View from triggering as you would expect on your machine and/or projects workspace.

Considering the automatic refresh functionality has been available for almost a year now, none of the other 300,000+ users have indicated the current approach is unreliable, and there being no suitable alternative method to implement this feature, I don’t think any further action needs to be taken at this point in time.

As Visual Studio Code is regularly updated and improved, it’s also highly likely that they will improve their File System Watcher, which will immediately make the Git Graph View’s automatically refresh mechanism work more reliably.

Also, if I find a more reliable alternative to the Visual Studio Code File System Watcher, I definitely want to & will implement it.

**Comment by rndmerle** [comment]
Thanks a lot for the detailled explanation :) And keep up with the good work
