### ISSUE TITLE
Drop commit

### ISSUE THREAD

**Issue by borekb** [mhutchie/vscode-git-graph#174]
**Describe the feature that you'd like**
I'd like to right-click a commit in Git Graph and select a **Drop Commit** command, which would basically run a rebase, omitting the commit.

**Additional context (optional)**
Sometimes, I work in a feature branch and commit to it even things that are not strictly related to the it (so that I don't lose the flow). After I'm done, I use `cherry-pick` to copy the commits to a new branch but am left with the original commits in the original branch.

At this point, I need to run `git rebase -i HEAD~5` or similar and delete the commits I no longer need.

It would be great if I could do this directly in the UI. It would be a sibling feature to **Revert...**.

**Comment by mhutchie** [comment]
Thanks for raising this feature request, this would definitely be useful to have in the Commit context menu.

This [page](https://sethrobertson.github.io/GitFixUm/fixup.html#remove_deep) suggests the command the extension should run to drop a commit is `git rebase -p --onto SHA^ SHA`. Although there does appear to be some issues with this command.

From reading the Git documentation [here](https://git-scm.com/docs/git-rebase), the argument `-p` is now depreciated and has been replaced with `--rebase-merges`.

From what I can see, the command should now be `git rebase --rebase-merges --onto SHA^ SHA` (I haven’t tested it yet). Please let me know if you’re aware of a better command to drop a commit (using its commit hash).

**Comment by borekb** [comment]
I didn't even think `--onto` was necessary but didn't properly play with it. Here's how I would naively / manually do it:

1. Count which commit I want to drop. For example, let's say I want to drop the fourth most recent commit in my feature branch so the number would be `4`.
2. I'd run `git rebase -i HEAD~4`.
3. I'd set the rebase operation to `drop` next to the commit I want to get rid of.
4. I'd save the todo and close the file.

I'm going to read the `git-rebase` docs to understand this better, thanks for considering this feature request so carefully.

**Comment by mhutchie** [comment]
This will be available in v1.15.0.

If you'd like to use it before the next release, you can download [v1.15.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.15.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by itsmuaaz** [comment]
I dropped a commit accidentally and need to undo this, is this possible in any way?

**Comment by mhutchie** [comment]
Hi @MuathAmer,

In the Git Graph View’s Repository Settings Widget, you should be able to temporarily turn on “Include commits only mentioned by reflogs”. This should allow you to see the dropped commit, and then perform the required actions to include it back into your branch.

**Comment by itsmuaaz** [comment]
@mhutchie 
Very helpful and quick! Thank you so much!
