### ISSUE TITLE
Squash selected commits

### ISSUE THREAD

**Issue by SreeChandan** [mhutchie/vscode-git-graph#179]
**Describe the feature that you'd like**
Squash selected commits.

**Additional context (optional)**
I'm currently a casual user of git. So pardon me if I'm not making sense.
I was looking to see if there was an extension for VS Code that supports squashing multiple commits the way GitKraken does.
I came across this closed issue #63. It's a bit similar. But I'm not looking to merge my develop branch to master yet. I just want to squash some commits together.

**Comment by mhutchie** [comment]
Thanks for raising this feature request! A squash option for commits would definitely be a great feature to have in Git Graph!

Note: The challenge that I see implementing this is when & where should the context menu item for this action be presented to the user. I’m sure there will be an intuitive solution for this, I’m just noting this for my later reference.

**Comment by mhutchie** [comment]
@SreeChandan, I'm going to close this feature request as it will be implemented as part of the newly raised (broader) feature request #182 for multi-commit operations. This new feature request includes squashing multiple selected commits (this feature request), along with similar operations that would be possible when multiple commits are selected. They all require a multi-commit selection mechanism, that will be the main complexity in delivering these new actions (hence why I'm grouping this into the new feature request).

Please monitor #182 for future updates on the progress of this feature.
