### ISSUE TITLE
Add support for ISO Dates

### ISSUE THREAD

**Issue by Gurran** [mhutchie/vscode-git-graph#185]
**Describe the feature that you'd like**
I'd like to be able to see the dates in ISO 8601 fromat.

**Additional context (optional)**
Git already supports this with `git log --date=iso`.

**Comment by mhutchie** [comment]
Thanks for raising this feature request, this would definitely be a nice addition to Git Graph!

Dates and times appear in three places in Git Graph:
* Date Column (an ideally short date & time value to minimise the volume of text in the table) [e.g. `25 Sep 2019 17:30`]
* Commit Details View (full date & time value) [e.g. `Wed Sep 25 2019 17:30:13 GMT+1000`]
* Annotated Tag Details (full date & time value) [same as Commit Details View]

What would you suggest for the short an long formats under ISO 8601? How about:
* Short format: `yyyy-mm-dd hh:mm` -> `2019-09-25 17:30`
* Long format: `yyyy-mm-dd hh:mm:ss +|-hhmm` -> `2019-09-25 17:30:13 +1000`

**Comment by Gurran** [comment]
Long format:
To make it as simple as possible. I suggest same long date format that git uses.
`yyyy-mm-dd hh:mm:ss +|-hhmm` -> `2019-09-26 10:48:59 +0200`

Short format:
I think your suggestion looks really good.
`yyyy-mm-dd hh:mm` -> `2019-09-25 17:30`

**Comment by mhutchie** [comment]
This will be available in v1.17.0.

If you'd like to use it before the next release, you can download [v1.17.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.17.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by Gurran** [comment]
Thank you so much for including this change. It really means a lot to me! 😃
