### ISSUE TITLE
enhance - add tag to commit : add auto push checkbox

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#186]
**Describe the feature that you'd like**
For the _Add tag to commit_ it would be useful to have a checkbox, that let us push directly after creating the new tag

It would be here 
![image](https://user-images.githubusercontent.com/44493964/65674968-b11bbf00-e04d-11e9-8543-feed1cf665f9.png)

**Additional context**
Currently, we have to add, and after to push, and sometime person completely forget to do that.
Since CI/CD sometime use those tag to publish automatically a new production or dev version on server, it would help some people not to forget to push it :)

**Comment by mhutchie** [comment]
Thanks for raising this feature request, this would definitely be nice to have!

When I implement this:
* It will be a checkbox if only one remote exists, or a dropdown if multiple remotes exist.
* I'll add a new extension setting to set the default value of the "push" input.

**Comment by mhutchie** [comment]
This will be available in v1.17.0.

If you'd like to use it before the next release, you can download [v1.17.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.17.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
