### ISSUE TITLE
Ability to select which remotes to hide/show branches in the graph

### ISSUE THREAD

**Issue by json2d** [mhutchie/vscode-git-graph#190]
Hey awesome project you got here - it's saved me a lot of time git-ing, and the UX feels good and thought out.

However I do find that the graph gets a bit noisy when I'm on projects with more than 1 remote. 

Here's the really straightforward solution I'm proposing:

**Describe the feature that you'd like**
A clear and concise description of what you'd like to be included in Git Graph.

Give the user the ability to select which remotes to hide/show branches.

**Additional context (optional)**

One approach to doing the UI for this is the add a button next to the **Show Remote Branches** toggle, and when that button is clicked: render a modal with toggles to hide/show each remote

![image](https://user-images.githubusercontent.com/143295/66057540-e66d5480-e506-11e9-8b02-4dc989908b41.png)

**Comment by mhutchie** [comment]
Thanks for the feedback and raising this request! This would be great functionality to have in Git Graph.

I already have plans for the little space that is left on the top control bar for other already open feature requests to do with filtering commits (I’d like to avoid another button if at all possible).

I think this functionality would be best suited in the Settings widget on the Git Graph View (cog icon), as under the Repository Settings section there is already a record for the configuration of each remote individually. I can simply add a “Show” column with checkboxes for each remote that toggle their hide/show state.

**Comment by json2d** [comment]
@mhutchie cool glad you think so too. 

You're right, the Settings widget is a great spot for this. 

Though how about an open/closed eye icon toggle button to the left of each remote item like this to keep it simple and compact:

![Show-Hide Remote w Icon Button](https://user-images.githubusercontent.com/143295/66089882-09235b80-e54f-11e9-8e2d-adb13da5f111.png)

**Comment by mhutchie** [comment]
Great idea for the eye icon, it’s much better than a checkbox.

When I have all the ground work in place, I’ll look into a few position options to see what works the best out of: left, right, or in a new column between a pair of existing a columns.

**Comment by mhutchie** [comment]
I found that having the eye icons to the left of each remotes name (as you suggested) functioned the best overall. Thank you for raising this feature request and your implementations suggestions!

This is what it looks like:
![image](https://user-images.githubusercontent.com/5315753/66254090-f14d1100-e7b4-11e9-9e52-a6e709833fe2.png)

This will be available in v1.17.0, which will be released in the next day.

**Comment by json2d** [comment]
Just check it out in v1.17.0 - looking good! I'm glad I was able to contribute a little to the effort.

One thing I think it still needs to make the UX 💯 and less potentially confusing is to show on the main page just how many/which remotes are being shown - like something to this effect:

![Show number of remotes shown](https://user-images.githubusercontent.com/143295/66419257-c2f84d00-e9d1-11e9-8b71-a6f431b257a2.png)

**Comment by mhutchie** [comment]
Thanks for the feedback! 👍

For the same reason as I previously mentioned, there just isn't enough space to add the text "(1/2 remotes)" in the control bar. Reducing it to "(1/2)", although short enough, would likely be misinterpreted as 1/2 remote branches, not branches from 1/2 remotes.

I considered adding an info icon to the right of the "Show Remote Branches" checkbox such that:
* When the mouse is hovered over it, a message like 'Branches from the remote "upstream" are currently hidden' would be shown.
* The icon would only be shown if one or more remotes are hidden (consumes no space if all are visible).
* This would visually indicate on the main page if remotes are hidden, and provide a way to see which remotes they are without a click.

I decided against this (at least for 1.17.0), as I figured it was fairly reasonable to assume that:
* Users would know that they hid a remote - As it is opt in.
* They would also know how to see which remotes are hidden & toggle them - As they hid it in the first place.
* A single click isn't that much more effort than a hover (and I don't think there is an alternative way to display this info without using a hover in some form).
* I expect that the users using this feature would either:
    * Be hiding the remote while they do a short task on the graph - In which case they don't need a reminder for something they just did.
    * Almost always want to keep a remote hidden, and only show it occasionally if they were pulling from / pushing to it - If it's the norm for them, they would expect it to be hidden.

I intended (and will continue to) monitor feedback from this release to see if there are indications of possible confusion. If there is, I'm sure a method (similar to what we've discussed) can be implemented to clarify the situation, and I can have this adjustment available in one of the next releases.

---

I always aim to get a feature included in the extension first (to a standard that is functionally & core UI complete), and then improve it in subsequent releases as I get user feedback. With the user community growing so rapidly, and so much functionality being requested for the extension, I'm constantly balancing the delivery of features to pass on the most value to users as fast as possible. Almost every feature can be taken an extra 10% to make it better, but without demand from users and diminishing returns I've found it works well to gauge user feedback and spread the extra 10% over the next few releases.
