### ISSUE TITLE
Splitting vscode package into @types/vscode and vscode-test

### ISSUE THREAD

**Issue by iboyperson** [mhutchie/vscode-git-graph#191]
VSCode has split the vscode package into @types/vscode and vscode-test. This project should likely be updated accordingly.

Refrences:
microsoft/vscode#71048
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_36.md#splitting-vscode-package-into-typesvscode-and-vscode-test

**Comment by mhutchie** [comment]
Thanks for making me aware of this!

This will be included in v1.17.0, which will be released in the next day.
