### ISSUE TITLE
Keep branch color no matter which the branch is with the latest commit

### ISSUE THREAD

**Issue by sprite-1** [mhutchie/vscode-git-graph#196]
**Describe the feature that you'd like**
I would love an option to be able to keep the colors assigned to the branches regardless of which of them has the latest commit

**Additional context (optional)**
It's a bit confusing that the colors keep changing

**Comment by mhutchie** [comment]
Thanks for raising this feature request!

I'm closing this for the same reason, and due to the same explanation in [this comment](https://github.com/mhutchie/vscode-git-graph/issues/194#issuecomment-539877857), which was on a very similar feature request.

**Comment by sprite-1** [comment]
Ah whoops, I somehow missed that when I did a quick scan of the issues, my bad
