### ISSUE TITLE
Extension settings for disabling context menu items

### ISSUE THREAD

**Issue by peterdickx** [mhutchie/vscode-git-graph#198]
Add an Extension Setting to allow educators to enable or disable every context menu action of Git Graph individually through a JSON format (see example below). This would allow to gradually enable more actions:

Example JSON config:
{
    "commit": {
        "addTag": true,
        "createBranch": false,
        ...
    },
    "branch": {
        "checkoutBranch": true,
        "renameBranch": false,
        ...
    },
    ...
}

![image](https://user-images.githubusercontent.com/19954023/66653643-cb05f600-ec38-11e9-95a3-431be6fe589d.png)

**Comment by mhutchie** [comment]
Thanks for raising this feature request! I'll have this implemented in the next release.

**Comment by mhutchie** [comment]
This will be available in v1.18.0.

If you'd like to use it before the next release, you can download [v1.18.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.18.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
