### ISSUE TITLE
FR: Add git reset to context menu

### ISSUE THREAD

**Issue by Gruntfuggly** [mhutchie/vscode-git-graph#2]
One thing stopping me from using this instead of gitk is not being able to reset from the tree. I could have a look at adding it myself if you like...

**Comment by mhutchie** [comment]
Great suggestion, that sounds quite useful.

Just to confirm, are you referring to performing the reset action described on https://git-scm.com/docs/git-reset by right clicking on a specific commit. If so, which options would you like available (I was thinking --soft, --mixed & --hard).

**Comment by Gruntfuggly** [comment]
To be honest, reset hard would be enough to be going with - I don't use soft or mixed that often to need it.

**Comment by mhutchie** [comment]
Awesome, I'll add this in the next release! As I'm adding in --hard, I might as well add --soft and --mixed as well, as it's minimal additional work but provides more flexibility.

**Comment by mhutchie** [comment]
Ready for release in 1.3.0 (should be in the next day or so)
