### ISSUE TITLE
Hide "Git Graph" when the workspace has no git repository

### ISSUE THREAD

**Issue by ducalex** [mhutchie/vscode-git-graph#20]
The "Git Graph" status bar button should be hidden when the window/workspace has no git repository.

**Comment by mhutchie** [comment]
Thank you for the feedback, this is a great idea!

I’m currently focusing on feature requests that add the most functionality for the most users, but this would definitely be nice to have once I’ve finished the higher prioritised items.

**Comment by mhutchie** [comment]
This is now completed, and it will be available in v1.4.3.

If you'd like to try it out before the next release, it is available in [v1.4.3-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.3-beta.1), which can be downloaded and installed following the instructions provided on [Downloading & Installing Releases](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
