### ISSUE TITLE
Show files in commits in list view

### ISSUE THREAD

**Issue by Pr07o7yp3** [mhutchie/vscode-git-graph#202]
First of all, thanks for this extension. It's very useful.

Now, about the feature.
When reviewing a commit with many edited files it's hard to navigate in that tree view.
It would be very nice if we have an option to change the view type between a tree and list one.

**Comment by mhutchie** [comment]
Thanks for raising this feature request! I’ll have it available in the next realease.

**Comment by mhutchie** [comment]
This will be available in v1.18.0.

If you'd like to use it before the next release, you can download [v1.18.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.18.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
