### ISSUE TITLE
Emphasis of the branch containing the commit being hovered over

### ISSUE THREAD

**Issue by ShoshinNikita** [mhutchie/vscode-git-graph#203]
At first, thank you for the extension. It is awesome! :)

Now get to the issue. There's a problem with exploring Git history with large number of branches. It is hard to understand which commit in what branch is picked. It would be really convenient to "start" highlight with branch line. I think screenshots can describe it better:

| Now | Want |
| ------ | ------ |
| ![1_now](https://user-images.githubusercontent.com/30220965/67805084-55f04880-faa1-11e9-942b-68303f727852.png) | ![1_after](https://user-images.githubusercontent.com/30220965/67805007-322d0280-faa1-11e9-87e7-f96ea115ab56.png) |
| ![2_now](https://user-images.githubusercontent.com/30220965/67805018-35c08980-faa1-11e9-94c1-33da419f7ee3.png) | ![2_after](https://user-images.githubusercontent.com/30220965/67805016-3527f300-faa1-11e9-858e-11f76f74ca1b.png) |

I am not sure it is possible. But I would like to learn your thoughts.

**Comment by mhutchie** [comment]
Thanks for your feedback & raising this improvement request!

Unfortunately, to implement "starting" the highlighting at the branch line would be almost impossible to achieve. The graph is rendered as an SVG in front of the table, and the highlighting is just changing the background colour of the table row when the user hovers over it. The only way I can think to achieve this would be to:
* Use a mouse event triggered when the user hovers over a row.
* Generate a SVG path filled with the background colour of the view that is rendered behind the existing graph content to cover up the table row highlighting.
* Selecting, generating and rendering a good path for this purpose is complicated, as well as handling the impact of other user events (such as graph refreshes, tooltips, context menus etc.)

Even if this was implemented, I can't think of an elegant way to handle the following scenarios:
* Commit circles at the head of a branch _(there is no branch line for the top half of the row)_
* If the user has resized the graph column smaller than its full width (common in large repos), such that the commit circle is hidden _(where would the highlighting start)_
* A new ref layout option may be coming soon that places the ref labels to the left of the graph _(by starting the highlighting at the branch line, it wouldn't extend left of the graph to include the ref labels - making it harder to identify which commit they are for)_

---

I've had a think and experimented with some other solutions to the scenario this request is trying to improve. Here are my thoughts:

There are three main ways I can think of to make the branch more apparent:
* Change the existing row highlighting to stop at the branch
    * Screenshots provided in your suggestions.
    * Thoughts:
        * My reasoning against this approach is provided above.
        * When I showed your "want" screenshots to other users, without telling them context of this request, they thought it looked like a rendering bug, not a feature. When I told them the context of this improvement request, they felt the existing commit circle was more than adequate in identifying which branch the highlighted commit belongs to.
* Emphasise the circle of the commit:
    * Make the commit circle larger on the row being highlighted.
    * ![image](https://user-images.githubusercontent.com/5315753/67841376-0c106c80-fb4c-11e9-86c5-9ef7f4c7fbb4.png)
    * Thoughts:
        * Making the circle bigger in practice didn't make it noticeably easier to work out the branch it was on. I found it hard to notice that a circle was even any bigger (when looking at it in the context of an entire view with a reasonable complexity graph).
        * When I showed this to other users, they had the same impression as I did, and again felt the same way about the adequacy of the existing extension behaviour.
* Emphasise the branch line belonging to the commit
    * Make the branch line containing the highlight commit wider.
    * ![image](https://user-images.githubusercontent.com/5315753/67844810-847a2c00-fb52-11e9-9e45-50dcd0627d40.png)
    * Thoughts:
        * Although it is easy enough to widen the line the example screenshot, it's just not feasible to do this in the general case. For example, in your first screenshot, a segment of the pink line, green line, and a second segment of the pink line would have to be made wider.
        * After showing the screenshot to some users, they realised that as almost the entire UI is covered by a hover event for some commit, no matter where their cursor was, the graph would be almost constantly changing. Consequently, it would be distracting when the user isn't needing this functionality, and make the interface far less responsive (as it would force a (costly) graph render every time the cursor moves over a different commit - i.e. all of the time).

All three of these approaches have the following complexities, that make them time consuming to implement relative to the little value perceived from the user feedback I've received so far:
* Handling large volumes of mouse events with minimal performance impact.
* Handling the impact of user events (such as graph refreshes, tooltips, context menus, Commit Details / Comparison Views etc.) on the chosen emphasis.

---

Based on all of the above considerations, I'll close this issue for now and add it to the backlog. If users reading this in the future have other suggestions, please reply to this thread.

I'm keen to make user experience improvements like this, as long as they add value and don't come at a cost (e.g. performance). If other suggestions are raised, I'd be happy to reconsider, re-open, and implement them.

**Comment by ShoshinNikita** [comment]
Thank you for the quick response. I appreciate your investigation and have to agree with conclusions. I will think about other ways to highlight the the picked commit. If I come up with any idea, I will write it here.
