### ISSUE TITLE
Plugin locks *.asar files

### ISSUE THREAD

**Issue by ToMGitHubN** [mhutchie/vscode-git-graph#209]
I am developing an electron app.

The plugin seems to lock * .asar files in the project output directory. 
This is in .gitignore and vscode-git-graph is an extension that doesn't need to be scanned.
Can this extension exclude files contained in .gitignore or * .asar files?

I found a useful URL with the extension * .asar.
https://electronjs.org/docs/api/environment-variables#electron_no_asar

Thank you.

**Comment by mhutchie** [comment]
This will be available in v1.19.0.

I was able to replicate the locking behaviour you were getting on *.asar files, and have made a fix that resolves it (confirmed during my own testing).

Could you please download and install the beta release [v1.19.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.19.0-beta.0), and confirm that this has fixed the locking issue you were observing?

FYI: Installation instructions are provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
