### ISSUE TITLE
git fetch should also purge

### ISSUE THREAD

**Issue by MaurGi** [mhutchie/vscode-git-graph#211]
**Describe the feature that you'd like**
A clear and concise description of what you'd like to be included in Git Graph.

When clicking on the fetch button, traces of remote branches that no longer exist stick around locally. I end up calling `git fetch -p` from the command line.

I would expect cleaning old branches to be the default behaviour.
If that default could not work for everyone, then maybe add an option for it in the settings?

**Additional context (optional)**

Looooove this plugin, I use it all the time!

**Comment by mhutchie** [comment]
The command you mentioned `git fetch -p` "prunes" the remote.

The fetch button can already be configured to prune the remote at the same time as fetching, using the extension setting [Fetch And Prune](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#fetch-and-prune).
