### ISSUE TITLE
filter graph by author 

### ISSUE THREAD

**Issue by nailuoGG** [mhutchie/vscode-git-graph#212]
**Describe the feature that you'd like**
A clear and concise description of what you'd like to be included in Git Graph.
while serviral people work in same repository, I'm usually interested in : 

1. my branch - > filter by branch name 
2. my commit  > filter by commit Author 

**Additional context (optional)**

![image](https://user-images.githubusercontent.com/4554827/68912614-97683f80-0793-11ea-90b8-9347af9262f3.png)

**Comment by mhutchie** [comment]
> 1. my branch - > filter by branch name

Branches can already be filtered using the "Branches" dropdown. You can also enable the extension setting [Show Current Branch By Default](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#show-current-branch-by-default) for Git Graph to automatically filter by the checked out branch when it is first opened.

> 2. my commit > filter by commit Author

This has been already requested in the existing open feature request #171, and is scheduled for delivery in an upcoming release.

---

I'm closing this feature request as it doesn't request any new functionality that isn't already available, or scheduled for delivery.

**Comment by pzpzpzp2** [comment]
@mhutchie branches only lets you filter specific branches. it doesnt let you filter by author, which is what the feature request was. this feature doesn't seem to exist at all?
