### ISSUE TITLE
enhance - settings : on delete branch auto selected "Force Delete"

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#213]
**Describe the feature that you'd like**
Would be nice to be able, in the settings, to Force Delete by default.  
![image](https://user-images.githubusercontent.com/44493964/68927664-85cd6a80-0788-11ea-9fe6-6cab1a45318f.png)

**Comment by mhutchie** [comment]
Thanks for raising this improvement request, I’ll add it in the next release!

**Comment by mhutchie** [comment]
This will be available in v1.19.0.

If you'd like to use it before the next release, you can download [v1.19.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.19.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
