### ISSUE TITLE
Keyboard shortcut to scroll to the HEAD commit

### ISSUE THREAD

**Issue by yangjuncode** [mhutchie/vscode-git-graph#218]
when scroll too far with many branch, it is hard to go to current git position.

**Comment by mhutchie** [comment]
Thanks for raising this feature request!

I'll add a new keyboard shortcut that scrolls the view to the head commit `CTRL+H` in the next release.

**Comment by mhutchie** [comment]
This will be available in v1.19.0, which will be released in the next day.

**Comment by danstreeter** [comment]
Hey, Was looking for exactly this whilst working on a rather large active repo however it doesnt seem to work.
I'm running `1.30.0` on OSX.

Wondering if there are any settings anywhere I need to be checking to make this work?
