### ISSUE TITLE
Option to scroll to HEAD commit when opening view

### ISSUE THREAD

**Issue by yangjuncode** [mhutchie/vscode-git-graph#219]
now git-graph show the log in time descending order, but some times it's far from the current git ref position, maybe it should be an option.

**Comment by mhutchie** [comment]
The current behaviour is expected, however it would definitely be improved by having an Extension Setting to enable this new behaviour!

For now I'll set the new Extension Setting to disabled by default, however once the improvement request for keeping the Git Graph Control Bar visible when the view is scrolled, I'd consider changing it to be enabled by default.

**Comment by mhutchie** [comment]
This will be available in v1.20.0.

If you'd like to use it before the next release, you can download [v1.20.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.20.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
