### ISSUE TITLE
Extend settings with possibility to define what branch to show in a graph

### ISSUE THREAD

**Issue by janbejvl** [mhutchie/vscode-git-graph#22]
**Describe the feature that you'd like**
It would be nice user expierience to have the possibility to make graph showing only one branch by default or via settings. I usually prefer to browse a history of a single branch instead of all branches in one place.
My proposals:
1) Show a graph of default branch. This would be an option in settings where default is master, but I can specify custom default branch.
2) Either show a graph of current branch or show branch list to pick from after clicking on Git Graph at the bottom panel. Just like VSCode built-in branch switch works.

**Comment by mhutchie** [comment]
Thank you for the suggestion, this is a great idea!

I’m currently focusing on feature requests that add the most functionality for the most users, but this would definitely be nice to have once I’ve finished the higher prioritised items.

**Comment by mhutchie** [comment]
This is now completed. It will be available in 1.4.2, which will be released in the next hour.
