### ISSUE TITLE
Issue Linking: Global default Issue Regex and Issue URL

### ISSUE THREAD

**Issue by Konsonanz** [mhutchie/vscode-git-graph#223]
**Describe the feature that you'd like**
For the newly introduced feature `Issue Linking in Commit Messages`, I'd like to be able to set Global-/Workspace-defaults in the `settings.json` for the the used Regex and substitution URL.

**Additional context (optional)**
Thanks for this new feature, really liking it! I'm using a Workspace with a very large amount of repositorys cloned, but which all use the same Issue-IS format in their commits (in this case Jira-IDs, so a commit typicaly looks like: `SYS-1234: Introduce error-checking for BuildSystem`). I would like to set a Global and/or Workspace-default so that I do not have to re-configure the options for each and every repository.
Also, when setting these options in a Workspace and duplicating the Workspace (`Ctrl+Shift+P "Workspaces: Duplicate Workspace in new Window"`), the options will be unset again.

**Comment by mhutchie** [comment]
Thanks for raising this feature request! I considered providing an Extension Setting for the default values of the Issue Regex & Issue URL, however decided not to for the first release of this functionality.

The challenge is with the Issue URL, as for the vast majority of users it will be different for each repository (although there definitely are exceptions). This would require a method to check the url's of the repositories remotes, and determine path components from them if possible (which will be different for each Issue Tracking vendor).

I definitely want to improve this behaviour to make it much more automated!

**Comment by mhutchie** [comment]
This will be available in v1.20.0.

If you'd like to use it before the next release, you can download [v1.20.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.20.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by xxorathaa** [comment]
so im a bit late to the party here, but can this setting be set in settings.json somehow?

**Comment by oliver-niedermaier** [comment]
+1
The possibility to export/import the Issue Link config would be awesome.
