### ISSUE TITLE
Change global user name and email

### ISSUE THREAD

**Issue by cvphat4796** [mhutchie/vscode-git-graph#225]
**Can change global user name and email**
I want to change global user name and email of respository by UI.

**Comment by mhutchie** [comment]
Thanks for raising this feature request!

When I implement this, I'll have the user name & email fields, and a checkbox to set whether the global or local repo settings are in use. This would allow the user to either update the global user name & email, or override the global user name & email with local values for the specific repository.

**Comment by mhutchie** [comment]
This will be available in v1.21.0.

If you'd like to use it before the next release, you can download [v1.21.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.21.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
