### ISSUE TITLE
Show diffs for all files simultaneously when viewing commit

### ISSUE THREAD

**Issue by AlexIII** [mhutchie/vscode-git-graph#228]
**Describe the feature that you'd like**

Hi! I wanted to replace gitk with your extension, but it's lacking one critical feature: be able to show all diffs for all files simultaneously when viewing commit. It is very useful in situations when you have many files in one commit, but each of them bears very little changes.
In case you're not familiar, that's how it's done in gitk:

![diff](https://user-images.githubusercontent.com/10047074/70231191-a97a4400-177b-11ea-8ea1-be796817d8a4.png)

**Comment by mhutchie** [comment]
Thanks for raising this feature request and your feedback!

Although not explicitly mentioned in "Show File Diffs within the Git Graph View" #206, the functionality you've requested is almost certainly how I intend to implement the existing feature request.

I'll close this request for now, as I only keep one open issue for tracking each core functionality request. However, if #206 ends up being implemented differently, I'll re-open this request if tracking it separately becomes necessary.
