### ISSUE TITLE
Limit maximum width of Branches Dropdown (style)

### ISSUE THREAD

**Issue by evgenymarkov** [mhutchie/vscode-git-graph#232]
**Describe the Bug**

Block with buttons overlaps the search bar

![image](https://user-images.githubusercontent.com/16443248/70981772-d9541080-20c6-11ea-9ec9-d5fcc0c4cfa7.png)

**Steps to Reproduce**

1. Run "View Git Graph" command
2. See error in markup

**Expected Behaviour**

Block with buttons must be in line with the checkbox

![image](https://user-images.githubusercontent.com/16443248/70982628-5c299b00-20c8-11ea-8b56-092cb690070b.png)

**Environment**

 - Git Graph Extension Version: 1.19.1
 - Visual Studio Code Version: 1.41.0
 - Operating System: macOS 10.14.6

**Comment by willpower232** [comment]
Your branches dropdown is very wide, do you have a really long branch name?

**Comment by mhutchie** [comment]
You must have a branch that has an extremely long name, causing the dropdown to extend over the Control Bar Buttons, and overflow off the right of your screen. The dropdown's width is determined by the width of the longest branch name. The Control Bar Buttons should be in their current location (centered vertically and aligned to the right), it's just the dropdown extending too wide.

The screenshot below indicates how the Control Bar should look (without any very long branch names):
![image](https://user-images.githubusercontent.com/5315753/70984268-450d9c00-210e-11ea-9991-f0c7beffa8fb.png)

The current style is not "broken", a maximum width for the dropdown just isn't specified as it's fairly reasonable to assume branch names aren't too long (none of the 200,000+ other users of Git Graph have such long branch names that it causes an overflow issue).

I'll add a maximum width constraint on the dropdowns to resolve this for you. It will be available in the next beta release (available in the next day).

**Comment by mhutchie** [comment]
This will be available in v1.20.0.

If you'd like to use it before the next release, you can download [v1.20.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.20.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
