### ISSUE TITLE
Add always accepted checkbox to the checkout dialog

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#233]
**Describe the feature that you'd like**
On checkout issue, let the user check 
*  [  ]   Always accept

![image](https://user-images.githubusercontent.com/44493964/71076459-09aeb400-2186-11ea-8bfa-55735eea716e.png)

(Which will only be activated when the user select `yes`)

**Comment by mhutchie** [comment]
Thanks for this suggestion, I'll add it in the next release!

**Comment by rbalet** [comment]
@mhutchie You're amazing, like always thx a lot

**Comment by mhutchie** [comment]
This will be available in v1.20.0.

If you'd like to use it before the next release, you can download [v1.20.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.20.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
