### ISSUE TITLE
Emphasize the selected branch(es)

### ISSUE THREAD

**Issue by goyzhang** [mhutchie/vscode-git-graph#236]
When a repo contains a lot of branches, the git view can be very messy and hard to tell which commits are on the current branch:
![image](https://user-images.githubusercontent.com/24909320/71230601-3e0ca680-2325-11ea-91c7-6bd264a93f2e.png)

Is it possible to have an option that make other branches fade out or Bold the selected branch so we have a clear impression at the first look? Sample from gitextension:
![image](https://user-images.githubusercontent.com/24909320/71230699-a2c80100-2325-11ea-9b6b-f27b67effe7f.png)

**Comment by mhutchie** [comment]
Thanks for raising this request!

I've just been working on implementing #139, which will "mute" (grey out) the commits not part of the current branch. The muting will be controlled by an Extension Setting just like the existing option to Mute Merge Commits.

To grey out lines in the graph and/or bold them is definitely possible, however it would be extremely complex and time-consuming to achieve. I could only justify the time it would take if a significant portion of users indicate they would gain significant value from it.

As #139 has an extremely similar effect to this request, however is far more reasonable to implement, I'm working to release it first in v1.20.0 (in the next few days). I'll close this request for now and move it to the backlog, as I hope the other feature already mid-development will resolve or significantly ease this issue. I'll gather feedback from users in the weeks after v1.20.0 is released to see if #139 is adequate, or if the additional graph-based emphasis would be valued.

If I have an indication that this graph-based emphasis would be reasonably valued by users (and I feel it justifies the development time & complexity), I'll definitely re-open this feature request and implement it.

_Note: If you are another Git Graph user reading this response in the future, and would value graph-based emphasis of the selected branches, please like the first comment on this issue. This will allow me to re-prioritise it based on community interest._
