### ISSUE TITLE
add option to use --force-with-lease when pushing branches

### ISSUE THREAD

**Issue by erclu** [mhutchie/vscode-git-graph#239]
Would love to have this possibility, as it's at least marginally safer than force pushes. 

For context:

- https://git-scm.com/docs/git-push#Documentation/git-push.txt---force-with-leaseltrefnamegt
- https://blog.developer.atlassian.com/force-with-lease/

I think the argumentless option (without explicit refspecs) would be more than enough to have!

Sorry if it's already been requested or implemented, I couldn't find anything related.

**Comment by mhutchie** [comment]
Thanks for making this suggestion, it would definitely be great to have in Git Graph!

Thanks for also providing the documentation files, I haven’t had the need to use `—force-with-lease` for myself before.

Am I correct in saying that the `—force-with-lease` by itself is most commonly used, not the variations with additional arguments? If this is the case, a checkbox or radio button should by suitable on the Push Branch Dialog.

**Comment by erclu** [comment]
> Am I correct in saying that the `--force-with-lease` argument by itself is most commonly used, not the variations with additional arguments?

Yeah based on my extremely limited experience and knowledge I'd say so. The most common use case (at least for me!) would be to push --force-with-lease  after I rebased a branch.

> If this is the case, a checkbox or radio button should by suitable on the Push Branch Dialog.

 I too was thinking of either a checkbox/radio next to "Force Push" or a setting to switch between the two behaviours

**Comment by mhutchie** [comment]
This will be available in v1.21.0.

If you'd like to use it before the next release, you can download [v1.21.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.21.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
