### ISSUE TITLE
Show commit signature status

### ISSUE THREAD

**Issue by Gurran** [mhutchie/vscode-git-graph#240]
`git log` has the flag `--show-signature` that shows the signing status of a commit. 
It would be nice to see the signing status in git-graph when selecting a commit.

A  ✔️ or ❌ would suffice.

**Additional context (optional)**
Github has a simular feature 
![Commit Signing](https://user-images.githubusercontent.com/42462633/71713250-3ced7600-2e09-11ea-852f-5f023fc622d2.png)

**Comment by mhutchie** [comment]
Thanks for raising this request, this would definitely be nice to have!

I'll add this in the next release!

**Comment by mhutchie** [comment]
This will be available in v1.21.0, which will be released in the next few days.

I've added the commit's signature status to the right of the Committer in the Commit Details View (only for signed commits) by enabling the new Extension Setting `git-graph.showSignatureStatus`. Hovering over the signature icon displays a tooltip with the signature details.

![image](https://user-images.githubusercontent.com/5315753/71803534-23705680-30b5-11ea-9055-adb61b1f99f4.png)
