### ISSUE TITLE
Strange Ctrl+Tab behaviour

### ISSUE THREAD

**Issue by pomdtr** [mhutchie/vscode-git-graph#244]
**Describe the Bug**
Git graph view is not coherent with ctrl+tab behavior

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open tab_1
2. Open tab_2
3. Open Git Graph
4. Press Ctrl+Tab
5. You are redirected to tab_1

**Expected Behaviour**
Beeing redirected to tab_2

**Environment**
 - Git Graph Extension Version: 1.20.0
 - Visual Studio Code Version: 1.41.1
 - Operating System: Ubuntu 19.10

**Comment by mhutchie** [comment]
When I follow Steps 1 through 4 on both Windows 10 & Mac Catalina, I am redirected to tab_2 as you expect. The behaviour you're observing must be platform specific for Ubuntu.

All keystrokes such as `Ctrl`+`Tab` are processed and actioned by Visual Studio Code itself. Git Graph, or any other extension for that matter, has absolutely no way (and shouldn't be able) to interfere with Visual Studio Code features (such as the `Ctrl`+`Tab` behaviour). The behaviour your observing will occur whenever you open a Visual Studio Code [Webview](https://code.visualstudio.com/api/extension-guides/webview) from any extension (the Git Graph View uses a Webview like many other extensions).

Visual Studio Code has recently had numerous keystroke issues when the user has opened Webview's, each only occurring on particular platforms. Please report this bug to [vscode](https://github.com/Microsoft/vscode) so they can fix it.
