### ISSUE TITLE
Add "no-commit" option to merge dialog

### ISSUE THREAD

**Issue by mfmayer** [mhutchie/vscode-git-graph#248]
When doing "Merge into current branch..." add the option to do the merge without automatically creating the commit (--no-commit option in git merge). 

This could look like this:
![image](https://user-images.githubusercontent.com/8875306/72503803-dfabe880-383c-11ea-800e-93652cbcd049.png)

**Comment by mhutchie** [comment]
Thanks for raising this feature request, this option would definitely be nice to have!

I'll include it in the next release (a beta release with it should be available in the next 1-2 days).

**Comment by mhutchie** [comment]
This will be available in v1.22.0.

If you'd like to use it before the next release, you can download [v1.22.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by mfmayer** [comment]
Thanks 👍 Definitely one of my favorite vscode plugins

**Comment by ModalityZ** [comment]
I'm on a much later version (see below) but there is no dialog for merge options at all when I select Source Control / Branch / "Merge...". I merely get to choose which branch to merge from (via the autocomplete box otherwise used for Ctrl+Shift+p)
```
Version: 1.88.0
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:25:57.039Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-27-generic snap
```
