### ISSUE TITLE
Add an option to do a PR when the user is pushing a branch to remote

### ISSUE THREAD

**Issue by mda-a** [mhutchie/vscode-git-graph#249]
**Describe the feature that you'd like**
When doing a push to a remote, I would like an option to open a page with a PR set up. 

**Additional context (optional)**
SourceTree has something like this, under the commit options dropdown.

**Comment by mhutchie** [comment]
Thanks for raising this feature request, this would definitely be a nice integration to have that streamlines developers workflows!

**Comment by mda-a** [comment]
Hi @mhutchie Can you delete this issue? https://help.github.com/en/github/managing-your-work-on-github/deleting-an-issue

I created this with my work account. I'll create it again from my personal one. Ok?

**Comment by mhutchie** [comment]
Sure, I'll do it right now
