### ISSUE TITLE
Add an option to make a PR after push

### ISSUE THREAD

**Issue by michaeljota** [mhutchie/vscode-git-graph#250]
**Describe the feature that you'd like**
In the push dialog, it would be nice to have an option to create a PR after the push has been made.

**Additional context (optional)**
SourceTree has something like this in the "Commit options" dropdown. 

PS: Thanks.

**Comment by mhutchie** [comment]
Thanks for raising this feature request, it would definitely be nice to have and streamline the development experience using Git Graph!

**Comment by mhutchie** [comment]
This will be available in v1.22.0, which will be released in the next day.

**Comment by michaeljota** [comment]
Thanks man!
