### ISSUE TITLE
Cherry picked from...

### ISSUE THREAD

**Issue by ACheshirov** [mhutchie/vscode-git-graph#251]
First at all, thanks for the extension, again!

**Describe the feature that you'd like**
Could you add a checkbox into the cherry pick panel called for example "Add cherry picked from commit...".
This basically just add -x param to the cherry pick command.

**Additional context (optional)**
https://git-scm.com/docs/git-cherry-pick#Documentation/git-cherry-pick.txt--x

**Comment by mhutchie** [comment]
Thanks for the feedback!

I’ll add this in the next release, along with a new Extension Setting to control the default value of the checkbox. It will be available in the next beta release for you to try out within the next 2-3 days.

**Comment by mhutchie** [comment]
This will be available in v1.22.0.

If you'd like to use it before the next release, you can download [v1.22.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
