### ISSUE TITLE
Add tooltip to "checked out commit" symbol

### ISSUE THREAD

**Issue by felixvd** [mhutchie/vscode-git-graph#259]
It would be helpful for new users if the hollow circle that signifies the currently checked out commit had a tooltip explaining what it represents.

**Comment by mhutchie** [comment]
Thanks for suggesting this, it would definitely be helpful to new users!

**Comment by mhutchie** [comment]
This will be available in v1.22.0.

If you'd like to use it before the next release, you can download [v1.22.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
