### ISSUE TITLE
Make committer identity more apparent

### ISSUE THREAD

**Issue by tecosaur** [mhutchie/vscode-git-graph#26]
I'll cut straight to the chase.

At the moment the 'Author' column doesn't make it easy to see at a glance who did what commit
![image](https://user-images.githubusercontent.com/20903656/54178914-397fab80-44d2-11e9-9001-378c464de203.png)
It not terribly, but I personally can't tell at a glance who's responsible for what.

### Feature Request

It would be nice if use of colour/icons to differentiate authors could be applied so that it's possible to tell at a glance who did what.

Ideas
 - colour picking rotation, add colour as centre of git graph dot
 - colour picking rotation, add colour to author name
 - fetch icons from gravitar/github etc and display those

Otherwise this is very nice and easy to use. Great work so far!

tecosaur.

**Comment by mhutchie** [comment]
Thanks for the suggestion. This is a great idea!

**Comment by meierw** [comment]
Hey there. Found this extension just today and really love it. 
Was thinking the same thing, that user pictures from gravatar/github/gitlab are a must. Similar to how GitKraken implements it by placing the picture in the commit dot ([example](https://blog.axosoft.com/wp-content/uploads/2017/04/gk-tip-pr-info-labels.gif))

Wanted to try my hand at coding this in, but dunno if I should, since Node and TS is quite foreign to me at the moment... 😟

**Comment by mhutchie** [comment]
@meierw Thanks for the feedback & the offer. There are three parts to this feature:

1. Create a function & class that can be called to request an image of the user owning an email address, by calling the gravatar/github/gitlab api's. (Requires knowledge of Node.js or TypeScript)
2. Implement a caching mechanism into the above class for the user pictures. (Requires knowledge of Typescript & VSCode API)
3. Display (and request if needed) user pictures as they are required by Git Graph. (Requires knowledge of Typescript & html+css)

Perhaps you could have a go at the first point if you're interested, as you can work on it in your own files without needing to integrate with the extension, and it also requires the least background in Node.js or Typescript. Once you have it working for one of the api's I can help bring it into the extension.

**Comment by meierw** [comment]
Alright. Will definitely try to build the first part. Can't give you any estimates on it being finished, since I'll have to invest time in learning Node and TS coding quirks.

**Comment by mhutchie** [comment]
@meierw That's awesome, thank you! This issue isn't high on my priority list, so there's no timeline it needs to be completed by. Feel free to send me an email if you have any questions.

**Comment by felipeandres254** [comment]
Hi @mhutchie,
I just found this awesome extension. A must have for me, thank you for that!

Would like to share some of the analysis I was working on weeks ago on your first point:

> Create a function & class that can be called to request an image of the user owning an email address, by calling the gravatar/github/gitlab api's. (Requires knowledge of Node.js or TypeScript)

So, Gravatar uses MD5 hash of the lowercased email to get the image or set a default if the user does not exists or does not have one.
```
https://s.gravatar.com/avatar/{MD5_HASH}?s={SIZE}&d={DEFAULT_STYLE}
```
The URL I most use will be this one, for a 100px image size and a 'Retro' style as defined [here](https://en.gravatar.com/site/implement/images/)

```
https://s.gravatar.com/avatar/bd470681f91662d2cd6cbcc085d94946?s=100&d=retro
```

Looking forward to collaborate in this project,

**Comment by tecosaur** [comment]
@felipeandres254 That's great!

For GitHub, I believe you can get images in the following way [https://github.com/tecosaur.png?size=40](https://github.com/tecosaur.png?size=40)

**Comment by meierw** [comment]
The retrieval method is already built. The code can be found here: https://github.com/mhutchie/vscode-git-graph/compare/master...meierw:feature/commit_avatar

The rest is in the works.

**Comment by mhutchie** [comment]
I've finished off the implementation based on @meierw's great work for integration with GitHub, GitLab & Gravatar. I'll be using & monitoring it this next week to make sure there aren't any issues, as the caching, request queuing & api rate limiting mechanisms have a significant amount of time dependant logic. This feature should be released within 1-2 weeks.

**Comment by mhutchie** [comment]
This will be available in v1.4.5, which I intend to release in the next two days.

If you'd like to use it before the next release, you can download [v1.4.5-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.5-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by tecosaur** [comment]
**Fantastic!** One quick question — does this show icons when there's only one commiter? (such as happens in personal git repos) because in those cases —taking a minimalistic approach— the profile icon is then unnecessary visual clutter.

**Comment by mhutchie** [comment]
Currently it will show avatars when there's only one committer. I think most people would think it was a bug if they have fetch avatars turned on, and no avatars showed (even though it makes sense to hide them).

If others like the idea of hiding avatars if there is only one committer, I think it would be best to add a setting to enable / disable the additional behaviour.
