### ISSUE TITLE
Keep git-graph visible when inspecting files

### ISSUE THREAD

**Issue by felixvd** [mhutchie/vscode-git-graph#260]
I find that one of the least intuitive features when using VSCode source control (and git-graph) is that when you inspect a file for changes, the newly opened tab replaces the entire view, leaving the user disoriented. It is unclear where they have to click to get back, as there is little to no breadcrumbing. I find it very confusing for newcomers overall.

Another reason this is inconvenient is that one cannot click through the changes in a commit without having to close each file after opening it. "Peeking" into a commit is tiresome.

It would be very helpful if the area that was just clicked on did not change, and the requested file opened somewhere else instead.

Is there a way for git-graph to perform "Split Editor Down" (if there is none), and use the newly opened Editor below to open the tab? This might be a good way to keep the git-graph tab and the commit in view while inspecting the file.

**Comment by mhutchie** [comment]
Unfortunately there is no practical / reliable way for any extension to "Split Editor Down" and open the Diff View as you suggested. Extensions can only to open the Diff View in the Active Tab, or Beside the Active Tab. This is already available and controlled by the existing extension setting [Open Diff Tab Location](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#open-diff-tab-location). There are currently no other places that the Diff View can be opened (a limitation of Visual Studio Code itself). Please see [my previous response](https://github.com/mhutchie/vscode-git-graph/issues/206#issuecomment-550472339) explaining this for more details.

The ability to open the Diff View reliably below the Active Tab is an open feature request in Microsoft's vscode repository, so it is on it's way. I'll definitely be making it available in Git Graph once vscode includes it.

I've designed how I will be implementing the existing Git Graph feature request #206, and it will provide the capability of opening a diff view within the Git Graph View itself (not in a separate tab). I plan to implement this soon in one of the next releases. This will definitely address and resolve the inconvenience you mentioned _"one cannot click through the changes in a commit without having to close each file after opening it"_. My final design is more refined, streamlined and user friendly solution than what was initially proposed in #206.

I don't think this feature request is requesting any new functionality that is not already being tracked, so I'll close it.
