### ISSUE TITLE
Regarding 'Capturing Group' in 'Issue Linking' section in 'Repository Settings'

### ISSUE THREAD

**Issue by umairkhan-dev** [mhutchie/vscode-git-graph#262]
**Describe the improvement that you'd like**
Please allow more than 1 capturing group in 'Issue Linking' section of 'Repository Settings'.

**Additional context (optional)**
Our company is using Self-hosted Bitbucket and Jira. Our issue urls in jira are like this.
http://10.0.1.1:8080/projects/PROJ1/issues/PROJ1-16
Where 'PROJ1' is project identifier and 'PROJ1-16' is the issue number.

I wanted to setup 'Issue Linking' globally but due to limitation of 1 capturing group, I can not do so.
Is there a way to use more than 1 capturing group in current version of this extension?
![GitGrapth-Feature](https://user-images.githubusercontent.com/16460954/74832684-a7b32c00-5339-11ea-8034-94c27e95d31b.png)

**Comment by mhutchie** [comment]
Thanks for your feedback on this!

Currently there is only support for a single capturing group, however it would be relatively easy to expand Issue Linking support multiple capturing groups. This would definitely make it much more flexible.

I’ll aim to include this in the next Git Graph release (ETA this weekend). If not, it will be available in a beta release of the follow release (also available this weekend or early next week).

**Comment by mhutchie** [comment]
This will be available in v1.22.0.

If you'd like to use it before the next release, you can download [v1.22.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by umairkhan-dev** [comment]
Sorry, but desperately waiting for release.

**Comment by mhutchie** [comment]
Hi @umairkhan-dev, Apologies for the delay in getting this from a beta release you can use to a full release for everyone. I’ve been quick unwell recently which has limited the amount of time I’ve been able to spend on the extension. It will definitely be released this weekend.

**Comment by umairkhan-dev** [comment]
Hi @mhutchie , Thanks for your reply. Please take your time.
Get Well Soon.
