### ISSUE TITLE
Not showing the correct number of line of code-changes

### ISSUE THREAD

**Issue by sayauYusen** [mhutchie/vscode-git-graph#264]
**Describe the Bug**
Only six lines of code-changes, but gitGraph is showing over six hundred. Please refer to the picture below:

![only_six_lines_changed_but_showing_over_sixHundred](https://user-images.githubusercontent.com/61306184/75013974-4bc6df80-54c0-11ea-97e3-da14f2b6843d.jpg)

**Steps to Reproduce**
Steps to reproduce the behaviour:

{under investigation}

**Environment**
- GitLens Version: 10.2.1 (VS marketplace version)
- VSCode Version: 1.36.0
- OS Version: Windows_NT x64 10.0.17763

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Git Graph runs the following built in git command to determine the number of additions and deletions to each file. It does not transform the values returned by git in any way.

`git diff-tree --numstat -r -m --root --find-renames --diff-filter=AMDR <commit-hash>`

Almost certainly you have made a line-ending change (e.g. from \r\n to \n) which has affected every line in the file. Because the Visual Studio Code Diff View doesn't show line ending changes, it looks like there are only six changes in the Visual Studio Code Diff View.

You can look at the diff of the files in the commit by running the following git command to confirm that more than just the six changes occurred in the file. `git diff <commit-hash>^ <commit-hash>`

I'll close this for now as I'm almost certain what I've described above is the occurring, however please let me know if this is not the case (and the provided git diff-tree command is returning different numbers to what is shown in Git Graph).

**Comment by sayauYusen** [comment]
If git doesn’t show line end changes, then how come it is showing ‘changes’ in here:[cid:image001.png@01D5EAFE.9E81B0F0]

But not in here:
[cid:image002.png@01D5EAFE.9E81B0F0]

Samuel Yau
Senior Analyst Programmer, CL IT Team
Information Technology Division

Yusen Logistics (Hong Kong) Limited
T: +852-2265-9833
E:  samuel.yau@hk.yusen-logistics.com<mailto:samuel.yau@hk.yusen-logistics.com>
W: www.yusen-logistics.com<http://www.yusen-logistics.com>
[cid:image003.jpg@01D5EAFE.9E81B0F0]

**Comment by sayauYusen** [comment]
You are right, my repository member has added two extra blank space in front of lines to make it look like hundreds of ‘meaningful’ changes were made.

But obviously, there is a inconsistency in Git algorithm, if it is not counting the extra space as changes then it might as well stop counting them in the summary.

Samuel Yau
Senior Analyst Programmer, CL IT Team
Information Technology Division

Yusen Logistics (Hong Kong) Limited
T: +852-2265-9833
E:  samuel.yau@hk.yusen-logistics.com<mailto:samuel.yau@hk.yusen-logistics.com>
W: www.yusen-logistics.com<http://www.yusen-logistics.com>
[cid:image001.jpg@01D5EB00.B99AB970]

**Comment by sayauYusen** [comment]
I mean if Git is not counting those meaningless ‘blank spaces’ and ‘end of line characters’ then your product, Git graph, should not count them either. I forgot to mention in my previous email, those over six hundreds lines of meaningless changes are not shown by Git but by Git graph.

Samuel Yau
Senior Analyst Programmer, CL IT Team
Information Technology Division

Yusen Logistics (Hong Kong) Limited
T: +852-2265-9833
E:  samuel.yau@hk.yusen-logistics.com<mailto:samuel.yau@hk.yusen-logistics.com>
W: www.yusen-logistics.com<http://www.yusen-logistics.com>
[cid:image001.jpg@01D5EB01.313E7890]

**Comment by mhutchie** [comment]
Are you saying that your Git installation when running `git diff-tree --numstat -r -m --root --find-renames --diff-filter=AMDR <commit-hash>` reports different numbers to what is show in the Git Graph Commit Details View? Please send me a screenshot of both the Git commands output and the Commit Detail View (for the same commit) if they are not the same numbers.

As I mentioned in my previous reply, Git Graph is just reporting the exact number of additions and deletions that the Git command `git diff-tree --numstat -r -m --root --find-renames --diff-filter=AMDR <commit-hash>` reports. It would be misleading for Git Graph to show any number other than what the Git command reports, as in your situation there actually were that many changes.

I understand that it may be slightly confusing if the number of additions and deletions shown in the Git Graph Commit Details View doesn’t look the same the Visual Studio Code Diff View, however the numbers that Git Graph is showing are the “true” values. The Visual Studio Code Diff View is just making some UX enhancements for what they consider meaningful information.

Unfortunately there is no feasible way for Git Graph to determine if each change in a commit is “meaningful” or not, as even if you personally consider line ending changes meaningless, accidentally making these changes can cause production defects if the code is run on a different platform to what it is developed on (and the line ending is incompatible).

The figures reported by Git Graph is also consistent with many other Git GUI’s, in other words, the approach I’ve taken is not unusual as many other GUI’s agree that the number of additions and deletions shown to summarise a commit should be the full number of actual changes, not the “meaningful number”.
