### ISSUE TITLE
Add Copy Commit Message to Clipboard context menu option

### ISSUE THREAD

**Issue by dguttman-jacada** [mhutchie/vscode-git-graph#267]
**Describe the feature that you'd like**
Currently there is an available feature in the commit context menu to "Copy Commit Hash to Clipboard". I would like to add functionality to also copy commit message to the context menu.

**Additional context (optional)**
In my environment, I have to include an issue URL in every commit. When committing multiple commits for the same issue, it is helpful to copy the commit message from a previous commit. To do so today, one must select the previous commit then use drag & drop to select the commit message to copy.
It would be helpful to just right-click the commit and select "Copy Commit Message to Clipboard"

**Comment by dguttman-jacada** [comment]
please assign to me

**Comment by doronguttman** [comment]
sorry, opened issue with wrong account. please assign to me

**Comment by mhutchie** [comment]
Thanks for suggesting this and raising a pull request! It will definitely be useful for users.

I’m currently working to finish off the features for Git Graph 1.22.0, so I’ll review your pull request after them.

**Comment by mhutchie** [comment]
This will be available in v1.22.0.

Please see my comment on your Pull Request #268 for more details.

If you'd like to use it before the next release, you can download [v1.22.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
