### ISSUE TITLE
Add option for annotated tag

### ISSUE THREAD

**Issue by tecosaur** [mhutchie/vscode-git-graph#27]
Once again, I'll keep this brief and to the point.

It would be nice if there was the option to switch between adding an annotated tag or not within the 'add tag' modal.

**Comment by mhutchie** [comment]
Thanks for the suggestion. This is a great idea!

It would also be nice to be able to view the tag info + message if it is annotated.

**Comment by mhutchie** [comment]
This will be available in 1.4.4, which will be released within the next day.
