### ISSUE TITLE
Use the color from the user's theme

### ISSUE THREAD

**Issue by aloisdg** [mhutchie/vscode-git-graph#273]
Hello,

I would like to have a unify theme in my vscode. It would be nice if Git-Graph could use my theme instead of the default color. I think keeping the default as it is is great. Having the choice to customize the colors would be a nice thing to have.

Example of Bracket Pair Colorizer 2 input:

![image](https://user-images.githubusercontent.com/3449303/75767422-184b4700-5d43-11ea-8f2c-c345aecde95d.png)

Thank you for your work!

**Comment by mhutchie** [comment]
Hi @aloisdg,

You can customise the colours used in Git Graph by using the existing [`git-graph.graphColours`](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#graph-colours) Extension Setting, by providing an array of hex colours just as you are doing for `bracket-pair-colorizer-2.colors`.

It's not feasible for Git Graph to support directly using sets of colours from other extensions (like `bracket-pair-colorizer-2.colors`), as numerous extensions support their own colours (each requiring code in Git Graph to detect), and only a small number of users having the other extensions (with such colour themes) installed. It is also not a recommended pattern for extensions to consume Extension Settings from other extensions.

I'll close this request as I believe the existing `git-graph.graphColours` Extension Setting already provides this functionality. Please let me know if I've misinterpreted your request, so I can re-open it if necessary.

**Comment by aloisdg** [comment]
Exactly what was I looking for. I guess I missed it in the documentation.

Thank you for answering!
