### ISSUE TITLE
Support Git Config Include Directives

### ISSUE THREAD

**Issue by caasi-dev** [mhutchie/vscode-git-graph#281]
**Describe the feature that you'd like**
Git Graph does not seem to be recognising the [includeIf](https://git-scm.com/docs/git-config#_includes) gitconfig property.

For example:
My current `.gitconfig` file is:
```
[user]
	email = main_email_address
	name = user_name
[includeIf "gitdir:/data/dev/WORK/"]
    path = /data/dev/dotfiles/gitconfigwork
[push]
        default = simple
[fetch]
        prune = true
```

`includeIf` checks if the path exists on the disk and loads additional configuration if the path is found. In my case `/data/dev/dotfiles/gitconfigwork` only specifies different email address for my work projects in WORK folder as below:
```
[user]
	email = work_email_address
```

I do appreciate I can update details per project manually from Git Graph settings, but it would be nice if Git Graph could read those settings too

**Comment by mhutchie** [comment]
Thanks for raising this feature request! I wasn’t aware of `includeIf`, so thanks for also providing some background on it.

Git Graph currently uses the commands `git config --list --local` and `git config --list --global` to read the local and global config of a repository. I’ll investigate what changes I need to make so the extension can respect `includeIf`, and implement it in an upcoming release.

**Comment by caasi-dev** [comment]
Thanks a lot, no rush, your extension is already fantastic. This would make it even better for me ;-)

**Comment by caasi-dev** [comment]
I can see that you have started implementing this feature, please ping me in if you need any testers.

**Comment by mhutchie** [comment]
Hi @caasi-dev,

I’ll be publishing a beta release for this functionality in the next few hours, which will include this feature. I’ll reply once it is available.

**Comment by caasi-dev** [comment]
Thank you !

**Comment by mhutchie** [comment]
This will be available in v1.27.0.

If you'd like to use it before the next release, you can download [v1.27.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.27.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by caasi-dev** [comment]
I will be installing fresh system tonight, so this will be a perfect time to test this, thank you.

**Comment by caasi-dev** [comment]
all repositories identified correctly, thank you for implementing this :-)
