### ISSUE TITLE
Momentarily flash the HEAD commit after running CTRL+H

### ISSUE THREAD

**Issue by mhutchie** [mhutchie/vscode-git-graph#283]
**Describe the improvement that you'd like**
Currently the `CTRL+H` keystroke scrolls the Git Graph View to be centered on the HEAD commit. In repositories with many labels it can be hard for the users eye to find exactly which commit is the HEAD.

This improvement involves quickly flashing the HEAD commit with a subtle background colour after the Git Graph View has scrolled to it.

**Additional context (optional)**
The underlying "flashing" behaviour on commits will be common with the new keystrokes for jumping to the next or previous stash.

**Comment by mhutchie** [comment]
This will be available in v1.23.0.

If you'd like to use it before the next release, you can download [v1.23.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.23.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by alok-mishra** [comment]
Is this keystroke configurable?  Currently I have CTRL+H mapped to go to previous tab, and I can't if the Git Graph tab in the middle of several tabs.  Git Graph seems to have precedence. CTRL+L for me is mapped to next tab, and that works fine.
