### ISSUE TITLE
Feature Request: First Parent Only

### ISSUE THREAD

**Issue by rcline** [mhutchie/vscode-git-graph#287]
_Thank you for this amazing tool!_

**Describe the feature that you'd like**

Only one thing I miss from using SourceTree: The option to only show the first parent of the git graph.

`git log --first-parent`
https://git-scm.com/docs/git-log#Documentation/git-log.txt---first-parent
> Follow only the first parent commit upon seeing a merge commit. This option can give a better overview when viewing the evolution of a particular topic branch, because merges into a topic branch tend to be only about adjusting to updated upstream from time to time, and this option allows you to ignore the individual commits brought in to your history by such a merge. Cannot be combined with --bisect.

This can make a very messy commit history, very clean cut and easy to see top level commits.

**Additional context (optional)**

Adding a checkbox to the right or left of "Show Remote Branches" would be perfect:
![Screen Shot 2020-04-01 at 12 39 26 PM](https://user-images.githubusercontent.com/1102747/78174506-9a985b00-7416-11ea-8b1a-a6278e32fc14.png)

Here is what SourceTree looks like:
![Screen Shot 2020-04-01 at 12 40 12 PM](https://user-images.githubusercontent.com/1102747/78174511-9cfab500-7416-11ea-805b-b0edfb8f4ee8.png)

**Comment by mhutchie** [comment]
Thanks for raising this feature request, I wasn’t aware of this option! This would be an extremely useful feature in Git Graph!

The top control bar is already getting quite full (in workspaces with multiple repositories and decent length branch names). I'm saving the remaining space for upcoming filtering functionality.

The pattern I’m using for all new lesser used options is to put them in the General section of the Repository Settings Widget (currently there is “Show Tags” in the published releases, and the new setting “Include commits only mentioned by reflogs” is now available in Git Graph 1.23.0-beta.2 and later). All settings in General section are initially set to the globally configured value from the Git Graph Extension Settings (applies to all repositories), however can then by manually overridden per repository.

I think this setting (All Parents / First Parent) would be best suited for the General section of the Repository Setting Widget (and having a Git Graph Extension Setting to configure the default value).

**Comment by rcline** [comment]
Perfect!  That seems great, it is only one extra mouse click.  I do switch back and forth throughout the day, but not frequently enough to need it front and center (and I am probably in the minority of how often frequently I switch it).

I am also excited that this could teach more people about this lesser know git log feature! 

🙇 😄 🌮

**Comment by mhutchie** [comment]
This will be available in v1.23.0.

If you'd like to use it before the next release, you can download [v1.23.0-beta.4](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.23.0-beta.4), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by rcline** [comment]
Thank you @mhutchie!  I went ahead and tested and it looks great!!
