### ISSUE TITLE
Ability to move branch pointer to different commit without checkout

### ISSUE THREAD

**Issue by samherrmann** [mhutchie/vscode-git-graph#288]
First off, awesome job on this extension @mhutchie! I use it every day and loving it :)

**Description**
 It would be nice if Git Graph provided the ability to move a branch that is not checked-out to another commit. The git command is `git branch -f branch-name new-tip-commit`.

Proposed workflow:
1. Right-click on branch
1. Select `Reset branch...` from context-menu.
1. Select commit that you want to reset the branch to.
1. Pop-up appears asking for confirmation to reset the branch and indicating the selected commit.
1. User can choose to accept or cancel.

I have to admit though that I am not sure how step 3 would be communicated to the user (i.e. how will they know that they need to click on a commit).

**Comment by mhutchie** [comment]
Thanks for the feedback, and raising this feature request with such a clear description, useful details, and proposed workflow!

I’ll have a think about how this would best be accomplished (mainly focussing on your third point).

I think this feature would definitely be useful in certain circumstances, but don’t think this feature would be frequently used by most users. If you’re another user reading this comment in the future, please like the first comment of this thread if you’d value this feature. This enables me to gauge user interest and prioritise it appropriately for delivery.

**Comment by PathogenDavid** [comment]
> If you’re another user reading this comment in the future, please like the first comment of this thread if you’d value this feature.

This is something that I have to do often enough that I'd definitely appreciate it!

**Comment by ntziolis** [comment]
This would indeed a useful feature. In the past I have used smartgit and they have solved this slightly different:
- Right click on any commit
- Choose create branch
- If branch already exists ask to user if branch should still be created

This would achieve the same result while not having to implement a commit picker. What do you guys think?

**Comment by mhutchie** [comment]
Hi @samherrmann, @PathogenDavid & @ntziolis,

In Git Graph 1.29.0 (just released today), I implemented the following feature:
* #390 When creating a branch or adding a tag, the name is now checked against all existing branches and tags in the repository. If a branch / tag already exists with the same name, a new dialog is displayed that allows you to: replace the existing branch / tag, or to choose another name.

#390 uses the `git branch -f branch-name new-tip-commit` command (just like what @samherrmann proposed for this feature), and follows the implementation approach proposed by @ntziolis. Although it's not quite as seamless as the original workflow proposed by @samherrmann, I think it still achieves the same result (while avoiding the complexities that have been previously mentioned).

I'll close this feature request for now, as I think there is now a workable solution available in Git Graph. As this feature has been open for almost 11 months, and there were only four users that indicated they'd use it in that period, I don't think it's worth pursuing a more streamlined solution that would end up being relatively challenging to implement in an intuitive manner. If in the future there is more user interest in the more streamlined workflow, I'll happily re-access it accordingly.

**Comment by PathogenDavid** [comment]
That sounds workable to me, thanks @mhutchie!

**Comment by siarhei-klimuts** [comment]
Use case:
When using git with Godot game engine, and specific branches for CI, for example merge into prod branch triggers a deploy.
In this case I need to close Godot before checkout because it goes crazy when lots of files suddenly changes.
Resetting prod branch without checkout is more comfortable because there will be no need to close the game engine.

Probably other game engines struggle with it too, don't know.
