### ISSUE TITLE
Ability to compare branches (actually, commits)

### ISSUE THREAD

**Issue by yzhang-gh** [mhutchie/vscode-git-graph#29]
Thank you so much for this awesome extension. I used to use the [Git History](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory) extension but immediately switched to yours since I found it (and left the first 5 ⭐ review of your extension 😎).

**Describe the feature that you'd like**

Select a commit for comparison, then select another commit to compare

**Additional context (optional)**

![demo](https://raw.githubusercontent.com/DonJayamanne/gitHistoryVSCode/master/images/compare.gif)

(This is just an example of what Git History does. I don't think it is a good idea to show the comparison in the file explorer)

**Comment by mhutchie** [comment]
Thanks for the feedback! This suggestion seems quiet useful, I’ve also used this type of commit comparison in the past.

I just need to think about how it would be best to display this information. I agree that it shouldn’t be in the file explorer, so I just need to find a nice way of showing it in the existing interface.

**Comment by kmasuyama** [comment]
To piggyback on this feature request, it'd be awesome to also be able to compare commits from the past against the current uncommitted state. Thanks for a great extension!

**Comment by krupenja** [comment]
Agreed, ability to compare a commit with working tree would be amazing!

**Comment by mhutchie** [comment]
The ability to compare two commits will be available in v1.5.0, and will be released in the next day. I've reopened #36 (which requested broader support for uncommitted changes), so I'll extend the commit comparison to support the working tree as part of that feature request in the next release (in the next week).

**Comment by yzhang-gh** [comment]
It seems like the order of selecting the commits doesn't change the order of comparison (from commit A to commit B). Is it by design?

**Comment by mhutchie** [comment]
Yes, the order of selecting commits doesn’t change the order of comparison. It will always show changes from the oldest commit to the newest commit.

**Comment by mhutchie** [comment]
I've now completed the ability to compare any commit with the uncommitted changes as part of #36. This will be available in v1.6.0. I have implemented:
- View uncommitted changes
- Comparing any commit with the uncommitted changes
- Three new Git actions from the new Uncommitted Changes context menu:
    - Reset uncommitted changes to HEAD
    - Clean untracked files
    - Open the Visual Studio Code Source Control View

If you'd like to use it before the next release, you can download [v1.6.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by yzhang-gh** [comment]
Thanks for the reply. Any consideration for this oldest-newest order?

A disadvantage is, we cannot select/copy the deleted text from _the old version_ in the vscode diff view. microsoft/vscode#8226

**Comment by mhutchie** [comment]
I thought the oldest-newest order made sense as:
- The old version of the file is always on the left, and the new version of the file is always on the right of the diff view, for consistency.
- I felt it would be confusing to have the newest version of the file on the left.
- The diff should be clearly interpretable from the Diff view alone, so the only way to allow the reversed ordering would be to change the tab title. I didn't pursue this at the time as I couldn't come up with a consistent pattern for a new tab naming scheme allowing the ordering to be easily differentiated (especially with the new beta support for uncommitted changes).
- This is consistent with the built in usage in the VS Code SCM view when viewing staged/unstaged files.

@yzhang-gh I wasn't aware of this limitation with the VS Code Diff View, which is quite unfortunate.

For now I'm inclined to leave it as is, however I'll have a think if there is anything else I could do to work around this limitation.

**Comment by yzhang-gh** [comment]
I agree with you on most of the points.

Just to add another point. When we are comparing two commits from different branches, it is hard to say which one is "older" 😥

**Comment by yeggles** [comment]
If you want the UI to work the same as other tools that I have used (TortoiseGit & GitExtensions) then the order of the clicks would matter.  For those applications, the diff is displayed as how the 2nd click differs from the 1st clicked commit.

**Comment by Keavon** [comment]
> To compare two commits, click on one of the commits (to open the Commit Details View), and then CTRL / CMD click any other commit to compare it with.

I just want to comment about the fact that this feature was very undiscoverable. I'm so happy to finally have discovered this! I would have never guessed that I need to <kbd>Ctrl</kbd><kbd>Click</kbd> between the two commits, although that's super useful now. This has been the one feature I've been needing for months. @mhutchie is there a way you could integrate this into the UI in some way to make it discoverable? One UX suggestion: add a compare button with an icon like ⇄ to the right of the commit message of each commit you hover over while an existing commit is expanded (clicking that icon button would be equivalent to Control-clicking the second commit, and its tooltip could explain the order of which comes first and last and explain the <kbd>Ctrl</kbd> shortcut.)

**Comment by wenbert** [comment]
Is there a way to compare more than 2 commits?

For example:
```
Commit E
Commit D
Commit C
Commit B
Commit A
```

I would like to be able to select `Commit B` up to `Commit E`. And see files changed across those commits.

**Comment by yeggles** [comment]
> Is there a way to compare more than 2 commits?
> 
> For example:
> 
> ```
> Commit E
> Commit D
> Commit C
> Commit B
> Commit A
> ```
> 
> I would like to be able to select `Commit B` up to `Commit E`. And see files changed across those commits.

If you hold the Ctrl key and click the first commit that you care about (so in your example you would click Commit A) and then click the last commit that you care about (Commit E).  It should provide a diff window that encapsulates all of the files that had changed across all of the commits between A and E.

**Comment by wenbert** [comment]
> > Is there a way to compare more than 2 commits?
> > For example:
> > ```
> > Commit E
> > Commit D
> > Commit C
> > Commit B
> > Commit A
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would like to be able to select `Commit B` up to `Commit E`. And see files changed across those commits.
> 
> If you hold the Ctrl key and click the first commit that you care about (so in your example you would click Commit A) and then click the last commit that you care about (Commit E). It should provide a diff window that encapsulates all of the files that had changed across all of the commits between A and E.

Cool thanks that works.
What about selecting something not in a series / linear way? For example, `Commit A` `Commit C` and `Commit E`? (Skipping B and D for example)
A usecase is something like PHPStorm I have different branches and then want to compare them across different ones to create a totally different branch.

**Comment by yeggles** [comment]
I know you can compare commits that are on different branches, but I am not 100% sure if you can select more than 2 commits to do a diff.  I'm currently not working with VSCode at my current job or else I would have tested it for you.  Good luck.  Feel free to ask any additional question that you might have.

**Comment by yeggles** [comment]
> > > Is there a way to compare more than 2 commits?
> > > For example:
> > > ```
> > > Commit E
> > > Commit D
> > > Commit C
> > > Commit B
> > > Commit A
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I would like to be able to select `Commit B` up to `Commit E`. And see files changed across those commits.
> > 
> > 
> > If you hold the Ctrl key and click the first commit that you care about (so in your example you would click Commit A) and then click the last commit that you care about (Commit E). It should provide a diff window that encapsulates all of the files that had changed across all of the commits between A and E.
> 
> Cool thanks that works. What about selecting something not in a series / linear way? For example, `Commit A` `Commit C` and `Commit E`? (Skipping B and D for example) A usecase is something like PHPStorm I have different branches and then want to compare them across different ones to create a totally different branch.

I know you can compare commits that are on different branches, but I am not 100% sure if you can select more than 2 commits to do a diff. I'm currently not working with VSCode at my current job or else I would have tested it for you. Good luck. Feel free to ask any additional question that you might have.

**Comment by MarkJeronimus** [comment]
> To compare two commits, click on one of the commits (to open the Commit Details View), and then CTRL / CMD click any other commit to compare it with.

And then...?
When I do this the two commits are just *selected* like you could select two files in an explorer. I can't find any new buttons or context menu items related to comparing. I'm using version 1.30

**Comment by boan-jfm** [comment]
> To compare two commits, click on one of the commits (to open the Commit Details View), and then CTRL / CMD click any other commit to compare it with.

Nice, I looked and looked for this feature, and could not find it. It would be nice if it could be part of the context menu if you right click on anther commit, and choose compare. 

Right now it is hard to find this feature.

Thanks.
