### ISSUE TITLE
Command `git-graph.view` not found

### ISSUE THREAD

**Issue by andywampir** [mhutchie/vscode-git-graph#291]
**Describe the Bug**
When i try to open the git graph window, i'm getting error: `Command 'git-graph.view' not found`.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Source Control on the panel'
2. Click on 'View Git Graph (git log)'
3. See error

**Expected Behaviour**
Show git graph

**Environment**
 - Git Graph Extension Version: 1.22.0
 - Visual Studio Code Version: 1.44.0
 - Operating System: Windows 10

**Screenshots (optional)**
![git-graph-issue-image](https://user-images.githubusercontent.com/24408703/79075778-3fb40d00-7d0e-11ea-936e-d302d9fd5c90.png)

**Comment by mhutchie** [comment]
When you receive this error, could you please include:
* Any records related to Git Graph from the “Log (Extension Host)” Output Channel. (this could indicate the extension failed to start and/or register the command).
* The contents of the Git Graph Output Channel if it is available (this will indicate the state of the extension).

As you’re the only person to report this issue out of over 200,000 active users, this appears to be an isolated incident. I also can’t replicate it under any environment (including the exact environment you’re using). Are you getting this error consistently or did it occur one-off?

Do any Git Graph commands exist in the Visual Studio Code Command Palette when this error occurs?

**Comment by andywampir** [comment]
I looked in `Log (Extension Host)` output channel and seen that module `../.vscode/extensions/mhutchie.git-graph-1.22.0/out/extensions.js` was not found, then a looked at directory `out` and realized that this directory doesn't have any `.js` files.
So i just deleted extension from `Extensions` panel in `vscode` and removed `mhutchie.git-graph-1.22.0` directory, then i just reinstall extensions and it's work now.

Thank's for quick answer on this issue.

**Comment by mhutchie** [comment]
Thanks for the update, and I’m glad the extension is working for you now after reinstalling it!

**Comment by bjornarhagen** [comment]
I had the same problem with v1.30.0. Uninstalling and reinstalling did not work. I had to delete the folder to fix it

**Comment by devsangwoo** [comment]
If you use this command to delete it, it's fast.

```
$ rm -rf ~/.vscode/extensions/mhutchie.git-graph-1.30.0

```

**Comment by goldengel** [comment]
I had same problem and thank you for the solution. The comment like "you are the only one with this problem" is wrong. Just not easy to report. Solved by:
https://github.com/mhutchie/vscode-git-graph/issues/291#issuecomment-612799755
My version: 1.30.0
