### ISSUE TITLE
"Open a Terminal for this Repository" Button

### ISSUE THREAD

**Issue by SirIntruder** [mhutchie/vscode-git-graph#293]
If I am inspecting a submodule in git graph, I would love to have ability to open terminal in the root of the current repository, so "git ..." calls would apply to the selected repositroy. Vscode standard command would open terminal at root of the workspace, which is not what I expect in this context.

Simplest solution would be to have a small terminal button in the right-up corner, that would function like "open terminal at path {repo}". If that seems like a waste of real estate, context menu action somewhere on the top bar would also be fine.

**Comment by mhutchie** [comment]
Thanks for raising this feature request, I definitely think this functionality would be nice to have in Git Graph!

**Comment by mhutchie** [comment]
This will be available in v1.25.0.

If you'd like to use it before the next release, you can download [v1.25.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.25.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
