### ISSUE TITLE
Set default - not changing colors for branches

### ISSUE THREAD

**Issue by rneveri** [mhutchie/vscode-git-graph#295]
First of all thanks a lot for this extension. Really appreciate it. Helped me to finally let sourcetree go :)

**Describe the improvement that you'd like**
While merging some branches in Git Graph, I keep noticing, that the branch colors change. 

It's not a huge issue, but when I get used to the master being green and dev being blue it's easier to see the flow. Then when the branch colors change again, I have to get used to it again etc...

I would like to suggest the ability to set certain colors for certain branches. It could improve workflow, to have the main branches, that never get deleted have the same color. So that when I look at the graph, I can see the master & dev branch immediately.

Thanks!

**Comment by mhutchie** [comment]
Thanks for the feedback!

This behaviour of the branches changing colour will automatically be improved and resolved as a side effect of how I plan to implement #207. I intend this behaviour to be available in one of the next releases of Git Graph.

I’ll close this improvement request as it’s core functionality is already planned to be implemented and tracked under a separate issue.

**Comment by rneveri** [comment]
Thanks for the swift feedback! Great news :) Looking forward to the new version.
