### ISSUE TITLE
Set `retainContextWhenHidden` to `true` (or add an option for it)

### ISSUE THREAD

**Issue by yzhang-gh** [mhutchie/vscode-git-graph#30]
**Describe the feature that you'd like**

I really like the git log view because it looks neat. I am happy to give the webview more computing resources to avoid the flash when switching back from other tabs.

**Additional context (optional)**

https://code.visualstudio.com/api/extension-guides/webview#retaincontextwhenhidden

**Comment by mhutchie** [comment]
Thanks for suggestion!

When I first set up the Webview I didn’t know about retainContextWhenHidden, but I came across it last week and have been meaning to try it out. I’m curious to see what the experience is like and how much it impacts system resources. Depending on these results I’m definitely wanting to either: enable it all the time, provide the option to do so, or improve the existing experience when switching back to the Git Graph tab.

**Comment by mhutchie** [comment]
Thanks for making these changes and contributing to the Git Graph extension!

I'll finish off a few other feature requests in the next day, and then I'll create a beta release including this one. I'll reply here to let you know once it is available for you to download.

**Comment by mhutchie** [comment]
This will be available in v1.6.0.

If you'd like to use it before the next release, you can download [v1.6.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
