### ISSUE TITLE
Add scroll bar support to dropdown menus on dialogs

### ISSUE THREAD

**Issue by davidhasegawa-bc** [mhutchie/vscode-git-graph#303]
**Describe the Bug**
In Step 2/2 of 'Configure "Pull Request Creation" Integration', the Destination Branch dropdown does not have a scroll bar, so it extends to the edge of the VSCode window if you have too many branches in your repo.  This makes it impossible to select the branch I'd like if its name isn't at the very top.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Set up Git Graph as usual, on a remote repo with many branches (more than 20 on my particular monitor and VSCode zoom level).  Can be reproduced with fewer branches if you zoom VSCode (Ctrl + +).
1. Click the gear icon for Repository Settings.
1. Click the 'Configure "Pull Request Creation" Integration' button.
1. Click Next to get to Step 2.
1. Open the Destination Branch dropdown.
1. Observe it extending to the edge of the VSCode window, stopping at the status bar.  It cannot be scrolled.

**Expected Behaviour**
This dropdown has a scroll bar, allowing me to see all the branches.  Additionally (as a bonus feature), it would allow me to type the first characters of the branch name, to allow me to quickly skip to the desired branch.

**Environment**
 - Git Graph Extension Version: 1.22.0
 - Visual Studio Code Version: 1.44.2
 - Operating System: Ubuntu 16.04

**Comment by mhutchie** [comment]
Thanks for spotting this! I'll have a fix for this available soon.

FYI: In the meantime, once the dropdown is focussed you can use the up/down arrows to navigate through and select the desired branch.

**Comment by mhutchie** [comment]
This will be available in v1.23.0.

If you'd like to use it before the next release, you can download [v1.23.0-beta.5](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.23.0-beta.5), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
