### ISSUE TITLE
Change commit-ordering from the Git Graph View

### ISSUE THREAD

**Issue by phgmacedo** [mhutchie/vscode-git-graph#304]
**Describe the feature that you'd like**
Add the ability to change commit-ordering by clicking the date or author column, and also a command and maybe a keyboard shortcut to do it. 

**Additional context (optional)**
Currently, it requires going into to the extension configuration, and changing an option every time you need to sort differently.

**Comment by mhutchie** [comment]
Thanks for raising this feature request, I agree that it would be nice to change this setting from the Git Graph View directly.

I think this functionality is best suited to be added to the existing right click menu on the column headers. This would be consistent with the pattern I use for Git Graph Extension & Repository Settings, and table layouts in many other software products.

**Comment by mhutchie** [comment]
This will be available in v1.24.0.

If you'd like to use it before the next release, you can download [v1.24.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.24.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by mhutchie** [comment]
Hi @b3nab,

I investigated supporting the `--reverse` option, however I quickly discovered that there were numerous technical and user experience reasons why it was best not to support it. There also isn’t any work-arounds.

This was also requested in #133, which was closed due to the above reasons, coupled with the lack of user interest in it.

**Comment by i11010520** [comment]
It'll be very convenient if  there's `--reverse` option supported.
Looking forward to this feature.

Thanks for your great work, @mhutchie !
