### ISSUE TITLE
Stash does not remove files from index

### ISSUE THREAD

**Issue by oligu** [mhutchie/vscode-git-graph#309]
**Describe the Bug**
Uncommitted files are not removed from index when stashing.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Have some local uncommitted changes.
2. Right-click on the `Uncommitted Changes` line
3. Select `Stash uncommitted changes ...`
4. In the popup optionally enter a name and click `Ok`
5. The stash gets created with the changed files, but the files are still present as `Uncommitted changes`

**Expected Behaviour**
The files only exist in the stash.

**Environment**
 - Git Graph Extension Version: 1.23.0
 - Visual Studio Code Version: 1.45.1
 - Operating System: Windows 10

**Screenshots (optional)**
Add any screenshots showing the bug.
![image](https://user-images.githubusercontent.com/3225652/83021656-9e1d1c80-a02a-11ea-83cc-c7762cf70778.png)

**Additional Context (optional)**
Tested with 1.22.0 and there it works as expected.

**Comment by mhutchie** [comment]
Hi @oligu,

I've followed the steps you've provided on all individual and combinations of stashing uncommitted changes that are (untracked, changed but not staged & staged), and every time Git Graph behaved exactly you expect (not what you indicate is occurring in Step 5). I've also tested this behaviour on both your platform (with exactly the same versions), and independently on a Mac - neither reproduced the behaviour you're describing.

There was absolutely no change in Git Graph 1.23.0 that affected any of the code used to perform the "Stash uncommitted changes..." action, so I see no reason why Git Graph 1.23.0 is behaving any differently from Git Graph 1.22.0 for you (which you state is working correctly).

Also, Git Graph 1.23.0 has been released for 4.5 days now, and out of the hundreds of thousands of Git Graph users I'd definitely have expected this to have been reported by many other users (far earlier than now), if it were actually a problem with Git Graph.

I'll close this issue for now as: I see no reason why this should be occurring, I can't replicate it using the steps you've provided (that appear to be thorough enough that I couldn't misinterpret them), and it hasn't been reported by any other users. If another user reports the same erroneous behaviour you're observing, I'll definitely re-open this issue and fix it immediately once replicated (as I definitely want to fix it ASAP if it is a bug).

**Comment by oligu** [comment]
Hello @mhutchie

Thanks for your thorough reply.

With an up-to-date setup (VSCode 1.46.1, Gitgraph 1.24.0) stashing works as expected. And also by switching back to Gitgraph 1.23.0 I cannot reproduce the error. As I was using another Git Client for stashing in the meantime, I cannot say when the behavior went back to normal. I suspect the issue might more have been related to git or the fact that I was working on a network drive over a bad network connection, or a combination of all of the above.

As everything works as expected, this issue can stay closed. I'll let you know if it should reappear.
