### ISSUE TITLE
Sticky branch selection bar / table head columns?

### ISSUE THREAD

**Issue by niccolomineo** [mhutchie/vscode-git-graph#310]
Hi, thank you for your awesome extension. I am wondering whether you could add an option to make the branch selection bar / table head columns (see screenshot below) fixed on scroll.

<img width="1130" alt="Schermata 2020-05-27 alle 22 04 29" src="https://user-images.githubusercontent.com/5409469/83067092-5ddb8f80-a066-11ea-8557-9a79bc8ca9f0.png">

Thank you.

**Comment by mhutchie** [comment]
Hi @niccolomineo, thanks for the feedback!

This is already being tracked by the existing feature request #132.

I'll close this feature request as it is a duplicate.
