### ISSUE TITLE
Launching command in the same terminal window

### ISSUE THREAD

**Issue by niccolomineo** [mhutchie/vscode-git-graph#311]
I don't know for sure if this happens with every command, but it probably does (although I can only speak for interactive rebases): do you think it could be possible to add an option to force issuing the command in the same terminal window?

Thank you.

**Comment by mhutchie** [comment]
Hi @niccolomineo,

The [Visual Studio Code Terminal](https://code.visualstudio.com/api/references/vscode-api#Terminal) integration with extensions has some limitations that effectively force Git Graph to always create a new Terminal window when running an interactive rebase. _(The interactive rebase action is the only action in Git Graph that uses a Visual Studio Code Terminal for that matter.)_

Extensions can get a reference to the active terminal, or a new terminal that the extension requests to be created. With this reference, the extension can send text to it (under-the-hood it sends the text to stdin). For example, Git Graph requests a new terminal to be created, and then sends the git rebase command to it.

However, the Visual Studio Code Terminal does not provide a mechanism to observe the state of the terminal / command being executed in it. This means that if Git Graph reused an existing terminal, there is no guarantee that the user is not in the middle of running another command, it simply just writes the text when invoked. This has the undesirable consequences that:
1. It could inadvertently affect the execution of an executing command.
2. It would prevent the git rebase from being run.

For these reasons the current behaviour was chosen, as it guarantees that no prior command is being executed, by creating a fresh terminal instance to run in.

Additionally, if the extension was to reuse the active terminal, there is no guarantee that git is in the path environment variable exposed to commands run in it. When creating a new terminal, Git Graph is able to add the users git executable to the new terminals path variable if it isn't already included. _(A surprisingly large number of users don't have git in their path)_

For the above reasons I'm closing this improvement request for now, as the current behaviour is practically forced by Visual Studio Code. If in the future Visual Studio Code expanded their terminal integration for extensions to enable the experience you describe, I'd be happy to re-open this request and implement it.
