### ISSUE TITLE
Web Browser Visual Studio Code: Prevent default event bubbling on right-click

### ISSUE THREAD

**Issue by francislavoie** [mhutchie/vscode-git-graph#312]
**Describe the Bug**
I'm using the Git Graph plugin with [Coder](https://github.com/cdr/code-server) i.e. a VSCode server, running it in a browser window. Specifically using it in Firefox.

When in the graph view, when I right-click on a commit to take some action, the browser context menu appears as well as the Git Graph one. Git Graph should handle the onContextMenu event and prevent it to avoid the overlap of the browser's on top of Git Graph's.

**Steps to Reproduce**
1. Install Coder https://github.com/cdr/code-server
2. Run it in a browser
3. Install Git Graph + reload
4. Open the Git Graph log view
5. Right-click a commit, see both context menus open

**Expected Behaviour**
I should not see both context menus appear, only Git Graphs.

I'm pretty certain browsers override onContextMenu if shift is held, so this would just make for better UX I think.

**Environment**
 - Git Graph Extension Version: 1.23.0
 - Visual Studio Code Version: 1.45.1, code-server v3.3.1
 - Operating System: Coder running on Ubuntu 20.04

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/2111701/83151137-2e5e6e80-a0ca-11ea-8ac9-c1c735bbfc9f.png)

**Additional Context (optional)**
N/A

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @francislavoie,

Git Graph is currently only supported in Visual Studio Code itself, not from the variety of web browser based Visual Studio Code environments. There are actually quite a variety of changes required to make Git Graph be fully supported in web browsers (not just this right-click menu issue).

I’m pleased to let you know though that the next release of Git Graph 1.24.0 will officially support being run in web browsers (and I aim to have a beta release available with this functionality within the next week). I’ll let you know when this is available so you can start using it ASAP.

This capability has been in the pipeline for the last three months, so I’m looking forward to finally getting this released soon. The delivery of this capability is being tracking in #307, however initial discussions where made in #271 & #294.

I’m closing this issue, as the broader implementation of Visual Studio Code support in web browsers (which this is a part of) is being tracked in the feature requests above.

**Comment by francislavoie** [comment]
Ooh, sweet! Thanks 😁
