### ISSUE TITLE
New setting: Show Selected Branches By Default

### ISSUE THREAD

**Issue by Kenobi-the-2nd** [mhutchie/vscode-git-graph#318]
Good morning,

I am still very much enjoying this extension. It has made using git within VS Code much easier and intuitive, without interrupting my workflow.

There is currently a setting in Git Graph called "Show Current Branch By Default", which allows a user to show the currently checked out branch in the graph by default. Could a new (but similar) setting be added that allows showing certain selected branches by default? 

For example, I typically want to see the local master branch and the origin/master branch along with my current branch so that I can easily see that my pulls, merges, and pushes have gone through successfully. However, every time I open the graph, I must select these two master branches again so that they will display. Having the option to have these shown by default would be very convenient. 

Again, thanks for a great extension, and thank-you for your time.

**Comment by mhutchie** [comment]
Thanks for raising this feature request, I definitely think it would be really useful!

I’ll include this in one of the upcoming Git Graph releases.

**Comment by mhutchie** [comment]
This will be available in Git Graph 1.26.0, which I'm aiming to have released within the next day.

**Comment by mhutchie** [comment]
Unfortunately I was only just unable to finish my formal review of Git Graph 1.26.0 on the weekend, so I had to postpone the release until this coming weekend.

If you'd like to use it before the next release, you can download [v1.26.0-beta.5](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.26.0-beta.5), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by Kenobi-the-2nd** [comment]
That's no problem at all! Thank-you again for adding the feature--definitely an improvement, and it will make my Git workflow that much smoother. Again, it is much appreciated sir.
