### ISSUE TITLE
Add checkout to context menu?

### ISSUE THREAD

**Issue by borekb** [mhutchie/vscode-git-graph#32]
Similarly to #2, I'd often appreciate a `git checkout` functionality in the context menu.

BTW, I use Git Graph more and more, the UI is so pleasant to use! Great job!

**Comment by mhutchie** [comment]
Thank you for the feedback!

Branches can already be checked out by right clicking on local or remote branch labels. Are you refering to checking out a specific commit instead of a branches?

**Comment by borekb** [comment]
Yes, to time-travel along the Git graph when I need to locate a bug or find out something. In that case, I usually jump between merges to master to find out which PR introduced the problem.

**Comment by mhutchie** [comment]
I hadn't thought about this use case, adding `Checkout this Commit` to the commit context menu definitely sounds really useful.

**Comment by mhutchie** [comment]
This is now completed, and will be available in 1.4.3.
