### ISSUE TITLE
Call to api.mhutchie.com

### ISSUE THREAD

**Issue by rolandleth** [mhutchie/vscode-git-graph#320]
Hey, Michael,

Was wondering what's up with this call:
<img width="568" alt="Screenshot 2020-06-15 at 12 08 10" src="https://user-images.githubusercontent.com/1858700/84639411-0318b380-af01-11ea-8b57-bbfe7d5f1da9.png">

Thanks!

**Comment by mhutchie** [comment]
Hi Roland,

The Git Graph extension uses this API for the following purpose:

---

The Git Graph extension generates an event when it is installed, updated, or uninstalled. Each event contains the following fields (and nothing else):
* extension: The Git Graph extension version (e.g. 1.22.0)
* vscode: The Visual Studio Code version (e.g. 1.43.2)
* nonce: A 256 bit cryptographically strong pseudo-random number generated and base64 encoded by the extension when each event is created. It is used to prevent duplicates of an event being stored when network disruptions prevent a successful API request.

The Git Graph and Visual Studio Code version numbers recorded in these events only allow aggregate compatibility information (e.g. 50% of users are using Visual Studio Code >= 1.41.0) to be generated. These insights enable Git Graph to utilise the latest features of Visual Studio Code as soon as the majority of users are using a compatible version. The data cannot, and will not, be used for any other purpose.

As only these two version numbers (and a random nonce) are recorded, it enforces that:
* The process is COMPLETELY ANONYMOUS, as there is no identifiable data involved at any stage.
* The process can only produce aggregate compatibility insights.
* There is NO WAY to correlate any two events with each other (e.g. belonging to the same machine or user).

Additionally:
* All API requests are sent using HTTPS.
* No other parameters of the request itself (e.g. Sender IP Address, User Agent, etc.) are recorded. This ensures the data sent in the event stays anonymous, unidentifiable, non-personal, and cannot be correlated.
* There is no access logging to the API, to ensure no request data is ever recorded.
* Error logging is limited to string literals that identify a system error or failure. No variables or data is included in the error logs.

---

This information is available at `https://api.mhutchie.com/vscode-git-graph/about`. This link is included in each request that is sent to the API.

**Comment by rolandleth** [comment]
Thank you for the detailed explanation!
