### ISSUE TITLE
Add "Merge into current branch..." to the remote branch context menu

### ISSUE THREAD

**Issue by firattaskin** [mhutchie/vscode-git-graph#322]
in sourceTree i can merge my master branch with any branch. But in GitGraph when i right click to any branch_name i cant see "Merge into Current Branch..." option if i didnt checkout remote branch.

**Comment by mhutchie** [comment]
Hi @firattaskin,

Currently the "Merge into Current Branch..." action is only available on the local branch context menu.

Is this feature request to add the "Merge into Current Branch..." action onto the remote branch context menu? This would all you to merge a remote branch into the current branch without first checking it out.

**Comment by firattaskin** [comment]
Yes i want this. I need merge option for remote branches. Checkout can be time waste in crowded projects. Our Company loves you

**Comment by mhutchie** [comment]
This will be available in v1.25.0.

If you'd like to use it before the next release, you can download [v1.25.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.25.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
