### ISSUE TITLE
Git Grgaph currently not avialble on the market place

### ISSUE THREAD

**Issue by jean-raphael** [mhutchie/vscode-git-graph#325]
can't find git graph on the marketplace

i want to show it to a friend and he can install it because of it

codium -v
1.46.0
a5d1cc28bb5da32ec67e86cc50f84c67cc690321
x64

**Comment by mhutchie** [comment]
I publish Git Graph to the Visual Studio Marketplace (the extensions page is available [here](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph#overview)). The extension has a minimum version requirement of Visual Studio Code >= 1.38.0.

I can see it in Visual Studio Code "Extensions: Marketplace" Panel when searching "Git Graph".

I'm unfamiliar with codium, does it / are you using to a different marketplace? It looks like they use a separate marketplace (documented [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace)), which I have never published the extension too. Have you seen it there before?

I'm closing this as the extension is definitely still available in the Visual Studio Marketplace, which is the only place I currently publish it. I'll keep this thread unlocked so we can continue the discussion starting with the above questions I've asked.

**Comment by jean-raphael** [comment]
Yes it strange i have git graph installed on my codium but i can't find it on the market place

**Comment by mhutchie** [comment]
@jean-raphael,

Would you please confirm which marketplace you’re using?

Which version of Git Graph do you have installed?

It looks like in codium you can specify the marketplace you’re using (either the Microsoft Visual Studio Marketplace or the Open VSIX Registry) in a product.json file (see the documentation I linked in my previous response).

**Comment by bobmorane06** [comment]
I'm trying to install git graph in codium too and not finding it in the marketplace. The origin of my switch to codium is that git graph isn't working anymore on vscode insiders (which I was using because codium doesn't have the SSH extension, which I don't need anymore now that I've moved from a VM to WSL2)
