### ISSUE TITLE
Support for git repositories in subfolders

### ISSUE THREAD

**Issue by asierralozano** [mhutchie/vscode-git-graph#33]
Referencing this comment in here:https://github.com/mhutchie/vscode-git-graph/issues/13#issuecomment-473215648

It would be nice if the extension supports sub-folders with git repos in them. Something like the following structure:

Folder1 (is not a git repo)
-- library1 (is a git repo)
-- library2 (is a git repo)
-- .. (some more git repos)

Folder2 (is not a git repo)
-- library1 (is a git repo)
-- library2 (is a git repo)
...

Thanks mate!

**Comment by mhutchie** [comment]
Thanks for the suggestion! This would be great functionality to support.

**Comment by asierralozano** [comment]
Hello! I was thinking about this feature request. 
I think that it would be a better approach if clicking on the Git Graph button opened the repo of the file that it is currectly active, except of detecting every repo in each subfolder.

What do you think?

Thanks!

**Comment by mhutchie** [comment]
Great work! I think this is a great idea for determining what repo should be initially loaded when opening the Git Graph view. However, `getRepos` does also need to include all the repos to show in the repo dropdown for the user can switch between any available repo. I have something in mind for the second part, so I think a combination what you already have & what I have in mind should make repo loading & switching much better.

**Comment by dawid-s** [comment]
Just wanted to say that it would be a very welcome feature indeed. Otherwise great extension so thanks for that :) :+1:

**Comment by mhutchie** [comment]
This will be available in v1.4.6. There is a new setting `git-graph.maxDepthOfRepoSearch` that specifies the maximum depth of subfolders to search (default: 0). For example, you will need to set `git-graph.maxDepthOfRepoSearch` to at least 1 for the workspace:

Folder1 (is not a git repo)
-- library3 (is a git repo)
-- library4 (is a git repo)
-- .. (some more git repos)

Folder2 (is not a git repo)
-- library5 (is a git repo)
-- library6 (is a git repo)

If you'd like to use it before the next release, you can download [v1.4.6-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.6-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by asierralozano** [comment]
Hello!
I'm so sorry, I was offline for holidays!
Thanks for adding this feature! it works like a charm!

**Comment by dawid-s** [comment]
Yep, I can confirm it works as expected. Thank you @mhutchie.

**Comment by jsohndata** [comment]
Thank you
