### ISSUE TITLE
Printout of the graph

### ISSUE THREAD

**Issue by raphboll** [mhutchie/vscode-git-graph#338]
Would it be possible to generated a printout of the complete graph. Like a screenshot would do but for the complete graph not just the part that is visible.

**Comment by mhutchie** [comment]
Hi @raphboll, Thanks for raising this feature request!

This capability is not one that Visual Studio Code provides to extensions, so it is something that I would have to implement in Git Graph itself. After looking at a variety of JavaScript packages online, I couldn't find one that would meet the requirements that I believe this feature would reasonably present, and would accurately deal with the complex graph rendering performed in the Git Graph View. It is also far to complex and time consuming for me to create a custom implementation specifically for Git Graph.

Even if a package did exist, based on what I can see of existing packages they would likely double to quadruple the packaged size of the extension. Although I don't mind doing this, I would only do so if this functionality would regularly be used by a decent number of users.

I'll close the issue for now and add it to the backlog, as primarily I'm unable to find a suitable package that would make this feature feasible, and secondly I don't think enough users would regularly use it for it to be prioritised among most of the open feature requests.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and add this feature if a decent number of users would like it, and a suitable JavaScript package exists (that someone can let me know about).

**Comment by raphboll** [comment]
Thank you very much for looking into this. I understand your reasons to close this.
