### ISSUE TITLE
Add ability to do rebase on a commit or branch

### ISSUE THREAD

**Issue by morganlombard** [mhutchie/vscode-git-graph#34]
**Describe the feature that you'd like**
From the context menu when right-clicking on a **commit**, add the option to rebase on the commit.
From the context menu when right-clicking on a **branch**, add the option to rebase on the branch.
For both commit/branch rebase, ask if rebase should happen **interactively**.

**Comment by mhutchie** [comment]
Thanks for the suggestion! This would be a great feature to support.

I'll need to have a think about how interactive rebases might work best in the ui.

**Comment by morganlombard** [comment]
For the interactive rebase option I currently copy **hash** and then in the terminal type **git rebase -i \<hash\>**

VSCode is set as my git editor, so if you do **git rebase -i \<hash/branch\>** it opens the **git-rebase-todo** in VSCode. From there the user an just move lines up and down as desired and change the **pick** to **fixup** or the like.

It would be nice to instead of copying the hash to just select a rebase option.

**Comment by morganlombard** [comment]
Also adding an rebase option **--ignore-date** would be awesome

**Comment by mhutchie** [comment]
This will be available in v1.7.0.

If you'd like to use it before the next release, you can download [v1.7.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.7.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by t-gehring** [comment]
I'm trying this out in beta 2, and it would be really nice if interactive rebase was a separate option in the context menu, rather than being a checkbox in a popup - I'd rather not make two clicks where one would be enough. Other than that this is looking great.
