### ISSUE TITLE
Global search shortcut overridden when on Git Graph tab

### ISSUE THREAD

**Issue by niccolomineo** [mhutchie/vscode-git-graph#340]
On Mac, when on the Git Graph tab, CMD+Shift+f opens the current file search, not the global one (sidebar), as it should instead.

MacOs Catalina
Git Graph 1.24.0

**Comment by mhutchie** [comment]
Hi @niccolomineo,

I noticed this myself about a week ago and fixed it in [2ed0f2e8](https://github.com/mhutchie/vscode-git-graph/commit/2ed0f2e8ed1d5a7d81968f417824dd3d915e6826).

It will be available in v1.25.0. If you'd like to get this fix now, you can download [v1.25.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.25.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

Previously the keyboard shortcut detection code checked for CTRL/CMD + F, but didn't explicitly ensure that the shift modifier wasn't pressed. Windows users weren't affected as `e.key` is case sensitive (and the shift modifier check isn't required), whereas on Macs `e.key` is case insensitive and is normalized to lower case (making an explicit shift modifier check required).
