### ISSUE TITLE
New extension setting to set the default value of the "Show Remote Branches" repository setting.

### ISSUE THREAD

**Issue by niccolomineo** [mhutchie/vscode-git-graph#341]
Personally, I would like to keep the display of remote branches turnes off, since half the time I don’t need a comparison with the remote counterpart as I am force pushing my local branch on it. Maybe you coul add a default toggle for the feature?

**Comment by mhutchie** [comment]
Hi @niccolomineo,

Isn't this already covered by the "Show Remote Branches" checkbox on the Git Graph View top control bar? Although it defaults to `true` for new repositories, it's state (set by the user) is persisted per repository across sessions.

**Comment by niccolomineo** [comment]
Yep, default value for newly detected repos.

**Comment by mhutchie** [comment]
@niccolomineo, thanks for confirming that!

I'll add this as an extension setting in an upcoming release. This will make it consistent with other settings like "Show Tags" (where the default global value can be set via the extension setting, and then it can be overridden locally per repository).

**Comment by mhutchie** [comment]
This will be available in v1.26.0.

If you'd like to use it before the next release, you can download [v1.26.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.26.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
