### ISSUE TITLE
Automatic GitHub authentication

### ISSUE THREAD

**Issue by mill1000** [mhutchie/vscode-git-graph#342]
**Describe the improvement that you'd like**
VS Code now supports automatic GitHub authentication for git commands executed via the Source Control pane. It would be excellent if Git Graph could tap into this functionality so we don't always have to prompt for login information (or setup SSH keys).

**Comment by mhutchie** [comment]
Hi @mill1000,

Which platform are you using? Most platforms have pretty standard methods for caching Git credentials, so you don’t have to keep entering them (this is what I use on both Windows and Mac to allow Git Graph to automatically authenticate with GitHub, along with many Git Graph users).

Could you please provide a link to some documentation explaining the Visual Studio Code functionality you’re describing, I wasn’t aware of any vscode changes to this (are you referring to the “GitHub Pull Request and Issue“ extension - produced by GitHub). Unfortunately there are several reasons why Git Graph can’t directly integrate with the Visual Studio Code Git Extension (which provides the Source Control View), or other extensions that may or may not be installed on the users vscode environment. In saying that, up until now I’ve ensured that Git Graph exactly matches the Visual Studio Code Git credential handling, so if you could help clarify exactly which functionality you’re referring to, I’d be keen to implement equivalent capabilities in Git Graph if it is at all possible.

**Comment by mill1000** [comment]
Hi @mhutchie 

I'm using VSCode on various Windows 10 PCs usually with WSL or SSH remotes running Debian/Ubuntu/RHEL. I don't really have any technical details for you. Unsure how/if it's tied into the Pull Result and Issue extension. There's little mentioned here: https://code.visualstudio.com/docs/editor/github#_authenticating-with-an-existing-repository

All I really know is if I push with Git Graph I'm prompted for my username and password, where as if I push with the Source Control View I am not.

**Comment by mhutchie** [comment]
The URL you provided indicates that the authentication is being performed by the GitHub produced “GitHub Pull Request and Issue” extension. It would be helpful if you could confirm whether this is actually what is allowing the GitHub authentication for you. You should be able to:
1. Check if the GitHub produced extension is installed.
2. If so, disable the GitHub produced extension, and see if you still don’t need to provide credentials.

**Comment by mill1000** [comment]
I did not have the "GitHub Issues & Pull Requests" extension installed presently. It may have been installed at some point in the past.

When using `Manage Trusted Extensions` for my account (bottom left in activity bar) the only listed extension was "GitHub".

However, for the sake of experimentation, I loaded the "Issues & Pull Request" extension and found I had to authorize that extension. Now there is a separate entry for "Github Issues &  Pull Requests" in `Manage Trusted Extensions`.

Looks like there's a built in GitHub extension (ID: `vscode.github`). If I unauthorized this extension I am required to input credentials.

**Comment by mhutchie** [comment]
Thanks @mill1000, based on the information you've provided I've being able to track down how GitHub authentication is now integrated with Visual Studio Code.

Microsoft have introduced three new built-in extensions around the end of February this year: `vscode.github`, `vscode.github-authentication` & `vscode.github-browser`.

Based on my exploration of the code, `vscode.github-authentication` is handling the authentication for these new GitHub extensions, and the existing `vscode.git` extension (which manages the Source Control View). It is using a custom-built GitHub integration specifically for Visual Studio Code (see [here](https://github.com/microsoft/vscode/blob/cbf6164587bb518facfc7312c3b66eb3ac6cebfd/extensions/github-authentication/src/githubServer.ts#L16)), that is registered as a remote source provider for `vscode.git` to use [here](https://github.com/microsoft/vscode/blob/cbf6164587bb518facfc7312c3b66eb3ac6cebfd/extensions/github/src/extension.ts#L19-L23) in `vscode.github`. For Microsoft and GitHub to create an entirely new purpose-built system, it indicates to me that this must be the only feasible solution, and all other existing (simpler) git-based systems were inadequate. It also means that extensions (such as Git Graph) can't directly use the same underlying authentication method as it is not a publicly available system.

Currently Visual Studio Code does not allow extensions to access any authentication providers (such as the one by `vscode.github`), however they do plan to expose them soon as it's included in their [Proposed API](https://github.com/microsoft/vscode/blob/cbf6164587bb518facfc7312c3b66eb3ac6cebfd/src/vs/vscode.proposed.d.ts#L21-L269). This would theoretically allow extensions (such as Git Graph) to leverage the GitHub authentication system they have built. As this will be coming soon, I'll close this improvement request and move it to the backlog until (1) it is available & (2) I can upgrade the minimum version requirement of the extension to the corresponding vscode release without losing too many existing Git Graph users. Once these conditions are met I'll re-open this request and implement it, as I'm really keen to improve this experience for GitHub users.

In the meantime, I'd encourage you have a look at the various Git credential mechanisms (different for each platform), that can be easily configured using the information [on this page](https://git-scm.com/docs/gitcredentials). Using Git based authentication methods will allow yourself, or any program that runs git commands on your behalf (like Git Graph) to communicate with remotes (such as GitHub) without having to prompt for your credentials.

**Comment by mill1000** [comment]
@mhutchie Thanks for taking the time to dig into this. Regardless, love the extension so far.

**Comment by mill1000** [comment]
Hi @mhutchie 

I've noticed that the integrated terminal never needs to authenticate even if I haven't setup a credentials cache. VScode has a manner to pass authentication down to the integrated terminals via this option:
![image](https://user-images.githubusercontent.com/6924622/125167276-f34bbd00-e15c-11eb-9216-7366ebce55e5.png)

Which sets the following environment variables
```sh
VSCODE_GIT_ASKPASS_NODE=/home/mill1000/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/node
GIT_ASKPASS=/home/mill1000/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/extensions/git/dist/askpass.sh
VSCODE_GIT_IPC_HANDLE=/tmp/vscode-git-5091bc0332.sock
VSCODE_GIT_ASKPASS_MAIN=/home/mill1000/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/extensions/git/dist/askpass-main.js
```
and (I guess) hooks back into VScode and authenticates with whatever system they have.

Is this the same Authentication Providers mechanism you've described in #477 and #481? Or could this be a different approach to get Git Graph to authenticate against VScode without breaking < 1.48 compatibility?

**Comment by mhutchie** [comment]
Hi @mill1000,

Those Askpass environment variables allow Git to call an external program to retrieve the credentials to use for a Git command.

In Visual Studio Code, they use their own Askpass integration (configured with the environment variables you mentioned), to enter into their own code and initiate various authentication flows.

Unfortunately, Git Graph is unable to use the same Askpass integration for numerous fundamental reasons, hence the I implemented an equivalent Askpass integration for Git Graph (see https://github.com/mhutchie/vscode-git-graph/tree/develop/src/askpass). My Askpass integration simply prompts the user for a username and password, which is what Visual Studio Code did historically. When Visual Studio Code began enhancing their Askpass integration, they now call the new Authentication Providers to retrieve the user’s credentials (instead of prompting the user each time).

When the Visual Studio Code API for Authentication Providers becomes stable, and enough Git Graph users are compatible with it, then where the extension currently prompts for user credentials, it will instead leverage the Visual Studio Code Authentication Providers to retrieve the credentials. We are not yet at the time, but as I’ve said elsewhere, as soon as it meets those conditions I will integrate with it.

**Comment by mill1000** [comment]
Is it not possible to do both? I imagine the extension could query the availability of the authentication providers and fallback to the old prompt if not available.
