### ISSUE TITLE
Viewing graph of single file's changes?

### ISSUE THREAD

**Issue by nyanpasu64** [mhutchie/vscode-git-graph#343]
**Describe the feature that you'd like**
You can run `git log --graph -- path/to/file` to view the history of a single file. Is it possible to perform this in VSCode Git Graph?

**Additional context (optional)**
This feature is already implemented in some Git graph viewers. I took some screenshots of a file which I modified in several non-adjacent commits.

Git Cola DAG is weird. By default, it doesn't connect commits. If you type --all, it connects direct parent-child commits.

![git dag single file](https://user-images.githubusercontent.com/913957/86987406-cda36680-c14a-11ea-80ae-41bddddf9cf6.png)

git log --graph (with/without --all) connects all nodes, regardless of whether they're direct parent-child or not.

![git log single file](https://user-images.githubusercontent.com/913957/86987430-df850980-c14a-11ea-80ff-6327cf264718.png)

tig connects all nodes, regardless of whether they're direct parent-child or not. But you can't see any vertical lines except in the presence of merges or splits. I don't know if merge commits are shown if they edit path/to/file or not.

![tig single file](https://user-images.githubusercontent.com/913957/86987572-4276a080-c14b-11ea-88b1-1181dd503dbe.png)

**Comment by mhutchie** [comment]
Hi @nyanpasu64, Thanks for raising this feature request, and providing the detailed examples of how this is implemented in other tools.

This functionality is already within the scope of what I intend to deliver in the existing feature request #70, so I’ll close this one. Please follow #70 to keep up to date on the progress and delivery of it.
