### ISSUE TITLE
crtl + v command pastes double

### ISSUE THREAD

**Issue by Qadosch** [mhutchie/vscode-git-graph#344]
**Describe the Bug**
Pasting anything into Add-Tag textfields doubles the pasted text

[Video Proof](https://streamable.com/3qjcv0)

**Environment**
 - Git Graph Extension Version: v1.24.0
 - Visual Studio Code Version: 1.47.0 on remote WSL v0.44.4
 - Operating System: Windows 10

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
This is a bug that was introduced in Visual Studio Code 1.47.0, which affects all extensions that use Webview's (including the Git Graph View). Microsoft has been made aware of this as it is affecting heaps of users, and they have implemented a fix for it that will be available in the next Visual Studio Code recovery release (e.g. 1.47.1).

More information is available [here](https://github.com/microsoft/vscode/issues/101946).
