### ISSUE TITLE
Please relase 1.25

### ISSUE THREAD

**Issue by firattaskin** [mhutchie/vscode-git-graph#346]
i am using 1.25 features can u release, manuel import not sexy on share gir graph

**Comment by mhutchie** [comment]
Hi @firattaskin,

Apologies for the delay in getting Git Graph 1.25.0 released, I’ve been unwell the last week and a half so haven’t been able to complete the final testing of the release. I’m starting to feel much better the last few days, so I intend to get the release on this coming weekend.
