### ISSUE TITLE
Option to move graph icon in the commit editor toolbar into overflow menu/hide

### ISSUE THREAD

**Issue by jsg2021** [mhutchie/vscode-git-graph#347]
**Describe the feature that you'd like**
With the latest vscode, they changed the way repos are displayed. It would be nice to declutter this view a bit. 

**Additional context (optional)**
![image](https://user-images.githubusercontent.com/577453/87455757-8b0adf80-c5cb-11ea-878d-4f1f68720a3a.png)

**Comment by mhutchie** [comment]
Hi @jsg2021,

The existing extension setting [Source Code Provider Integration Location](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#source-code-provider-integration-location) can be set to `More Actions`. This will move the Git Graph button into the overflow menu, as you're requesting.

In the past this setting change reflected immediately in the Visual Studio Code Source Control View, however from what I can see it seems that now they require Visual Studio Code to be restarted for this setting to take affect. This mechanism is completely managed by Visual Studio Code, so I'm unable to make the setting change reflect sooner.

**Comment by jsg2021** [comment]
Awesome! I missed the setting when Was skimming. Sorry for the noise 😊 Thanks for the awesome extension!

**Comment by mhutchie** [comment]
@jsg2021, All good!

The number of extension settings has been steadily growing since I first created Git Graph, and consequently it’s become harder and harder for users to find the specific setting they need. In an upcoming release I plan on improving how the settings are structured, so hopefully they should be easier to find.
