### ISSUE TITLE
pin

### ISSUE THREAD

**Issue by caasi-dev** [mhutchie/vscode-git-graph#348]
**Describe the feature that you'd like**
With the new VSCode [pin tabs](https://code.visualstudio.com/updates/v1_46?ref=codebldr#_pin-tabs) feature, is there any chance too see if this could also be implemented to this extension so it stays pinned per project?

I understand there were some requests of this type previously, but perhaps this feature would make it more possible?

**Comment by mhutchie** [comment]
Hi @caasi-dev,

From what I can see, the Git Graph View can be pinned just like any other tab:
![image](https://user-images.githubusercontent.com/5315753/87541119-18d9ee00-c6e4-11ea-8dd8-98af60a51be9.png)

Could you please clarify what you mean by "so it stays pinned per project"?

**Comment by caasi-dev** [comment]
Sorry my mistake :-(
Pinning works great, I was meant to say that it will stay pinned once VSCode is closed and reopened. 
I did not elaborate mt second sentence about previous requests.

**Comment by mhutchie** [comment]
Thanks for clarifying that.

Unfortunately the recently introduced pin functionality is completely independent of the underlying Visual Studio Code limitation I previously outlined [here](https://github.com/mhutchie/vscode-git-graph/issues/276#issuecomment-596361340), that is preventing the Git Graph View (a Webview) from being restored across Visual Studio Code sessions.

As I previously mentioned, I'm keen to enable this capability as soon as Visual Studio Code addresses the underlying issue. I closely monitor all Visual Studio Code releases for a variety features and changes that would enable new capabilities in Git Graph, so I can re-open feature requests that were previously unachievable and temporarily moved to the backlog.

I'll close this feature request, as the delivery of the underlying Git Graph View tab restoration capability will be tracked in #276.

**Comment by ArnaudC** [comment]
Hello, anything new on this one ?

**Comment by mhutchie** [comment]
Hi @ArnaudC,

It looks like some progress has been made on Microsoft’s side recently, so I’ll have another look this weekend to see if the underlying issues are now resolved (or can feasibly be worked around).

**Comment by mhutchie** [comment]
Hi @ArnaudC,

I've just done some additional testing, and unfortunately the underlying Visual Studio Code limitation is still present. This prevents the Git Graph View (a Webview) from being restored across Visual Studio Code sessions, and there isn't any feasible work-around.

The recent progress that I mentioned on  Microsoft's side did resolve some other related concerns I had, but ultimately the same limitation is blocking this feature request.

Please follow #276 for updates on this, as it's tracking the delivery of the underlying Git Graph View tab restoration capability. Once it's possible & implemented, this feature will automatically be available.

**Comment by ArnaudC** [comment]
Hi,

I'm not an expert, but could it be possible to implement a
WebviewPanelSerializer ?

The doc says : https://code.visualstudio.com/api/extension-guides/webview

Then, in our extension's activate method, call
registerWebviewPanelSerializer to register a new WebviewPanelSerializer.

**Comment by mhutchie** [comment]
Hi @ArnaudC,

Yes, that's how to allow a Webview to be resumed after Visual Studio Code is restarted, and how I've already implemented it (since I started testing this capability over two years ago). The Visual Studio Code limitation I'm referring to is not this, it's to do with one of the many other changes that's required.
