### ISSUE TITLE
Add ability to do a merge from a commit

### ISSUE THREAD

**Issue by morganlombard** [mhutchie/vscode-git-graph#35]
**Describe the feature that you'd like**
From the context menu when right-clicking on a **commit**, add the option to **merge into current branch**, like when right-clicking on a **branch**.

**Comment by mhutchie** [comment]
Thanks for the suggestion!

**Comment by mhutchie** [comment]
This will be available in v1.4.4.

If you'd like to use it before the next release, you can download [v1.4.4-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.4-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
