### ISSUE TITLE
Merge branches after Pull Requests

### ISSUE THREAD

**Issue by MrCodingB** [mhutchie/vscode-git-graph#354]
I noticed that when I complete a PR (Pull Request), the GitGraph doesn't show a visual on the branch. Because when I merge two branches there is a line connecting the two, but I don't see anything when I complete a PR (which merges the branches). Is this because the PR is recognized as a commit? What can I do to change this (if it is just a bug)?

![grafik](https://user-images.githubusercontent.com/46847577/88544037-1c8d3f00-d019-11ea-9706-5aef41a5f1d9.png)

**Comment by mhutchie** [comment]
Hi @MrCodingB,

If you click on the PR Merge Commit "Merged PR 6: ..." to view the Commit Details View, how many parents are listed for it?

If there is only a single parent, the PR was likely squash merged (in which case the graph is being correctly rendered). Alternatively, if the commit has multiple parents can you see each of the parent commits within the commits loaded in the Git Graph View?

**Comment by MrCodingB** [comment]
Ah ok. Yeah it was squash merged. Makes sense that it gets displayed that way.

**Comment by mhutchie** [comment]
Hi @MrCodingB,

I’m glad that clarifies how the graph renders the parent relationships.

I’ll close this improvement request now as the existing rendering behaviour is correct.
