### ISSUE TITLE
Option to prune tags during fetch

### ISSUE THREAD

**Issue by leandro-manifesto** [mhutchie/vscode-git-graph#356]
Today there is an option that prunes local branches that were removed in the remote, but there is no option to do the same for tags.

**Comment by mhutchie** [comment]
Hi @leandro-manifesto,

Thanks for raising this feature request, I’ll add this as an option in the next release!

**Comment by mhutchie** [comment]
This will be available in v1.26.0.

If you'd like to use it before the next release, you can download [v1.26.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.26.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
