### ISSUE TITLE
Set a custom name for repositories

### ISSUE THREAD

**Issue by FStefanni** [mhutchie/vscode-git-graph#357]
Hi,

I am using a multi-root workspace which has some repo folders with the same name, e.g. "test-project".
The top filter of git graph shows the repos by folder names, and in this case it makes it harder to understand which repo is which.
It could be nice (whether there is no current way -- I did not found one...) to set a specific name for each repo,
in order to easily distinguish the two folders with the same name.
For example, by using the name associated into the workspace configuration file (but also any other setting is fine too).

Regards.

**Comment by mhutchie** [comment]
Hi @FStefanni, Thanks for raising this feature request!

I previously implemented a hint mechanism to aid the identification of repositories that share the same name (shown in grey to the right of the repo name). This is similar to how Visual Studio Code displays editor tabs when two files are open with the same name. In your multi-root workspace, are these hints not clear enough for you (e.g. based on the parent directory names)?
![image](https://user-images.githubusercontent.com/5315753/89526232-c72c0b80-d82a-11ea-8447-89547bc35ae5.png)

I really like the idea of allowing users to optionally set a display name for the each repository, I think many users in similar situations as yourself would benefit from it. I'll put it in Repository Settings Widget, as this seems a natural place that users would look for it.

FYI: As any number of repositories can be in subfolders of a workspace root, I wouldn't be able to use single name optionally associated with the root in the workspace configuration file.

**Comment by FStefanni** [comment]
Hi,

yes, I noticed the "hint", but it is truly not so clear for me.
Actually, I did not think to to the issue of having any number of repos inside a workspace folder, as you pointed out,
so basically it seems fine to me to be able to set a custom name in a dedicated configuration.

By the way, there is also a related issue for the built-in git plugin:

https://github.com/microsoft/vscode/issues/40548

I do not know if your extension could benefit from their effort...

Regards.

**Comment by mhutchie** [comment]
This will be available in v1.26.0.

If you'd like to use it before the next release, you can download [v1.26.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.26.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
