### ISSUE TITLE
Add scroll focus on main area when git-graph tab is opened

### ISSUE THREAD

**Issue by NikiforovAll** [mhutchie/vscode-git-graph#359]
I tend to use _git-graph_ by opening it from the command palette. It would be great if we could set focus on the main area by default so it is possible to use keyboard to scroll log and use tab for navigation between various controls (e.g. "Open a terminal for this repository", "Repository settings" and so on).

**Currently**, it is only possible to do it by clicking on the main area.

**Comment by mhutchie** [comment]
Hi @NikiforovAll, Thanks for bringing this to my attention!

Previously I only considered running the Git Graph View keystrokes (e.g. `CTRL/CMD` + `H`) immediately after the Git Graph View is opened (which does currently work immediately after the view is opened), not the browser native arrow key behaviour for scrolling. After looking into why this wasn’t already occurring for the arrow keys, I realised that the initial focus is going to the document body (the default behaviour built into web browsers / Electron), however in the Git Graph View a child of the document body contains the commits and scrolls (not the document body itself). I just had to manually set the focus to this child element on load, and it now allows the user to scroll immediately after load.

I’ll include this in a beta release for you to use (sometime this weekend).

**Comment by NikiforovAll** [comment]
Cool! Thank you for the explanation. I'm looking forward for the fix.

**Comment by mhutchie** [comment]
The change to the scroll focus behaviour will be available in v1.26.0.

If you'd like to use it before the next release, you can download [v1.26.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.26.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

---

I looked into enabling tab navigation for the Git Graph View Control Bar items, and decided against it for now as no other users have requested it, and if I were to implement it, it would likely be part of a much broader collection of tab navigation improvements throughout the Git Graph experience. I'll gauge user interest for tab navigation improvements to see if enough users would value it, and if so, I'll open a new feature request specifically for it.
