### ISSUE TITLE
Git graph tab icon not present in high contrast themes

### ISSUE THREAD

**Issue by Sesostrismage** [mhutchie/vscode-git-graph#362]
The git graph tab icon is not present in high contrast themes.

Icon shows with tomorrow night blue theme and all other dark themes I've checked:
![Git graph icon - tomorrow night blue theme](https://user-images.githubusercontent.com/24550972/89857917-a0a90000-db9d-11ea-984c-8c833d78171a.PNG)

Icon does not show with the built-in high contrast theme or with another high contrast theme I have installed:
![Git graph icon - high contrast theme](https://user-images.githubusercontent.com/24550972/89858030-e36ad800-db9d-11ea-9e59-7ccd7ecc5665.PNG)

**Comment by mhutchie** [comment]
Hi @Sesostrismage,

This is a limitation of Visual Studio Code itself, Git Graph sets the `iconPath` property of the Git Graph View's Webview [here](https://github.com/mhutchie/vscode-git-graph/blob/cecc24a305dddea77d2459e01e704c705a0be4e8/src/gitGraphView.ts#L94-L99) (as you can see, I just specify the URI of the icon - the extension has no theme specific logic). Visual Studio Code has chosen not to display the icon specified by the extension if the user has selected a high contrast theme. Unfortunately, there is nothing I can do within Git Graph to change the behaviour of the tab icon, as it is completely controlled by Visual Studio Code itself. More information on the Visual Studio Code `WebviewPanel.iconPath` property is available [here](https://code.visualstudio.com/api/references/vscode-api#WebviewPanel).

If you'd like the icon specified by any extension for their Webview's tab icon to be displayed in high contrast themes, please raise a feature request in the [vscode](https://github.com/microsoft/vscode) repository.

**Comment by Sesostrismage** [comment]
Thanks for the explanation.
