### ISSUE TITLE
Parse and render a frequently used subset of inline Markdown formatting rules in commit messages and tag details

### ISSUE THREAD

**Issue by PedroCuadra** [mhutchie/vscode-git-graph#364]
**Describe the feature that you'd like**
Hello, community!

I'd like to see  some basic **Markdown** highlight in my commits. 

**Additional context (optional)**

\*italic\* ➡ *italic*
\*\*bold\*\* ➡ **bold**
\*\*\*bold-italic\*\*\* ➡ ***bold-italic***
&grave;code&grave; ➡ `code`

**Comment by mhutchie** [comment]
Hi @PedroCuadra,

Thanks for raising this feature request, this would definitely be nice to have in Git Graph.

I’ll gauge user interest in this functionality, to prioritise its delivery.

Note to other users reading this: Please like the first comment in this thread if you’d value this functionality.

**Comment by mhutchie** [comment]
This will be available in v1.27.0.

If you'd like to use it before the next release, you can download [v1.27.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.27.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
