### ISSUE TITLE
Show file history as graph

### ISSUE THREAD

**Issue by bm-stschneider** [mhutchie/vscode-git-graph#366]
**Describe the feature that you'd like**
Currently there is only a view for commit. It would be nice if you could right click on a file and show its history in a graph.

**Comment by mhutchie** [comment]
Hi @bm-stschneider, Thanks for raising this feature request.

This functionality is already within the scope of what I intend to deliver in the existing feature request #70, so I’ll close this one. Please follow #70 to keep up to date on the progress and delivery of it.
