### ISSUE TITLE
Add support for native right click menu

### ISSUE THREAD

**Issue by phgmacedo** [mhutchie/vscode-git-graph#367]
VS Code supports native context menus with `    "window.titleBarStyle": "native",`

With this option, the context menu can appear outside the application window, as can be seen in this screenshot:
![1](https://user-images.githubusercontent.com/2473545/90699588-12e2aa00-e25a-11ea-9a55-f697a249396f.png)

Git graph currently does not support this option, which can make the context menu unusable in certain situations, like this:

![2](https://user-images.githubusercontent.com/2473545/90699651-3279d280-e25a-11ea-8b6c-0724d1e0f111.png)

Pleasse, consider adding support for native context menus.

**Comment by mhutchie** [comment]
Hi @phgmacedo,

This would definitely be nice to have, and has many advantages over the current context menus as you mention.

From what I can see, support for native context menus is only available in Visual Studio Code itself, and is not made available for extensions to leverage within [Webview’s](https://code.visualstudio.com/api/extension-guides/webview), which is how the Git Graph View is rendered (and is the only way for extensions to contribute rich interfaces). Webview’s contributed by extensions run in an isolated context for security reasons from the Visual Studio Code perspective, but this inherently restricts the functionality available within them.

I’ll close this feature request for now, as everything I’ve read suggests this is just not possible at the present time. However, if in the future I become aware of a way to achieve this, Visual Studio Code provides a mechanism to achieve this, or someone can reply to this thread with a feasible solution, I’ll definitely reopen and implement this.
