### ISSUE TITLE
Make Gravatar avatar fetch case-insensitive

### ISSUE THREAD

**Issue by mhutchie** [mhutchie/vscode-git-graph#369]
**Describe the improvement that you'd like**
As per the instructions on https://en.gravatar.com/site/implement/hash/, the email address being fetched should be converted to lower case before being MD5 hashed.

**Comment by mhutchie** [comment]
This will be available in v1.26.0.

If you'd like to use it before the next release, you can download [v1.26.0-beta.4](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.26.0-beta.4), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by DmytroSokhach** [comment]
> This will be available in v1.26.0.
> 
> If you'd like to use it before the next release, you can download [v1.26.0-beta.4](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.26.0-beta.4), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

Works for me!
Note: Took me about 3 times to Clean Avatar Cache and Reload Window (not sure why it didn't work from 1st time)
