### ISSUE TITLE
Resizable columns

### ISSUE THREAD

**Issue by meierw** [mhutchie/vscode-git-graph#37]
The "Graph", "Description", etc. columns should be resizable. When working with massive repositories, the graph column can become very large, even though the latest most relevant commits/branches are only a few levels deep. ([example](https://i.imgur.com/d64bN4S.png))
Ideally the resized column width values would be saved/restored for each individual repo.

GitKraken has a pretty good implementation of this I think, by allowing you to peek the commit avatar behind the hidden part ([example](https://www.gitkraken.com/img/misc/gitkraken.jpg))

**Comment by mhutchie** [comment]
Thanks for the suggestion, this is definitely something I'd like to support!

**Comment by mhutchie** [comment]
This will be available in v1.4.5, which I intend to release in the next day.

If you'd like to use it before the next release, you can download [v1.4.5-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.5-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
