### ISSUE TITLE
Support bare repositories

### ISSUE THREAD

**Issue by n-gist** [mhutchie/vscode-git-graph#379]
Hi! I tried to add bare repo through Git Graph: Add Git Repository, but it seems like it does not supported. I tried to put files inside '.git' folder, but it does not worked too.
Would be nice to have this possibility. Sometimes visual management is much more convenient. Thanks for great extension!

**Comment by mhutchie** [comment]
Hi @n-gist,

As Git Graph is an extension for Visual Studio Code, it has many integrations with Visual Studio Code itself (via the Visual Studio Code API), that are required for it to function. From what I can see, Visual Studio Code doesn't support bare repositories (either when they are opened as the workspace root, or they are a folder within a multi-root workspace) - there appear to be numerous feature requests that are open for it though.

If the bare repository was within the Visual Studio Code Workspace, even without Visual Studio Code directly supporting them, it would at least be possible for Git Graph to offer a decent amount of support for them. However, based on my current understanding of bare repositories, it would require a substantial amount of work to add support for them to Git Graph - in order for a seamless experience to be achieved.

For the following reasons, I'll close this improvement request for now and move it to the backlog:
* Visual Studio Code doesn't support bare repositories.
* A substantial amount of work would be required to support bare repositories in Git Graph, and out of the ~640,000 users you're the first to raise this improvement (indicating that this substantial amount of work would only benefit a relatively small proportion of users).

However, if in the future Visual Studio Code supports bare repositories, or a significant number of Git Graph users indicate they would value this functionality, I'd happily reconsider and re-open / implement this request.

Note: If you're another Git Graph user reading this in the future, and would support for bare repositories to be implemented, please like the first comment in this thread. This allows me to gauge community interest and re-prioritise them.
