### ISSUE TITLE
push tag option

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#38]
First, thx for this great plugin.

It would be nice if we had an option to push the Tag once created.

![image](https://user-images.githubusercontent.com/44493964/54544507-18bac880-49a0-11e9-9f64-cbb4dc09e021.png)

**Comment by mhutchie** [comment]
Thanks for the suggestion, this is a great idea!

**Comment by mhutchie** [comment]
This will be available in v1.4.4.

If you'd like to use it before the next release, you can download [v1.4.4-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.4-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by rbalet** [comment]
I test it, it work like a charm :) 
Thx a lot
