### ISSUE TITLE
New context menu for Commit Details View Files, containing the existing File Actions

### ISSUE THREAD

**Issue by nicklaros** [mhutchie/vscode-git-graph#381]
**Describe the Bug**
When Clicking on a commit, it shows commit detail and when I hover on a file it will show some action buttons, such as:
- Copy File Path to the Clipboard
- View File at this Revision
- Open File

But when Git Graph opened in small window or tab, some buttons got truncated, makes it unclickable.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open Git Graph on small tab or vs code window.
2. Click on some commit
3. Hover over on some file which changed in that commit 
4. See Some button got truncated and unclickable

**Expected Behaviour**
Button don't get truncated so I can click it.

**Environment**
 - Git Graph Extension Version: 1.26.0
 - Visual Studio Code Version: 1.49.0
 - Operating System: Manjaro Linux 20.1

**Screenshots (optional)**
Here I try to hover on file `store_setting_ormer.go` but `View File at this Revision` and `Open File` button got truncated and hidden.
![Screenshot_2020-09-16_05-54-50](https://user-images.githubusercontent.com/2937466/93273844-19c1f580-f7e3-11ea-9231-9f8cb38517cb.png)

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @nicklaros,

The Commit Details View File View is constrained to a fixed width, determined by the user (who can resize: the VSCode Window width, the Git Graph View’s width, and the horizontal divider between the information and File View in the Commit Details View). There are several reasons why I’ve decided not to add a horizontal scroll bar to the File View, that unfortunately means some content must be hidden when not enough width is available. Based on feedback I’d received from users, the buttons were determined to be the least useful / used component, so it made sense to hide them first.

Although I’m not wanting to change the current overflow behaviour, I think this would be a great opportunity to make the “Copy File Path to the Clipboard”, “View File at this Revision” & “Open File” buttons also accessible by right clicking on the corresponding file name in the Commit Details View File View. This would ensure these actions are always available no matter how much width is available. I think this might actually be the preferred location of these actions for some users.

I’ll change this bug to a feature request and make it available in the next version of Git Graph. I’ll also publish a beta release of this functionality this weekend, so you can use it straight away.

**Comment by nicklaros** [comment]
I see, showing it on right click menu would be a great additions. Thanks @mhutchie 

Did I forgot to say Git Graph was a great extension? Yes indeed it's great and one of my favorite vs code extension.

**Comment by mhutchie** [comment]
Hi @nicklaros,

I've implemented the right-menu for the files in the Commit Details View, and I'm really pleased with how it's turned out (I think many users will regular use it). Unfortunately there are a number of edge cases (e.g. when the Commit Details View is docked to the bottom of the Git Graph View, and when background data refreshes occur), that are going to take some extra time to get working.

Although I won't have a beta release with this functionality available this weekend, I'll continue working on these corner cases, and make it available as soon as possible.

**Comment by mhutchie** [comment]
This will be available in v1.27.0, which will be released later this weekend.
