### ISSUE TITLE
Push Branches & Tags to Multiple Remotes

### ISSUE THREAD

**Issue by caasi-dev** [mhutchie/vscode-git-graph#385]
**Describe the feature that you'd like**
Git Graph currently supports managing multiple remotes. When pushing a branch we are give drop down box to select which remote we would like to push to. It would be fantastic if instead of a drop down box we could have check boxes. Then when selecting push branch we could select remotes that we would like to push the branch to.

Those check boxes would trigger a queue of `git push` commands. Assuming we have the following setup:
- **origin** - git@github.com:USER/repo.git
- **staging** - USER@remote_host:/path_to_git_repo
- **production** - USER@remote_host:/path_to_git_repo

The dialog could look something like this:

![gitgraph](https://user-images.githubusercontent.com/60949037/93638762-253a3a00-f9f8-11ea-8bc7-5f021add8a47.png)

**Comment by mhutchie** [comment]
Hi @caasi-dev,

Thanks for raising this feature request, this would be really useful to have in Git Graph! I’ll include it in the next release.

**Comment by caasi-dev** [comment]
Thank you, I've started studying your extension, so maybe in the future, I could help with PRs :-)

**Comment by mhutchie** [comment]
This will be available in v1.27.0.

If you'd like to use it before the next release, you can download [v1.27.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.27.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by caasi-dev** [comment]
I am trying to test it, and I can confirm that I have 1.27.0-beta.1 installed as seen in the image below

![image](https://user-images.githubusercontent.com/60949037/93687801-ecb26300-fac0-11ea-9a5f-90f70ef1147d.png)

How was it implemented? With the suggestion above? Check-boxes?

Here is my repo confing

![sdsd](https://user-images.githubusercontent.com/60949037/93687832-4a46af80-fac1-11ea-9ba4-81f918ae04dd.png)

But I do not seem to be able to see the checkboxes? But still drop-down

![image](https://user-images.githubusercontent.com/60949037/93687845-6fd3b900-fac1-11ea-83ea-56f9d9097839.png)
 

Have I done something wrong?

**Comment by mhutchie** [comment]
Hi @caasi-dev,

The “Push to Remote(s)” input is now a multiple select input (notice the checkbox next to the “origin“ item). You can click multiple items in the select list, just like if they were a list of checkboxes.

FYI: The reason I chose a multiple select input instead of multiple checkboxes, is that if checkboxes were used, the dialog would change height depending on the number of remotes the user had. This isn’t ideal if the user has many remotes, as the dialog would become extremely tall. By using a multiple select input, the dialog always maintains the same height, no matter how many remotes the user has.

**Comment by caasi-dev** [comment]
Ah that's a very good design choice and I guess I will have to update my theme to make those checkboxes more obvious. Will give it another test on Monday. Cheers!

**Comment by caasi-dev** [comment]
works great, thank you !
