### ISSUE TITLE
On double click - Checkout branche

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#39]
Triggering the "Checkout branche" function when double clicking on the branch name.

Like gitkraken does
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44493964/54605119-cf728380-4a48-11e9-8a9f-00671becde11.gif)

**Comment by mhutchie** [comment]
This will be available in v1.4.4.

If you'd like to use it before the next release, you can download [v1.4.4-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.4-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by rbalet** [comment]
Amazing, thx a lot
