### ISSUE TITLE
Force option when tagging or branching

### ISSUE THREAD

**Issue by TomasJuocepis** [mhutchie/vscode-git-graph#390]
**Describe the feature that you'd like**
git has a force option '-f' when adding tags or branches. I often "move" tags or branches (e.g. after rebase, push, etc) with the force option as it allows to use a single command as opposed to having to delete an existing tag/branch and then to re-create it again.

One option is to simply add a checkbox 'Force' below, let's say, the name input field.

Alternative option is to add a "force" button on the "already exists" error dialog (i.e. user adds a tag, gets the "already exists" dialog with the existing button for ack/dismiss/no-op action and a new button to "delete existing" conflicting tag/branch and continuing with adding the new tag.

**Comment by mhutchie** [comment]
Hi @TomasJuocepis, thanks for raising this feature request, it would be great to have this in Git Graph!

I’ll include it in an upcoming release of Git Graph.

**Comment by mhutchie** [comment]
This will be available in v1.29.0.

When creating a branch or adding a tag, the name is now checked against the existing branches and tags in the repository. If a branch / tag already exists with the same name, a new dialog is displayed that allows you to: replace the existing branch / tag, or to choose another name.

If you'd like to use it before the next release, you can download [v1.29.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.29.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
