### ISSUE TITLE
push on merge

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#391]
**Describe the feature that you'd like**
Add an option for the user to be able to push on merging two branches together.  

**Additional context (optional)**
I heard that others git tool like [fork](https://git-fork.com/)  did give the option _(didn't test it myself)_

_workflow_ : developing on a `dev` branch, then, when we want to merge it back to the `master` it's only because we want to push it on the master branch.  

_Possible problem_ : If the user that push don't have any right to push on such branch, _but it shouldn't be a problem for that feature_

**Comment by mhutchie** [comment]
Hi @rbalet,

Thanks for raising this feature request!

I've deliberately tried to avoid combining separate Git actions (by keeping them independent of each other), as it allows the user to easily compose multiple Git actions in any order based on there needs, while minimising the number of options on the Git action dialogs (to avoid overloading the user with options). The Merge Branch Dialog currently has three options on it, and I've already had feedback that this has been intimidating (and/or confusing) to numerous new users - all they want to do is merge a branch. Additionally, providing a "push to remote" option is even more cluttering if the user has multiple remotes as it requires a multi-select input.

Although implementing this one request would be easy to do, and streamlines the experience for a portion of users, it sets a precedent that I'm willing to combine any arbitrary actions together. I can think of many other examples were it would be faster for a small portion of users to combine actions on a single dialog (that other users would request), so this single feature request spirals over time to become many options cluttering many dialogs.

For these reasons, I'll close this feature request. I completely understand and agree with you that combining these two actions would provide a faster experience for the portion of the users who would use it, but it's my current opinion that the precedent it sets will have a net negative affect for the majority of users.

**Comment by rbalet** [comment]
Hi @mhutchie and thanks for you answer.   

I understand what you're saying and it makes sense.

Just to take the discussion a little bit further, since you want to avoid complexity in the UI (What I find clever from your side) , it may frustrate more advanced developers that daily needs your tool.  

Could be, adding such feature directly inside the vsCode user setting something that you could consider?  
(I se you already did it for a couple of other options, would also understand if adding it here would only move the problem there and you don't think it as a good Idea).
