### ISSUE TITLE
New git.path array option causes error in Git Graph: "Unable to find a Git executable"

### ISSUE THREAD

**Issue by charlwillia6** [mhutchie/vscode-git-graph#392]
**Describe the Bug**
VSCode settings now allows git.path to be an array of strings for searching different paths for the git executables.  Since vscode-git-graph consumes the git.path setting, this now causes the following error: "Unable to find a Git executable"

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Change git.path in settings.json to `git.path: ["C:\\path\\to\\git.exe", "C:\\another\\path\\to\\git.exe"]`
2. Re-open Visual Studio Code
3. Error appears

**Expected Behaviour**
Git Graph should recognize arrays for the git.path setting now.

**Environment**
 - Git Graph Extension Version: v1.26.0
 - Visual Studio Code Version: 1.50.0
 - Operating System: Windows 10

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/9610352/95592291-6a112980-0a16-11eb-98d4-17f7b7ea5a62.png)

**Additional Context (optional)**
I realize this is a new feature released in the stable version of VSCode to allow arrays of strings for the git.path setting.  I am making Git Graph developers aware of this change to VSCode so that this can be fixed quickly.

**Comment by mhutchie** [comment]
Thanks @charlwillia6 for making me aware of this!

I find it extremely frustrating that the VSCode team just releases breaking changes like this, without notifying extensions that are affected.

Fortunately shouldn't affect too many users. It will only affect users who:
* Are new to Git Graph & they already define an array in `git.path`, as Git Graph won't have cached the last know Git executable. When Visual Studio Code starts up, Git Graph will check if the last known Git executable still exists, and if so, reuse it.
* Change `git.path` to the array format while the Git Graph extension is installed.

I'll make a beta release with support for this available within the next 24 hours. I plan on doing a new full release of the extension almost certainly next weekend 18/10/2020, this this change will also be included in it.

**Comment by mhutchie** [comment]
This will be available in v1.27.0.

If you'd like to use it before the next release, you can download [v1.27.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.27.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
