### ISSUE TITLE
Reset local branch with the remote branch.

### ISSUE THREAD

**Issue by alexisfrjp** [mhutchie/vscode-git-graph#395]
During a checkout from a remote branch, I'd like to be able to overwrite/reset the local branch with the remote branch. The remote branch has been force pushed and/or my local branch has changes not committed/stashed, then choosing `Checkout the existing branch & pull changes` will just lead to merge conflicts.
```
Error: Unable to Checkout Branch & Pull Changes
error: you need to resolve your current index first
```

*Gitkraken* has a feature `Reset Local to Here` when I want to checkout a branch.
I'd like to slowly replace GitKraken/GitAhead with a single tool such as Git Graph.

**Comment by mhutchie** [comment]
Hi @alexisfrjp,

Thanks for this feature request, this would be great to have in Git Graph!

**Comment by mhutchie** [comment]
I've explored numerous Git commands (and combinations of commands) that have the affect of resetting a local branch with a remote branch, while handling "remote branch has been force pushed and/or my local branch has changes". Each option has various subtle nuances and pro's & con's, however I believe I've implemented the option with the most net value for users (across many different workflows - not just the one specifically mentioned in this feature request).

From the remote branch context menu, the "Fetch into local branch..." action now has the option to "Force Fetch", which when enabled has the affect of "Force the local branch to be reset to this remote branch.". The only limitation is that the local branch can't be checked out when doing the Force Fetch, as most Git commands won't allow the checked out branch to be force updated.

In the use case you mentioned, I believe you would:
1. Do a Force Fetch from the remote branch into the local branch
2. Checkout the local branch

Please try out the implemented solution, and let me know if it works for your use case. If you don't think the implemented solution is workable, I'm more than happy to explore alternatives and implement them as well (as long as I haven't it out for some reason).

---

This will be available in v1.30.0.

If you'd like to use it before the next release, you can download [v1.30.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.30.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by jleni** [comment]
I think it would be good to have an additional option in this menu:

![image](https://user-images.githubusercontent.com/13698520/126078266-e778932b-58ef-482f-a78f-19aa5c573194.png)

that says:

- Reset local master to remote master

**Comment by Yuyan-Li** [comment]
Hello, I didn't want to open a new issue thus commenting here.

Resetting my current local branch on the remote is something I do very frequently. As this is not directly possible my work around is right-clicking the commit instead of the branch and then do the reset.

> I've explored numerous Git commands (and combinations of commands) that have the affect of resetting a local branch with a remote branch, while handling "remote branch has been force pushed and/or my local branch has changes". Each option has various subtle nuances and pro's & con's

Could you explain this a little more? As I see it, a remote branch is no different to a local branch. This is even more clear as you can easily reset/rebase on the commit the remote branch is pointing to. So why shouldn't you be able to do it on the branch. (I'm referencing to rebasing on remote branches which I also often do. #329)

Resetting to the tracking remote branch in the command line would be done with.
```
git reset @{u}
```
But it could as well be done with the full branch name which also works for any remote branch
```
git reset origin/name-of-branch
```
