### ISSUE TITLE
Force delete a branch not working

### ISSUE THREAD

**Issue by krzikalla** [mhutchie/vscode-git-graph#396]
**Describe the Bug**
 I open the context menu for a branch name, click on "delete branch" and check the  "force delete" box. 
The following message appears:
```
Error: Unable to Delete Branch
usage: git branch [options] [-r | -a] [--merged | --no-merged]
or: git branch [options] [-l] [-f] <branchname> [<start-point>]
or: git branch [options] [-r] (-d | -D) <branchname>...
or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

(and some more usage text)
```

The branch is not deleted. `git branch -D branchname` from the terminal works as expected (and the tree view is refreshed). 

**Environment**
 - Git Graph Extension Version: 1.26.0
 - Visual Studio Code Version: 1.50.1
 - Operating System: Windows 10 client, Linux server (remote connected via ssh)

**Comment by mhutchie** [comment]
Hi @krzikalla,

Would you please include the full output shown on the error dialog? The most I can get from the snippet you’ve included is that it appears the arguments provided to the Git command are not valid.

If you look at the Git Graph Output Channel logs, you should be able to see the exact Git command that Git Graph is running. Can you try running it in the terminal? (it should be `git branch --delete --force branchname`). Also please include it in your reply.

At the beginning of the Git Graph Output Channel logs, there will be a line that indicates the path and version of Git that Git Graph is using. Would you please include it in your reply?

This is such a basic Git command, so if there was a Git Graph bug I’m sure many users would have reported it out of over 700,000 users in the last 18 months (it has remained unchanged the entire time) - no one else has reported any issues.

**Comment by krzikalla** [comment]
The issued command is right. But:

`[2020-10-16 09:51:41.943] Using git (version: 1.8.3.1)`

That's the problem - the version is to old. In my .bashrc I load git 2.18.4. That version is then also active in the VC terminal. 
But: how do I load that module before gitgraph starts? 
Also: it would be good to issue a warning, if an unsupported git version is used.

**Comment by mhutchie** [comment]
Hi @krzikalla,

Visual Studio Code provides the setting `git.path` that allows you to specify the path and filename of a Git executable that you'd like Visual Studio Code to use. Most Git-related extension in Visual Studio Code (including Git Graph) also use this setting to determine which Git executable to load (if set). This setting is designed for exactly your situation, where there are multiple valid Git executables on the File System.

The reasons why I don't have a warning in Git Graph is:
* Most Git Graph features work fine for very old versions of Git, there are just a handful of exceptions (like the one you've found).
* Visual Studio Code already has a prompt if the user is not using Git 2.*.*, adding one in the extension is doubling up on the same notification.
* Almost all of the time Git Graph will use the same Git executable as Visual Studio Code, even though it discovers which Git executable to load independently from Visual Studio Code. However, there are some unavoidable cases that may cause different executables to be used, when there are multiple Git executables on the file system. The number of users potentially affected by this scenario, who have multiple versions of Git installed on their computer, is extremely low.

I'll close this as I believe this issue has now been resolved.
