### ISSUE TITLE
Support for git show

### ISSUE THREAD

**Issue by mminchev** [mhutchie/vscode-git-graph#4]
First of all, thank you for this awesome extension. I really love it.

The only important functionality that it is missing at the moment in my opinion is the ability to see all file changes within a given commit. Something like "git show" but implemented within the UI.

Thanks and keep up the excellent work!

**Comment by mhutchie** [comment]
I've been working on adding support for "git show" the last two days, and it should be ready for the next release in the next few days. Thanks for the feedback!

**Comment by mhutchie** [comment]
Viewing commit details from git show, and a tree view of file changes is ready for release in 1.3.0.

Opening a commit file diff from the tree will be in the next release, due to integration considerations with VSCode's diff viewer.

**Comment by mminchev** [comment]
Hi @mhutchie , I understand. Thanks for the update, I just tried out the latest version. The extension already looks much better than the "Git History" extension which seems to be popular in the community.

**Comment by mminchev** [comment]
Btw, one idea for an improvement for the next version. It would be nice if you can close the commit details view when you click again on the commit line. Currently, when you click again on the line, it just refreshes the view. Thanks!

**Comment by mhutchie** [comment]
I've made the change so that when you click again on the commit line it closes the commit details.

**Comment by mhutchie** [comment]
Hi @mminchev, I've just released the integration with the Visual Studio Code Diff View in v1.3.1 (from #5). Thank you for all of your feedback.

**Comment by mminchev** [comment]
@mhutchie , this was incredibly quick! Thank you one more time. Version 1.3.1 looks extremely well!
