### ISSUE TITLE
Ability to select/deselect hunks in Diff view for uncommitted changes

### ISSUE THREAD

**Issue by BLitzMe** [mhutchie/vscode-git-graph#400]
This is mainly an inspiration from jet brain's products.

It would be great to be able to have a commit dialogue(or simply icons next to line numbers in diff view) where one can select/unselect hunks to commit with a certain commit. The same functionality that is available on command line with git add --patch.

**Comment by mhutchie** [comment]
Hi @BLitzMe,

This functionality is already built into Visual Studio Code's Git Extension. When you click on a file (first screenshot), you can highlight chunks in the new (right) side, and run "Stage Selected Ranges" (second screenshot).

![image](https://user-images.githubusercontent.com/5315753/96559075-4bf5d400-1308-11eb-9ced-f532f7fe6181.png)
![image](https://user-images.githubusercontent.com/5315753/96559157-64fe8500-1308-11eb-903a-8cec67beb2e0.png)

When you open the Diff View for a file in the "Uncommitted Changes" from Git Graph, it just opens the Visual Studio Code Diff View for the file, between the HEAD commit (on the left), and the current version of the file on your file system (on the right). This already allows you to "Stage Selected Rages" and "Unstage Selected Ranges", as it is using the Visual Studio Code Diff View. The only difference is that within Git Graph, I don't distinguish been the Staged and Unstaged Uncommitted Changes (and therefore you can't open a Diff View specifically for the Unstaged Changes only).

I decided not to provide this functionality in Git Graph, as:
* It is already available built into the Visual Studio Code's Git Extension - I always try to complement what's already provided in Visual Studio Code with new features in Git Graph. It's wasted time/effort for me to duplicate the existing behaviour, as my time is far better spent by implementing features not already available in Visual Studio Code.
* There is a decent amount of complexity to implement it.

Please let me know if I've misunderstood your request.

**Comment by mhutchie** [comment]
I'm closing this feature request for now, as I believe my previous response addresses it, and I haven't heard any response.

**Comment by BLitzMe** [comment]
Thanks for the response. 
You're correct, your response does address the issue. The inbuilt git support also needs to improve though, but that's microsoft's headache. 
Thankyou for your amazing work, I would love to be able to contribute in near future.
