### ISSUE TITLE
Ability to reset branch (soft, hard, mixed, keep) from right click menu

### ISSUE THREAD

**Issue by BLitzMe** [mhutchie/vscode-git-graph#401]
This is also an inspiration from jetbrains products. 

On the menu that appears upon right clicking on a commit, the options to reset current branch to the commit being clicked on would be great to have. The same menu where we have Add Tag, Create Branch, Drop, Revert, Merge etc.

**Comment by mhutchie** [comment]
Hi @BLitzMe,

Unless I'm misunderstanding, this is already available in the "Reset current branch to this Commit...".

![image](https://user-images.githubusercontent.com/5315753/96558554-94f95880-1307-11eb-8eff-c164124eb7d6.png)

![image](https://user-images.githubusercontent.com/5315753/96558615-a93d5580-1307-11eb-85b4-240ea5b29101.png)

Please provide additional information to clarify your request if I've misunderstood.

**Comment by BLitzMe** [comment]
yes you're correct. I'll close this request.
