### ISSUE TITLE
Find Widget Mode to open Commit Details View

### ISSUE THREAD

**Issue by Urkallinger** [mhutchie/vscode-git-graph#402]
First of all thank you for this great extension. I use it every day. For me it's the best extension to look at the git history.

But right now I'm missing an important feature.

Since I do code reviews every day and identify commits by ticket number, I use the search function very often. However, the search only highlights the commit but doesn't open it. So I have to click with the mouse on the commit every time to see the details. 

When opening the next match, would it be possible to open the commit details instead of just highlighting it?

**Comment by mhutchie** [comment]
Hi @Urkallinger,

Thanks for raising this feature request, I think this would be great to have in Git Graph. I’ll definitely include it in an upcoming release!

I think it would be best to have this behaviour enabled/disabled by a new toggle on the Settings Widget, so users can easily configure the behaviour they prefer.

**Comment by mhutchie** [comment]
This will be available in v1.29.0.

If you'd like to use it before the next release, you can download [v1.29.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.29.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
