### ISSUE TITLE
The GitGraph tab does not reopen after reopening or reloading VSCode

### ISSUE THREAD

**Issue by kanlukasz** [mhutchie/vscode-git-graph#403]
**Describe the Bug** _( Note: I'm not sure if it's a bug. Sorry for the doubt )_

- While I'm working with a project and have some tabs open, I also have GitGraph open
![obraz](https://user-images.githubusercontent.com/30685349/97000403-f4897b00-1536-11eb-8d5b-729b124afd01.png)

- But after reloading VSCode, GitGraph does not reopen like other tabs:
![obraz](https://user-images.githubusercontent.com/30685349/97000811-95783600-1537-11eb-9f14-59e7b451caf7.png)

**Steps to Reproduce**
1. Run the project in VSCode
2. Initialize the git repository
3. Do something
4. Open some tabs and the GitGraph tab too
5. Try to reload VSCode

**Expected Behaviour**
- The GitGraph tab should work the same as any other tab. It should not close automatically

**Environment**
 - Git Graph Extension Version: [1.26.0]
 - Visual Studio Code Version: [1.50.1]
 - Operating System: [Windows 10 2004]

**Comment by mhutchie** [comment]
Hi @kanlukasz,

The Git Graph View uses a Visual Studio Code [Webview](https://code.visualstudio.com/api/extension-guides/webview) to render, as it's the only way for any extension to contribute a view. Unfortunately there are some limitations with Webview's, which prevent the Git Graph View from being restored after Visual Studio Code is re-opened or reloaded. Visual Studio Code Webview's are different to the other text editors (which is we they can reopen as you would expect).

I already have code committed on a separate branch that allows the Git Graph View to be restored after Visual Studio Code is re-opened or reloaded (from almost a year ago). However, I'm still waiting on Microsoft to make some adjustments to their Webview API, so the experience is seamless and as expected (currently there is an issue that prevents it from working well - many users would deem it a bug).

I'll close this for now, however hopefully this capability will soon be resolved in the Visual Studio Code Webview API, and I can subsequently enable it for the Git Graph View.
