### ISSUE TITLE
add the Issue Linking generated links to the context menu for copying

### ISSUE THREAD

**Issue by PiIsFour** [mhutchie/vscode-git-graph#404]
Hi, i would like to ask if it would be possible to

add the Issue Linking generated links to the context menu for copying?

I like the Issue Linking because I don't have to remember the Numbers all the time. Recently I started working inside an VM but have my Issue tracking still in on my local PC. So opening the Issue link inside the VM is not helpful to me, but if I could copy the link, that would be faster. Not sure if this is something you could add without to much work, otherwise I will keep coping the text.

Thanks for your time and this great Extension.

**Comment by mhutchie** [comment]
Hi @PiIsFour,

Thanks for this suggestion, it should be relatively quick to implement, and I think it would be useful to a decent number of users.

I’ll probably create a new context menu for this, that is activated when right clicking on any External URL’s in Git Graph (e.g. Issue Links & auto-detected URL’s in the Commit Details View).

**Comment by PiIsFour** [comment]
@mhutchie Thanks for the quick answer

**Comment by mhutchie** [comment]
This will be available in v1.29.0.

If you'd like to use it before the next release, you can download [v1.29.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.29.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by PiIsFour** [comment]
@mhutchie just tried it, works beautifully. Thanks a lot, this is amazing.
