### ISSUE TITLE
Include built-in support for new emoji shortcodes recently added to gitmoji

### ISSUE THREAD

**Issue by mhutchie** [mhutchie/vscode-git-graph#409]
**Describe the improvement that you'd like**
In the last five months, gitmoji have made the following changes:
* Renamed `:pencil:` to `:memo:`
* Added `:passport-control:`

These changes should be reflected in the built-in set of emoji shortcodes supported in Git Graph.

**Additional context (optional)**
I've included importing gitmoji into my pre-release steps, so that going forward the set of gitmoji in Git Graph is always kept in sync.

**Comment by mhutchie** [comment]
This will be available in v1.28.0.

If you'd like to use it before the next release, you can download [v1.28.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.28.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by Pustur** [comment]
> I've included importing gitmoji into my pre-release steps, so that going forward the set of gitmoji in Git Graph is always kept in sync.

@mhutchie Was the above ever done? I see that currently we are missing a few gitmoji, namely:

- `:coffin:` ⚰️
- `:monocle_face:` 🧐 
- `:necktie:` 👔
- `:test_tube:` 🧪

Would you kindly add them? Or should I open a new issue first?

Thanks

**Comment by mhutchie** [comment]
Hi @Pustur,

Those new Gitmoji will automatically be included in the next Git Graph release. There’s no need for you to open a new issue.
