### ISSUE TITLE
Remember last used Repo

### ISSUE THREAD

**Issue by seanboothm** [mhutchie/vscode-git-graph#41]
When there are multiple repos in your workspace (We'll call them Repo1 and Repo2), when you view Git Graph, change the repo to Repo2, close git graph and reopen git graph, it switches back to Repo1. 

![git graph](https://user-images.githubusercontent.com/6071700/55184924-88734500-5150-11e9-95d8-d45b2d7e942b.gif)

**What does the bug relate to**
Graph rendering for multiple repos

**To reproduce**
Steps to reproduce the behaviour:
1. Add multiple repos to workspace
2. Open Git Graph
3. Change repo
4. Close and reopen Git Graph

**Expected behaviour**
Expected behavior is for git graph to remember last selected repo

**Environment**
 - OS: Windows 10
 - Visual Studio Code Version: 1.32.3
 - Git Graph: 1.4.3

**Comment by mhutchie** [comment]
Thanks for raising this! This will be available in the next release.

I'll change this issue to a feature request as the extension is not currently doing anything wrong, it's just that it would be nicer for it to remember the last workspace that was viewed in a multi-root workspace.

**Comment by mhutchie** [comment]
This will be available in v1.4.4.

If you'd like to use it before the next release, you can download [v1.4.4-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.4-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
