### ISSUE TITLE
Add "Fast forward" item to the popup of a non current branch

### ISSUE THREAD

**Issue by cepera-one** [mhutchie/vscode-git-graph#413]
Please add a new item to the context menu of a branch "Fast forward". It must be available event the branch is not the current HEAD.
It will perform fast forward of the branch to its tracking reference. 
Git command for this feature can be 
`git fetch origin {remoteBranchName}:{localBranchName}`

It will save many time because excluding checkout to another branch and then go back.

**Comment by mhutchie** [comment]
Hi @cepera-one,

If I'm understanding your request correctly, I believe this feature is already available when you right click on a remote branch label, and select the "Fetch into local branch..." action. It runs the Git command you specified, fast-forwarding the local branch to the remote tracking reference, within needing to check out the branch.

Please let me know if I've misunderstood your request.

**Comment by mhutchie** [comment]
Hi @cepera-one,

I'll close this feature request, as I believe the functionality you're requesting is already available in Git Graph (please read my previous response), and I haven't heard back from you.

Additionally, as I believe this functionality is already available on the remote branch context menu, I wouldn't duplicate it on the local branch context menu. It's on the remote branch context menu, as the Git command is more closely related to remote branches.

If I've misunderstood your request, and the functionality I've mentioned is different from what you're requesting, please reply with additional information to clarify your request. I'll happily re-open this feature request if this is the case.
