### ISSUE TITLE
Better merge conflicts

### ISSUE THREAD

**Issue by FDiskas** [mhutchie/vscode-git-graph#415]
Take a look at https://github.com/microsoft/vscode/issues/37350

**Comment by mhutchie** [comment]
Hi @FDiskas,

Unfortunately this functionality is outside of the scope for Git Graph, as the extension is designed to complement Visual Studio Code with additional Git related functionality, not duplicate it's built-in Git Extension. Although I understand that the linked feature request is not currently available in Visual Studio Code, and is stale, it is fundamentally an enhancement to the Visual Studio Code Git extension merge conflict tools. If I were to implement the requested feature in Git Graph (an enormous amount of work), the vast majority of the implementation would duplicate the existing merge conflict resolution capability of Visual Studio Code, and only have UX changes. This functionality, if implemented, should sit within the Visual Studio Code's Git Extension, or if Microsoft doesn't want to implement it, it should be in it's own extension.
