### ISSUE TITLE
Select / Unselect branches in the Branches Dropdown from the branch & remote branch context menu

### ISSUE THREAD

**Issue by thmatot** [mhutchie/vscode-git-graph#417]
Add "hide branch" to the menu opened by right-clicking on the branch
![image](https://user-images.githubusercontent.com/54960435/99378372-a4000600-28c7-11eb-85b3-407bfbfaaad4.png)

**Comment by mhutchie** [comment]
Hi @thmatot, Thanks for raising this improvement request.

For the purpose of my response below, I'm assuming that by "Hide Branch" you're intending that the label for the branch would be hidden (but the commits still shown in the view). Not, for it to be filtered out of the view (i.e. unchecking it in the Branches dropdown). Please clarify you're request if I've misunderstood it.

---

This request is definitely possible, and would be relatively easy to implement, however I'm hesitant to do so (for the following reasons).

Would you please clarify the use case for why users would want to hide a branch?
* If the user is hiding the branch, they lose the ability to perform all actions on it via Git Graph - why wouldn't they just delete the branch?
* If the branch is unmerged and the user doesn't want to see it, couldn't they just use the branches dropdown to filter it out of the view.
    * There's an open feature request for configuring custom glob patterns of branches to exclude that might make this easier.

Additionally, there would have to be a mechanism (likely through the Repository Settings Widget), to "unhide" specific hidden branches. _(This isn't an problem, it's also easy to do. I'm just capturing this for completeness)_

**Comment by thmatot** [comment]
I mean Hide branch will uncheck it in the branches dropdown, and if no other displayed branch have the branch commits in its own history, will remove them (commits) out of the view

**Comment by mhutchie** [comment]
Hi @thmatot,

Thanks for the clarification, I definitely agree that this would be nice to have in Git Graph!

**Comment by mhutchie** [comment]
This will be available in v1.29.0.

If you'd like to use it before the next release, you can download [v1.29.0-beta.4](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.29.0-beta.4), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by EO2875** [comment]
I am using v1.30.0, but I do not see this feature. This is what I see in the menu:
![image](https://user-images.githubusercontent.com/60835841/117934001-c0d83c00-b334-11eb-848d-af5c89b30e99.png)

**Comment by mhutchie** [comment]
Hi @EO2875,

The screenshot you provided is the commit context menu, which is opened when right clicking on a commit.

In contrast, as mentioned above, this feature was added to the branch & remote branch context menu’s, which is accessed by right clicking on a branch / remote branch label.
