### ISSUE TITLE
Show commit date as well

### ISSUE THREAD

**Issue by JM-Mendez** [mhutchie/vscode-git-graph#42]
**Describe the feature that you'd like**
A column that shows commit date rather than or adjacent to author date 

**Additional context (optional)**

When running git log without filter options, eg "--since", git will show the author date. But when using said options or using `git bisect` it will use the commit date. Yet the commit date is not necessarily the same as the author date. 

This discrepancy can manifest itself in various ways, but most commonly when rebasing branches. One situation in particular is running CI package updates and rebasing on develop to bring the current branch up to date. 

I propose adding the `%ct` placeholder to assist when running commands like git bisect or filtering commits by date. 

I'm willing to make a pull request if you'd like. Just point me on where to look.

**Comment by mhutchie** [comment]
Thanks for the feedback, this is a great suggestion!

It's a really quick change, I can add it in today.

**Comment by JM-Mendez** [comment]
Wow, you're amazing! Thank you. Yeah I personally prefer to choose myself, rather than having an extra column taking up space.

**Comment by mhutchie** [comment]
This will be available in 1.4.4, which will be released within the next day.

**Comment by cateyes99** [comment]
@mhutchie how can I show both `author date` and `commit date`? I have a commit:
```
* commit b3ddb2dc6ccdd338111205f2cee3bb204694ebbf (origin/Release_Branches/20-02-2020)
| Author:     Someone
| AuthorDate: Thu Feb 13 02:09:45 2020 +0000
| Commit:     Sometwo
| CommitDate: Wed Feb 19 13:27:17 2020 +1300
|
|     Merged PR 12850: increased callback limit from 1 to 3
|
|     Increased callback limit from 1 to 3
|
|     As agreed in meeting 31/1/2020
|
|     Related work items: #16897
```
In **Git Graph**, it only shows `author date` as `date`.
![image](https://user-images.githubusercontent.com/19678455/75308260-ddfd2800-58b2-11ea-8824-e1be74c726e7.png)

**Comment by mhutchie** [comment]
@cateyes99 I'll add this in an upcoming release, now need to raise a feature request as it’s small and easy for me to do.

**Comment by cateyes99** [comment]
> @cateyes99 I'll add this in an upcoming release, now need to raise a feature request as it’s small and easy for me to do.

Done. I've created #269.
