### ISSUE TITLE
Consider github sponsoring

### ISSUE THREAD

**Issue by marco-m** [mhutchie/vscode-git-graph#423]
hello,

did you consider to enable GitHub sponsoring? I am an happy user of vscode-git-graph and would be happy to sponsor your work.

(feel free to close this issue if no interest or similar :-)

**Comment by mhutchie** [comment]
Hi @marco-m,

Thank you for the feedback on the extension, I'm pleased to hear you're a happy user!

A few months back I looked into setting up sponsorship for Git Graph, however I didn't quite get to the position of finishing up the setup. After making some progress, I had to switch back to developing the extension (as it's my priority), and I haven't had a chance to finish setting it up. Hopefully over the upcoming holiday period I'll put aside some time to finish it.

I'll close this question, however I'll reply back once I've completed setting up sponsorship for Git Graph.

**Comment by marco-m** [comment]
Maybe a faster way is to put a PayPal (or equivalent) account on the README page ...

**Comment by mhutchie** [comment]
Hi @marco-m,

I've now finished setting up some simple sponsorship options, if you're still interested. Thanks again!

More information is provided on [Support the Git Graph extension for Visual Studio Code](https://github.com/mhutchie/vscode-git-graph/wiki/Support-the-Git-Graph-extension-for-Visual-Studio-Code).
