### ISSUE TITLE
Integrate the Commit Details View with external diff tools.

### ISSUE THREAD

**Issue by justTravis** [mhutchie/vscode-git-graph#426]
It would be great if we could simply select any two commits in the graph and get a "directory diff" done on those commits.

git difftool --dir-diff $SHA..$SHA

Where the $SHA variables there are just the commit hashes.  For example when I run that in a terminal it pops up my configured diff tool (BeyondCompare) and is a really great way to do code reviews.

Currently there is no way to select multiple commits.  When you click a commit it "pops up" the awesome little utility window for that commit.  So perhaps in that window would be an option to "Dir-Diff Against....."  which then asked you to click another commit and be done.

**Comment by mhutchie** [comment]
Hi @justTravis,

Currently when you have clicked on a commit, the Commit Details View is shown (showing you all of the changes that occurred in the commit). Additionally, when you then `CTRL/CMD` click on any another commit the Commit Comparison View is shown (showing you all of the changes that occurred between the two commits). This provides all of the Git Graph capabilities from the Commit Details View for the comparison of any two commits, including the Code Review tool. I believe this already allows you to “select multiple commits”, contrary to your statement.

Would you please clarify this, and let me know what the advantages are of a dir-diff, over the existing Commit Comparison View in Git Graph?

**Comment by justTravis** [comment]
Hello @mhutchie , and thanks for the quick response!  I didn't know about the CTRL/CMD click, so that is indeed great.

However, even with this in place, it would be even better to then be able to "click something" and get the tool to execute the diftool --dir-diff command, which would cause whatever the "registered diff tool" is to kick in.  In my case, BeyondCompare.

As great as the "code review" functionality is in your extension, this would be an awesome addition.

**Comment by mhutchie** [comment]
Hi @justTravis,

Thanks for the clarifications, I'm looking into whether it's possible to do this.

Would you please check your Git config to see whether you've set either `diff.tool` or `diff.guitool`, and let me know the configuration values? Depending on how it's set up, it may or may not be possible to do.

**Comment by justTravis** [comment]
Hello again @meierw .  Mine looks like this:

[difftool "bc3"]
	cmd = 'C:/Program Files/Beyond Compare 4/BComp.exe' \"$REMOTE\" \"$LOCAL\"
[diff]
	tool = bc3

**Comment by mhutchie** [comment]
Perfect, thank you for confirming your configuration (it means I can match yours while testing).

I'll include this new difftool integration in an upcoming release.

**Comment by justTravis** [comment]
Woo Woo!  Thanks!

**Comment by mhutchie** [comment]
This will be available in v1.29.0.

If you'd like to use it before the next release, you can download [v1.29.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.29.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by justTravis** [comment]
Hello again.  Just wondering if there is an expected timeline for releasing 1.29.0 into the wild?  Not intending to be adding pressure or trying to nudge.  Just wondering.  It will be the first time I've asked for a feature in an open source project and had that feature go live, so it's exciting for me even beyond just wanting the feature :)

 
Travis

-----Original message-----

**Comment by mhutchie** [comment]
Hi @justTravis,

Apologies for the long delay in getting this feature released. I’d originally targeted releasing Git Graph 1.29.0 on 24 Dec 2020, however unfortunately I’ve been very unwell since mid-to-late December and haven’t been able to get the release out. I do intend to release Git Graph 1.29.0 this weekend - I got the majority of my final code review and testing done last weekend, so there’s not much left to do before it can be released.

Under normal circumstances, I’ve found that a monthly release cycle works well for the extension (that’s what I aim for).

**Comment by justTravis** [comment]
Michael, I'm sorry to hear you were not feeling well.  I face that often enough myself.  I hope you are improving.  That's much more important than a release schedule.

 
Thank you for the update, and please do take care of yourself first.  We can all wait.

Travis

 
-----Original message-----
