### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bscharan** [mhutchie/vscode-git-graph#428]
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.28.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`
[mhutchie.git-graph-unresponsive.cpuprofile.txt](https://github.com/mhutchie/vscode-git-graph/files/5654816/mhutchie.git-graph-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mhutchie** [comment]
Hi @bscharan,

After reviewing the CPU profile you provided, there doesn't appear to be anything that that caused this decreased performance from the extension's perspective. Some Visual Studio Code scripts responsible for loading the extension just seemed to take abnormally long.

As I haven't had any reports of Git Graph causing high cpu load in the last 11 months, I'm inclined to believe this was a one-time module loading anomaly (likely hardware induced), and not a recurring issue with Git Graph that I need to resolve. I'll close this issue for this reason.

However, if you've received this multiple times please provide additional cpu profiles so I can attempt to see what the common problem is.
