### ISSUE TITLE
Highlight HEAD commit some more

### ISSUE THREAD

**Issue by borekb** [mhutchie/vscode-git-graph#43]
I use the "Branch: Show All" mode most of the time in which it's not always easy to identify the `HEAD` commit – it's just a slightly different dot in the graph. Maybe use some kind of marker or a different background or both together, I'm not sure, but it would be great if I could tell what commit I'm on immediately.

**Comment by mhutchie** [comment]
Thanks for the suggestion, it would definitely be better if the head commit was more obvious (other than the different node on the graph)! I'll have a think about what might be the best way to achieve this.

**Comment by mhutchie** [comment]
This will be available in v1.4.5, which I intend to release in the next day.

If you'd like to use it before the next release, you can download [v1.4.5-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.5-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
