### ISSUE TITLE
Add remote info in tag if pushed

### ISSUE THREAD

**Issue by thmatot** [mhutchie/vscode-git-graph#430]
It would be nice to add remote information on tag label when it is pushed on one or severals remotes, as for branch with upstream

**Comment by mhutchie** [comment]
Hi @thmatot,

Although this would be nice to have, unfortunately Git doesn’t record this information in your local version of the repository, so there is no way of efficiently knowing which remotes have which tags, unlike branches.

Locally, the following information is stored for the repository:
* `refs/heads`: Local Branches
* `refs/remotes`: Remote Branches
* `refs/tags`: Local Tags

Although there is a Git command that can query a remote for all tags on it, this is slow as it has to query the remote each time as the information isn’t stored locally, and needs to be called individually for each remote of the repository. It would be a significant amount of work to add a custom background fetching & caching mechanism for remote tags in Git Graph.

I’ll close this request for now, as I’m not aware of a feasible way to achieve this. I’d looked into this over a year ago, as it seemed like a natural type of information to display in the Git Graph View, and was surprised to discover the above information. If anyone is aware of a feasible method to achieve this, please reply to this thread (I’m definitely open to implementing this in some form if a feasible solution was proposed).
