### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by IJlima** [mhutchie/vscode-git-graph#435]
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.28.0`
- OS Version: `Linux x64 5.4.0-56-generic`
- VSCode version: `1.52.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/mhutchie.git-graph-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mhutchie** [comment]
HI @IJlima,

You haven't provided the CPU profile highlighted by the yellow exclamation emoji's in the template you used, this makes it impossible to investigate this further. All I know from the information you've provided that the extension was slow to start once, for one user, and have no context to know what could have possibly caused it.

I've only had occasional reports of Git Graph causing high cpu load (two this year), so I'm inclined to believe this was a one-time module loading anomaly (likely hardware induced), and not a recurring issue with Git Graph that I need to resolve. I'll close this issue for this reason.

However, if you've received this multiple times please provide additional cpu profiles so I can attempt to see what the common problem is.
