### ISSUE TITLE
Retain sort status

### ISSUE THREAD

**Issue by BrendanSimon** [mhutchie/vscode-git-graph#437]
I use "Sort by status" in the source control `...` menu.

However this is not the default and when I relaunch vscode my previous selection is not retained.

Is there a way to set the default sort criteria and/or for git-graph to retain the last selected value?

If not, please consider this a feature request ;-)

**Comment by BrendanSimon** [comment]
Actually this is probably built-in Source Control issue, rather than vscode-git-graph.  Sorry about that !!

**Comment by mhutchie** [comment]
Hi @BrendanSimon,

You're correct that this functionality (and the entire Source Control View) is provided by the built-in Visual Studio Code Git Extension. After having a quick look, I couldn't see any existing Visual Studio Code settings that would allow you to save your View & Sort preferences for the Source Control View.

As the Source Control View is from the built-in Git Extension, any feature requests would have to raised in the Visual Studio Code GitHub repository https://github.com/microsoft/vscode.
