### ISSUE TITLE
Review file changes in a more convenient manner

### ISSUE THREAD

**Issue by bvandevliet** [mhutchie/vscode-git-graph#438]
Now, when one commit or two commits are selected, the commit unfolds and changed files are shown within that drop-down area. It would be nice if these where shown on the left vscode panel, in the area where also changed files are shown before they are committed. This would be a more similar experience like in Visual Studio IDE and it keeps the changed files visible when reviewing the actual diffs in the editor.

**Comment by mhutchie** [comment]
Hi @bvandevliet,

Thank you for raising this feature request!

I definitely would like to incorporate this capability into Git Graph, and explore various other opportunities to leverage other regions of the Visual Studio Code interface to improve various workflows of users. I've received multiple feature requests in the past to expand outside of the current Git Graph View (mainly to the Side Bar) for similar reasons #170 & #229.

Up until a few months ago, Visual Studio Code didn't provide a workable solution for extensions to achieve this type of rich integration outside of the current [Webview](https://code.visualstudio.com/api/extension-guides/webview). However, Microsoft have recently been greatly expanding the ability for extensions to contribute rich views throughout Visual Studio Code, enabling this to now be possible. Please see my previous comment here https://github.com/mhutchie/vscode-git-graph/issues/170#issuecomment-690771740, to understand why I'm currently holding off on implementing this collection of Side Bar feature requests. I'll move this request temporarily to the backlog for the linked reason, however I'm definitely intending to re-open and implement it once user compatibility allows.
