### ISSUE TITLE
missing rendered "merge line" of graph when 4 parallel branches are shown, see the picture

### ISSUE THREAD

**Issue by flyingmoro** [mhutchie/vscode-git-graph#439]
**Describe the Bug**
A part of the drawn graph is missing, this was a bit confusing, because it looked like a somehow dangling branch.

**Expected Behaviour**
Line from source to target branch for this merge should be drawn.

**Environment**
 - Git Graph Extension Version: 1.28.0
 - Visual Studio Code Version: 1.52.1
 - Operating System: Ubuntu

**Screenshots (optional)**
Develop is shown in blue:  
![GraphMissingLine](https://user-images.githubusercontent.com/8232833/102481400-f61c7e80-4061-11eb-8b76-89fa47776dc4.PNG)  

If merge commit is selected, the line is drawn correctly:
![GraphShowingLine](https://user-images.githubusercontent.com/8232833/102481409-f9176f00-4061-11eb-8e65-67b61b45bb4b.PNG)

Very nice tool anyway!!

**Comment by mhutchie** [comment]
Hi @flyingmoro,

Zooming into your first screenshot, you can actually still see a slight hint of the blue line that you say is "missing" on either side of the green and orange lines. It just so happens that with this exact combination of lines that the blue line is hidden by the other lines in the graph.

![image](https://user-images.githubusercontent.com/5315753/102483116-635afe80-40b8-11eb-8653-14539124b56f.png)

There isn't really a way to avoid this, as the lines have to connect in specific places, and have to be connected in some way (naturally leading to some inevitable overlaps of some lines).

If this is a problem for you, I'd recommend you try setting the extension setting [git-graph.graph.style](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#style) to `angular` (this setting changes the style of the graph from smooth curves to sharp angular lines). From my own testing, it lays out the lines such that the blue line is visible:

| "rounded" | "angular" |
|--|--|
| ![image](https://user-images.githubusercontent.com/5315753/102484329-327bc900-40ba-11eb-817b-6be81f635861.png) | ![image](https://user-images.githubusercontent.com/5315753/102484535-8686ad80-40ba-11eb-8f23-e32ed147c435.png) |
| ![image](https://user-images.githubusercontent.com/5315753/102484612-a027f500-40ba-11eb-99f0-fc70c63fd324.png) | ![image](https://user-images.githubusercontent.com/5315753/102484485-753da100-40ba-11eb-8e67-eb2f4ded418a.png) |

I'll close this issue, as the line is being rendered, it's just mostly hidden by other lines shown in the graph - which is unavoidable in some cases, and there is already an alternative graph style that better renders the line.

**Comment by flyingmoro** [comment]
Hi @mhutchie,
thanks for your answer. Now i understand the problem, thanks for explaining this. 

I thought about how this might be solved and made the following drawing, that shows four different alternatives, that at least solve the problem in this special case here.  
In all variations, the z-index of the lines of branches beeing more to the left, is always higher than the ones more to the right and i belive, that it should be assured, that in all cases, you always would see a small part of the crossing curve.  
If you want to stick to your logic drawing those curves, the problem might be solved, if you draw the curve starting always at the oldest possible commit as shown in the leftest version.

And thanks for pointing me to the option to change to the angular view!
And i really would not call this a "problem" at all, more a very small disfigurement :) Using your tool, really helps a lot already while doing my daily work!

![Graphs](https://user-images.githubusercontent.com/8232833/102723930-17a09300-430c-11eb-9904-12600e4361d6.png)

**Comment by mhutchie** [comment]
Hi @flyingmoro, I'm glad to here that my explanation clarified what is going on, and that the extension helps you doing your work!

I definitely agree that some of the suggestions you've provided would improve the graph.

The graph layout & rendering algorithm in the extension has the following priorities (1 - highest priority, 3 - lowest priority):
1. All commits, branches, merges & branching must be shown correctly (i.e. does the graph correctly represent what occurred in the repository, based on all the information Git contains).
2. It must be laid out and rendered highly efficiently - Git repositories can get extremely large over time (especially for the business users who make up the majority of extension users), so the algorithm must be capable of rendering hundreds to thousands of commits and 10+ branches in parallel almost instantly (from the users perspective). The current algorithm I designed and implemented is extremely efficient as a two-pass algorithm (one pass lays out the graph, and a second pass renders it). Any algorithms that require back-tracking, or have exponential complexity, are essentially ruled out.
3. Render the graph in the best way possible (all improvements go here).

The challenge is that the majority of graph improvements, like the ones you've suggested, instinctively appear easy at first glance, however often when going into all the details, possible cases, and implementing them, they become much harder to implement in a reasonably efficient manner. In the past when occasional graph rendering improvements have been raised, they typically fall into three categories: _(your suggestions fall into the second and third categories from my initial analysis)_
* They're quick & easy to do, with low risk. I always implement these, as I want to keep improving the graph.
* They're extremely complicated & time consuming to do efficiently, with high risk. I rarely do these, just from a feature prioritisation perspective, as often it takes too much time for too little benefit, compared to implementing new capabilities to the extension that far more users will appreciate and value.
* There is no efficient algorithm that myself, or the requestor, could come up with to achieve them.

In saying that, I'll definitely keep this scenario in mind when I make ongoing improvements to the graph, to see if this scenario can be better handled.
