### ISSUE TITLE
Unaesthetic display of error message during push onto remote

### ISSUE THREAD

**Issue by AlexVillarra** [mhutchie/vscode-git-graph#448]
I've noticed before that upon encountering an error whilst pushing onto a remote, the error message displayed in the box is broken into many lines with "remote:" repeated every newline (see example screenshot below).
Although this does not affect functionality at all, and is more of an aesthetic problem, I was wondering if it would be possible to display the whole error message (not breaking it into multiple newlines) and without the repeating "remote:".

![Screenshot 2021-01-08 094857](https://user-images.githubusercontent.com/50244793/103995660-150dbc80-5199-11eb-987d-a20f81efdc9c.jpg)

**Comment by mhutchie** [comment]
Hi @AlexVillarra,

Git Graph displays the error messages produced by the underlying Git command that was run. This is for the following reasons:
* Git error messages are available in most common languages, which allows non-English speaking users to better understand the details of the error. This potentially means that parsing error messages may only work for English users (which is a minority of the extensions users). Currently all text in Git Graph is in English, so I try to leverage Git's multi-language support as much as possible.
* The designers of Git chose to write the error messages in a particular way (often for a specific reason).
    * Any improvements to the error messages should be made in Git, so all Git users benefit from the same improvements, regardless of how they consume Git (e.g. via the command line, or various Git UI's).
* Git error messages are not designed to be machine-read (i.e. they're written for users, not for other software to parse and alter). This means that these error messages can be reworded or reformatted over time, making parsing inconsistent and possibly incorrect for some past or future versions of Git.
    * Throughout Git Graph, I only parse Git output that is designed to be machine-readable, as it guarantees consistency for all users, regardless of which language, version of Git, or platform they use.

Although it's clear in your example that the current error message produced by Git could be better formatted, and it would be relatively easy to implement a solution to achieve this, I have to maintain consistency in my position that the extension simply displays error messages produced by Git (for all of the reasons I mentioned above). I'll therefore close this improvement request. Additionally, it's not fair for me to make exceptions for specific cases - if I improve one error message, I'll receive requests to improve many other Git error messages (which may be more complex & time consuming).
