### ISSUE TITLE
Show commits with only tags

### ISSUE THREAD

**Issue by morganlombard** [mhutchie/vscode-git-graph#45]
**Describe the feature that you'd like**
Show commits in the graph that is referenced by a tag only

**Additional context (optional)**
When looking at the graph with 'Show All' selected I could not see **commits** that are only **referenced** by **tags**. (head of commits is a tag only, no branch). When using 'gitk --all' I could see the tags.

**Comment by mhutchie** [comment]
Thanks for this suggestion, I'll add this in the next release.

**Comment by mhutchie** [comment]
This will be available in v1.4.5.

If you'd like to use it before the next release, you can download [v1.4.5-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.5-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
