### ISSUE TITLE
Git Graph icon disappeared

### ISSUE THREAD

**Issue by oo6** [mhutchie/vscode-git-graph#456]
**Describe the Bug**
When I upgrade to the latest beta version of vscode, the icon disappeared in the source control panel.
I opened the developer tool, and I can see it is missing `codicon` class from other icons. if I add `codicon` class, it will be shown.

I am not sure this is a plugin or vscode problem.
Thanks.

**Steps to Reproduce**
1. Hover the source control panel

**Expected Behaviour**
Show git graph icon

**Environment**
 - Git Graph Extension Version: [1.28.0]
 - Visual Studio Code Version: [1.53.0-insider, commit: 7b0cfdd04ad530a9c8d782c618afd79290be3d64]
 - Operating System: [macOS Big Sur]

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/6327995/106100699-be801680-6177-11eb-86dc-6df92e07776b.png)

**Comment by mhutchie** [comment]
Hi @oo6,

Visual Studio Code extensions register actions for the Source Control View Title Menu in the [extension manifest](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) (e.g. Git Graph does it [here](https://github.com/mhutchie/vscode-git-graph/blob/e513fc7f995e4840193a57817351344b2fc5a539/package.json#L1405-L1416)), and provide paths to the icons for the underlying commands also in the [extension manifest](https://code.visualstudio.com/api/references/contribution-points#contributes.commands) (e.g. Git Graph does it [here](https://github.com/mhutchie/vscode-git-graph/blob/e513fc7f995e4840193a57817351344b2fc5a539/package.json#L49-L50)). It is Visual Studio Code's responsibility to ensure the menu items defined by extensions are displayed correctly in Visual Studio Code - no extension has any control over this.

As this is a bug with Visual Studio Code itself, not the extension, please raise this as a bug with Microsoft in the [vscode](https://github.com/microsoft/vscode) repository, so they can fix it before this bug makes it into the next full Visual Studio Code release.

**Comment by mhutchie** [comment]
I've just installed the latest Visual Studio Code 1.53.0 Insiders release, and the Git Graph menu item appears correctly. Please try installing the latest insiders release to see if Microsoft has already fixed this issue.

Version: 1.53.0-insider (user setup)
Commit: f73c011ae3f8df0aa4ba144cdee221e2e8690373
Date: 2021-01-28T06:16:16.520Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

![image](https://user-images.githubusercontent.com/5315753/106107389-fc426680-619a-11eb-9e3b-8223cd954707.png)
