### ISSUE TITLE
Git graph and code commit do not share the same tab on the newest vscode release

### ISSUE THREAD

**Issue by Med-H** [mhutchie/vscode-git-graph#459]
**Describe the Bug**
Git graph and code commit do not share the same tab on the newest vscode release.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. update to latest vs code 1.53.0 

**Expected Behaviour**
git graph and code commit should share the same tab

**Environment**
 - Visual Studio Code Version: [e.g. 1.53.0]
 - Operating System: [e.g. Windows 10]

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/74670211/107118031-9d59ad00-687e-11eb-9fb2-32c47066153f.png)

as shown in the screenshot, there are two same icons one for git graph and one for source control . they used to be one button for both of them.

**Comment by mhutchie** [comment]
Hi @Med-H,

The extension doesn't contribute any "tab" to the Visual Studio Code Activity Bar, or the Visual Studio Code Source Control View.

The extension only contributes a single menu item to the Source Control Title menu, see the arrow in the screenshot below (which uses the Git Graph icon).

![image](https://user-images.githubusercontent.com/5315753/107130333-591ee900-6920-11eb-84c7-bfa076c3bbf8.png)

The extension does not contribute anything to Visual Studio Code with the icon you show, so I don't see any way that the duplicate icon could be anything to do with Git Graph. I'm also unable to observe the duplicate menu items in the Visual Studio Code Activity Bar (using Visual Studio Code 1.53.0 & Windows 10).

Why do you think the duplicate icon is anything to do with Git Graph?

FYI: The only way I can observe duplicates of the Source Control icon in the Activity Bar is if I drag and drop the Source Control section header from the Source Control View to the Activity Bar - but again, this has nothing to do with Git Graph. This can also easily be reversed.

I'll close this for now as I think it's completely unrelated to Git Graph. Additionally, if the change of behaviour was introduced in Visual Studio Code 1.53.0, it would almost certainly be a bug in vscode itself (in which case it should be raised with Microsoft, not this extension).

**Comment by Med-H** [comment]
on fresh install the problem does not happen, but i wanted to clarify the problem, just in case someone else have it.
this is how it should looke like

![image](https://user-images.githubusercontent.com/74670211/107612828-65b87f80-6c47-11eb-8e67-e329b4fb9fcb.png)

but when updating from a previous version to the newest one, the icons are duplicated 
![image](https://user-images.githubusercontent.com/74670211/107612957-a9ab8480-6c47-11eb-836c-a1107c9dd46a.png)

**Comment by MichaelJGW** [comment]
# Issue is from VS-Code not the plugin

## Resolution 
Drag and drop the section back in.

![vscode-multiple-source-control (4)](https://user-images.githubusercontent.com/2390194/167009423-933dbdc6-65b6-4eb3-a76b-ce26da164460.gif)
