### ISSUE TITLE
Integration with VS Code's "timeline" view

### ISSUE THREAD

**Issue by ilyagr** [mhutchie/vscode-git-graph#463]
It would be very nice if VS Code's "Timeline" view of a file (in the Explorer pane on the left, pictured below) had a button to jump to the corresponding commit in Git Graph, similar to the button Git Graph adds in the Git pane.

![Screenshot 2021-02-15 8 15 47 PM](https://user-images.githubusercontent.com/4123047/108017798-a22f0700-6fca-11eb-81b7-e0e253681a3f.png)

Conversely, it would be nice if clicking on a file in Git Graph (in the screen pictured below) brought me to VS Code's native Timeline view of that file at that commit.

![Screenshot 2021-02-15 8 20 19 PM](https://user-images.githubusercontent.com/4123047/108017991-4a44d000-6fcb-11eb-9a17-1f9b205ba978.png)

**Comment by mhutchie** [comment]
Hi @ilyagr,

This would be a really nice integration between Visual Studio Code and Git Graph, and would definitely streamline the user experience!

Extensions can register a command to be displayed when right-clicking on a TimelineItem, and the registered command is called with two arguments:
* TimelineItem (which includes the commit hash)
* URI - The file being displayed in the Timeline View

The TimelineItem argument is still only in the "Proposed" state, and not yet released in the Visual Studio Code API that extensions use to integrate with Visual Studio Code. While it's in the "Proposed" state, it could change at any time, and cause breaking changes for any extensions that consume it. The delivery of the class is being tracked in https://github.com/microsoft/vscode/issues/84297.

I'll close this feature request for now, and move it to the backlog. However, once TimelineItem has been included in the Visual Studio Code API for extensions to use, I'll definitely re-open this feature request and implement it.

**Comment by ilyagr** [comment]
Thank you for the detailed reply. 

Thank you also for the wonderful extension! The combination of Git Graph and VS Code's terminal makes for an excellent Git experience.
