### ISSUE TITLE
Copy File Path to the Clipboard (Relative)

### ISSUE THREAD

**Issue by edridgedsouza** [mhutchie/vscode-git-graph#466]
When examining a given commit, sometimes you'll want to use the command line to run `git show REVISION:path/to/file`. Currently, it's easy to copy the full commit hash to the terminal for this purpose. However, if you click the button for "Copy File Path to the Clipboard" within a given commit, it gives the absolute path rather than the relative path for the repository, which is what `git show` expects. This is relatively minor, and you can get this from the file tree anyway with some effort, but an extra option to copy the relative path in addition to the file path would be convenient since it'd be right in the git graph window next to the revisions you care about.

Providing examples for a Jupyter notebook, which I wanted to inspect in my terminal since "View File at this Revision" kept trying to run the VSCode jupyter extension (which isn't working for past revisions apparently) instead of opening it as plaintext.

![image](https://user-images.githubusercontent.com/19752149/108787819-884e7080-7544-11eb-8c51-094ebaf647f7.png)
![image](https://user-images.githubusercontent.com/19752149/108787857-a2884e80-7544-11eb-854a-04ae5ff0b364.png)
![image](https://user-images.githubusercontent.com/19752149/108787984-fa26ba00-7544-11eb-9c81-a47d14080cbf.png)
![image](https://user-images.githubusercontent.com/19752149/108788043-1aef0f80-7545-11eb-9730-9a3925d92027.png)

**Comment by mhutchie** [comment]
Hi @edridgedsouza,

Thanks for raising this feature request, it would definitely be useful to have the option to copy the relative path of a file, in addition to the absolute path!

I'll include this in an upcoming release of Git Graph.

**Comment by mhutchie** [comment]
This will be available in v1.30.0.

If you'd like to use it before the next release, you can download [v1.30.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.30.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by mhutchie** [comment]
I've added the option to the right-click context menu for files in the Commit Details / Comparison Views:
![image](https://user-images.githubusercontent.com/5315753/109795752-7159fd80-7c6b-11eb-8885-eed0f5bc9a84.png)
