### ISSUE TITLE
Automatically replace disallowed characters with allowed characters in create branch form field

### ISSUE THREAD

**Issue by griest024** [mhutchie/vscode-git-graph#471]
**Describe the feature that you'd like**
When typing the name of the branch in the create branch dialog form field, I would like an allowed character (e.g. hyphen: `-`) to be automatically substituted in when I type a disallowed character (e.g. space: ` `).

**Additional context (optional)**
The inserted character should probably be configurable as I imagine some people would prefer `_` over `-`.

**Comment by mhutchie** [comment]
Hi @griest024,

Thanks for raising this feature request, it would definitely be nice to have in Git Graph!

It seems like the space substitution you mentioned as an example would be the most useful.

There are numerous other disallowed characters that I don’t think there is a natural substitution for (e.g. `~`, `^`, `:`, `?`, `*`, `[`). I’ll have a think about how these should be substituted (if at all). Let me know if you have any ideas.

**Comment by griest024** [comment]
> There are numerous other disallowed characters that I don’t think there is a natural substitution for (e.g. ~, ^, :, ?, *, [). I’ll have a think about how these should be substituted (if at all). Let me know if you have any ideas.

I think at the very least the form field should not allow those characters to be inserted into the branch name string. You could add a config option for each one of those characters but that seems cumbersome and most likely YAGNI.

I say for now just add an option to configure the space replacement character. I would be willing to submit a PR; let me dig into the codebase a little and I'll get back to you.

**Comment by mhutchie** [comment]
Hi @griest024,

I agree that for now let's focus on the space replacement in all reference dialog inputs.

This is actually really quick and easy for me to do - I'm doing a beta release in around 9 hours, so I'm happy to implement it so it can be included in it.

**Comment by griest024** [comment]
@mhutchie okay go for it, don't let me hold you up

**Comment by mhutchie** [comment]
Automatic space substitution on reference inputs on dialogs will be available in v1.30.0.

The new extension setting `git-graph.dialog.general.referenceInputSpaceSubstitution` lets the user choose between "None", "Hyphen" & "Underscore". Currently it is set to "None" by default, so users must set their preference before any substitution is performed. In the future we can reconsider the default value of this setting, if this receives positive user feedback.

If you'd like to use / test it before the next release, you can download [v1.30.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.30.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
