### ISSUE TITLE
New Repository Dropdown Order option that follows the order of multi-root workspace folder

### ISSUE THREAD

**Issue by jsg2021** [mhutchie/vscode-git-graph#479]
I have a large multi-root workspace. I frequently interact with the select box to switch between. It would be nice to make it more keyboard friendly such as:
- auto focus input on open
- arrow select/enter confirm
- sort options to match explorer

**Comment by mhutchie** [comment]
Hi @jsg2021,

Thanks for raising this feature request!

> - auto focus input on open

Unfortunately this is not feasible to do. Quite a number of users requested that the table of commits be focused on initial load, as it allows them to easily scroll through the commits using keyboard shortcuts (up/down arrows, home/end, page up/down). Also, the portion of users with many repositories in their workspace is definitely the minority, so always focusing on the Repo Dropdown (only visible when multiple repositories exist) on load would only benefit a smaller portion of users, and be a detriment to everyone else.

> - arrow select/enter confirm

This is definitely something I want to implement (and have been meaning to for some time). Originally neither the dropdowns (used for the Repo and Branches Dropdowns on the Git Graph View Control Bar), or the select inputs on dialogs, supported keyboard navigation. Last year I updated the select input implementation on dialogs to be keyboard friendly - I definitely want to update the dropdown implementation to match!

> - sort options to match explorer

The extension setting [Repository Dropdown Order](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#repository-dropdown-order), allows the users to customise their preferred order for the Repo Dropdown. There are two options, either sorting by the full path of the repository (which should match the Visual Studio Code Explorer View), or sorting just by the name of the repository. Would you please provide an example where the dropdown's order differs from the explorer, so I can work out why they aren't matching? (what value have you set for `explorer.sortOrder`)

**Comment by jsg2021** [comment]
> Hi @jsg2021,
> 
> 
> 
> Thanks for raising this feature request!
> 
> 
> 
> > - auto focus input on open
> 
> 
> 
> Unfortunately this is not feasible to do. Quite a number of users requested that the table of commits be focused on initial load, as it allows them to easily scroll through the commits using keyboard shortcuts (up/down arrows, home/end, page up/down). Also, the portion of users with many repositories in their workspace is definitely the minority, so always focusing on the Repo Dropdown (only visible when multiple repositories exist) on load would only benefit a smaller portion of users, and be a detriment to everyone else.
> 
I'm sorry, I jotted the idea down incompletely. I meant to auto focus the input on opening the drop down not the main view. 😊 

> 
> 
> > - arrow select/enter confirm
> 
> 
> 
> This is definitely something I want to implement (and have been meaning to for some time). Originally neither the dropdowns (used for the Repo and Branches Dropdowns on the Git Graph View Control Bar), or the select inputs on dialogs, supported keyboard navigation. Last year I updated the select input implementation on dialogs to be keyboard friendly - I definitely want to update the dropdown implementation to match!
> 
> 

awesome 😊 

> 
> > - sort options to match explorer
> 
> 
> 
> The extension setting [Repository Dropdown Order](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#repository-dropdown-order), allows the users to customise their preferred order for the Repo Dropdown. There are two options, either sorting by the full path of the repository (which should match the Visual Studio Code Explorer View), or sorting just by the name of the repository. Would you please provide an example where the dropdown's order differs from the explorer, so I can work out why they aren't matching? (what value have you set for `explorer.sortOrder`)

I believe it's the default value. I will confirm in the morning. I believe it's sorting by full path. 

With multi root workspaces you can order your projects how ever you want. Having an option to mirror that order would be nice. Most of mine are alphabetical. However I keep a few hot spots at the top.

**Comment by mhutchie** [comment]
Your first point is definitely something I'd like to do, thanks for the clarification!

I just experimented with your third point before your comment came through, and in multi-root workspaces the order of the roots can be set by the user (not necessarily the alphabetical order of full file paths) - as you also now mentioned. I'll work out how to support this as a new option for Repository Dropdown Order, and make it the default. I wasn't aware of this nuance in Visual Studio Code's ordering 😄 .

**Comment by jsg2021** [comment]
thank you 😊

**Comment by mhutchie** [comment]
I've decided to split this improvement request into two, so they can be delivered independently. This improvement request now only refers to (1).
1. New Repository Dropdown Order option that follows the order of multi-root workspace folder (the new default order) - you're third point.
2. Allow Repository & Branches Dropdown's to be navigated via keyboard - you're first & second points.

---

This will be available in v1.30.0.

If you'd like to use it before the next release, you can download [v1.30.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.30.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by jsg2021** [comment]
This is awesome 😊 thank you!
