### ISSUE TITLE
Show Stashes

### ISSUE THREAD

**Issue by morganlombard** [mhutchie/vscode-git-graph#48]
**Describe the feature that you'd like**
It would be nice to to be able to see stashes in the graph, it could be selectable like with "Show Remote Branches"

**Additional context (optional)**
Like when using
git log --oneline --graph --decorate --all $(git reflog show --format="%h" stash)
or
gitk --all

**Comment by mhutchie** [comment]
Thanks for this suggestion, I’ll add support for showing stashes, and possibly some related actions as well!

**Comment by mhutchie** [comment]
Thanks everyone that has expressed interest for stash integration in Git Graph, and your patience for this to be implemented. This is scheduled for the next release, which will be available in 1 - 2 weeks.

My intentions for the MVP of stash integration are:
* Show stashes equivalent to how commits appear.
* Support for the Commit Details & Comparison Views.
* Right Click Context Menu Actions:
    * Apply Stash
    * Create Branch from Stash
    * Drop Stash

This can be expanded in future releases to include additional integrations.

**Comment by mhutchie** [comment]
This will be available in v1.15.0, which will be released within the next day. I've implemented:
* Show Stashes on the Git Graph View.
* Stash Context Menu:
    * Apply Stash...
    * Create Branch from Stash...
    * Drop Stash...
    * Copy Stash Name to Clipboard
    * Copy Stash Hash to Clipboard
* New "Stash uncommitted changes..." action on the Uncommitted Changes Context Menu.
* Commit Details & Comparison View support for Stashes.

**Comment by borekb** [comment]
Wow, stashes are awesome! I commonly use `pop` instead of `apply` (so that I don't have to remember clearing them up) but it's already an excellent feature, thank you!

**Comment by mhutchie** [comment]
@borekb Thanks for the feedback! I've just added a "Pop..." action on the Stash Context Menu. This will be available in v1.16.0.

If you'd like to use it before the next release, you can download [v1.16.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.16.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
