### ISSUE TITLE
Add "Mark as Un/reviewed" options to files in code review mode

### ISSUE THREAD

**Issue by dan1994** [mhutchie/vscode-git-graph#482]
Add two new actions to Commit Details View File Context Menu (https://github.com/mhutchie/vscode-git-graph/blob/ad1ba5c16bf3982337df7982451ec9ea5942ab6c/web/main.ts#L2926-L2958):

Mark as Reviewed: Remove the file from the array of files remaining to be reviewed, and unbold it. This would appear when a Code Review is active, and the file isn't reviewed.
Mark as Unreviewed: Add the file back into the array of files remaining to be reviewed, and bold it. This would appear when a Code Review is active, and the file is reviewed.

**Comment by dan1994** [comment]
@mhutchie Please assign to me

**Comment by mhutchie** [comment]
This will be available in v1.30.0.

If you'd like to use it before the next release, you can download [v1.30.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.30.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
