### ISSUE TITLE
Support more context menu actions for branches

### ISSUE THREAD

**Issue by jdiamond** [mhutchie/vscode-git-graph#485]
I'm trying to add the Reset and Copy Hash actions to the context menu for branches with this in my settings.json:

```
  "git-graph.contextMenuActionsVisibility": {
    "remoteBranch": {
      "reset": true,
      "copyHash": true
    }
  }
```

Based on the definition I see [here](https://github.com/mhutchie/vscode-git-graph/blob/245863645afcdbf5fd6f0fb851dca4dbfdba2045/src/types.ts#L361), I think these options aren't supported.

Is it possible to support these options for both branch and remoteBranch context menus?

**Comment by mhutchie** [comment]
Hi @jdiamond,

You're correct that these options aren't available on local or remote branches.

For "reset": Would you please clarify what behaviour you're expecting for this "reset" action do (in the context of branches)? (At the moment the reset action only resets the current branch to a specific commit / HEAD)

For "copyHash": I currently don't have it on the local or remote branch context menu's, as it's available on the commit context menu (which is just as easy, if not easier, to access). I have to be really careful about keeping the context menu's as small as feasibly possible, so users with smaller resolution displays (e.g. laptops) can see all of the available actions without scrolling. While I don't mind adding actions if they offer additional Git capabilities, when the action as already available (like it is in this case) on another context menu I'd prefer to avoid duplicating it. Although the remote branch context menu has plenty of capacity, the local branch context menu is almost full, so I'd prefer to leave what little space is remaining for additional Git capabilities.

**Comment by jdiamond** [comment]
For "reset", I'm hoping for the same behavior as when I right-click on a commit: it pops up a dialog asking if I want mixed or hard. I'm coming from SourceTree where I could reset by clicking on the branch label just like I could on the rest of the line and I keep surprising myself in GitGraph when I right-click on the branch label and don't see it (because in my head I'm thinking I need to reset back to origin/main or whatever so I click where it says the branch name).

For "copyHash", it's the same thing. I want to copy the hash of the commit a branch is currently set to so I click on the branch and don't see the action. In SourceTree, it didn't make that distinction and let you copy the hash no matter where you clicked.

The workaround for both of these is really easy: I just move my pointer to the right and right-click again. I stopped using SourceTree several months ago in favor of GitGraph, but I still do this several times a week and thought I would finally fix it so I didn't have to think about it anymore. I assumed these actions were just disabled by default and I could enable only for myself.

I understand wanting to keep the menus small as I'm always working on a laptop, too. At the resolution I'm using, there's still lots of room but I am getting older and might be reducing my resolution soon. 😢

**Comment by mhutchie** [comment]
Hi @jdiamond,

Thank you for making those clarifications!

Unlike SourceTree and other stand-alone Git UI applications (that have the full screen resolution of the user's device to render UI), Git Graph has to work within just a portion of Visual Studio Code. This means there isn't room to have a dedicated list of branches to the side of the main commit view. Consequently, the only place that branch actions can be made available is on the labels themselves, forcing me to make the branch and commit context menu's independent (to fit the wide range of available actions).

Even though it would (no doubt) be convenient to duplicate some actions across different context menu's, it ultimately just removes space that could be better used of for other dedicated actions (determined by what the user is right-clicking on).

Although implementing some duplicate context menu actions (disabled by default) would be possible, ultimately it just means that only a very small portion of users would get value from the time cost of implementing them (which could be better spent implementing features that many more users would value). It also just bloats the codebase with code that is unused by the majority of users.

Ultimately I think that avoiding duplication is the right decision to make, given the circumstances that the extension must operate within. Hence, I'll close this feature request.

---

FYI: Based on the use case you mentioned for the reset action, it may be possible for you to use the "Fetch into local branch..." action on the Remote Branch context menu (and chose "Force Fetch"). This will reset the local branch to be at the same commit as the remote branch. This is available as long as the local branch isn't checked out.

**Comment by Scorg** [comment]
> Ultimately I think that avoiding duplication is the right decision to make, given the circumstances that the extension must operate within. Hence, I'll close this feature request.

Well that is as cheap as an excuse can be. Holy crap. You are pretty much telling people to suck up a pretty significant inconvenience for the sake of catering to tables-size screen users. If you are so desperate to minimize the number of items, you can make this an option.

And interface duplication is in no way the same as code duplication. Useful interfaces don't get in the way of workflow for the sake of some subjective ideological extremes.
