### ISSUE TITLE
Enable "Git Graph: File Encoding" Extension Setting to be "files.associations" Scoped

### ISSUE THREAD

**Issue by hkcomori** [mhutchie/vscode-git-graph#489]
My project has a different encoding for each extension.
The diff view of Git Graph wrong files encoding in any files which are encoded by Shift-JIS.

- VSCode Version 1.54.3
- Git Graph Version 1.29.0
- Windows 10 Pro x64 Version 1909

Steps to Reproduce:

1. Setup workspace settings according to this:
```json
{
    "files.associations": {
        "*.c": "c",
        "*.h": "c",
        "*.mtpj": "xml",
    },
    "[c]": {
        "files.encoding": "shiftjis",
        "git-graph.fileEncoding": "SHIFT_JIS",
    },
    "[xml]": {
        "files.encoding": "utf8",
        "git-graph.fileEncoding": "UTF-8",
    },
}
```

2. Initialize a git repository
3. Create "*.c" files which are encoded by Shift-JIS
3. Create "*.mtpj" files which are encoded by UTF-8
4. Open the diff of the created file in Git Graph
5. The file eonciding of the diff view is always UTF-8

**Comment by mhutchie** [comment]
Hi @hkcomori,

Thanks for raising this feature request, it would be really nice to have in Git Graph!

Currently `git-graph.fileEncoding` is `resource` scoped, so it can be set at the user, workspace, and folder level (of the repository).

In order for `git-graph.fileEncoding` to be `language-overridable` scoped, it requires that the minimum version of Visual Studio Code that Git Graph supports is 1.42.0 (as this is when this scope was added to Visual Studio Code). Currently the minimum version of Visual Studio Code that Git Graph supports is 1.38.0. Unfortunately, at the current time I’m not able to increase this minimum version requirement to 1.42.0, as too many users are using 1.38.x - 1.41.x, and there is not enough value added by this feature request to offset this. If I were to upgrade the minimum version requirement of the extension, all of these users would never receive any more Git Graph updates (unless they update Visual Studio Code).

I’ll close this feature request for now, and move it to the backlog for the above reasons. However, I’ll definitely reopen and implement this feature request in a few months time (once there are less users using the older versions of Visual Studio Code).

**Comment by hkcomori** [comment]
Thank you for your answer.
I look forward to future implementations.

**Comment by Scorg** [comment]
Bumping as 4 years have passed.
