### ISSUE TITLE
Filter branches from view

### ISSUE THREAD

**Issue by JM-Mendez** [mhutchie/vscode-git-graph#49]
**Describe the feature that you'd like**
Provide a way to filter branches from the view. Would be nicer if the user could provide a glob pattern.

**Additional context (optional)**
Gitlab currently requires that the user checkout the merge request in order for the pipelines to be properly triggered. Unfortunately this creates a messy view in the graph. It would be great if you could add the ability to filter the viewable branches.

Also, since the branches are names like `origin/merge-requests/*`, it would be even nicer if we could filter out according to a glob pattern. 

Doing this will also make it nicer for those using the gitflow workflow where branches are named like `feature/some-feature`.

**Comment by mhutchie** [comment]
Thanks for the suggestion! This would definitely be nice have, I’ll have a think about the best way to incorporate the additional UI to support this.

**Comment by paradoXp** [comment]
I think it would be really cool if there were check boxes beside the branches in the branch selection drop down. This would allow me to show a sub-set of the branches (it appears currently I can show one branch or all branches). Sometimes it is useful to only select a few branches to show.

My understanding is this issue is for filtering the drop down list, and what I am suggesting is for selecting the branches to show. I don't know if this should be its own feature or not, if it should, please let me know!

**Comment by mhutchie** [comment]
@paradoXp No need to create a new feature request, this one will focus on a delivering a mechanism to filter branches from view. Thanks for the additional feedback, I’ll keep it in mind when I work on this request.

**Comment by mhutchie** [comment]
This will be available in v1.6.0. I have implemented:
- Allow multiple branches to be selected in the 'Branches' dropdown.
- Predefine an array of custom glob patterns with the new setting `git-graph.customBranchGlobPatterns`, allowing you to use them anytime from the 'Branches' dropdown. For example: `[{"name": "Feature Requests", "glob": "heads/feature/*"}]`

If you'd like to use it before the next release, you can download [v1.6.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

I'll leave the exclusion of branches by using glob patterns for another feature request if it is still necessary. It requires quite a significant amount of additional logic in the branches dropdown, so I'd like to use what I've implemented for a bit to see if exclusion of branches is really necessary.
