### ISSUE TITLE
Date column show selected sorting date.

### ISSUE THREAD

**Issue by BradL-Msft** [mhutchie/vscode-git-graph#490]
**Describe the improvement that you'd like**

The Date column allows sorting by Author or Commit date, but it always displays Author Date.
Some projects have Author and Commit dates with multi-month gaps (see context below for example).
This mismatch causes the graph view to show an apparently incorrect sort (though the sort is correct per the selected option.) 
 
It would be clearer if the "Date" column showed the date that is being used in the sort, or allow the user to choose which date is shown. Allowing the user to pick which date is shown on the graph also clears up the topological sort case.

One possible suggestion, change the 3 sorting options:

"Commit Timestamp Order"
"Author Timestamp Order"
"Topological Order" 

into two groups

"Show Commit Timestamp"
"Show Author Timestamp"
and
"Topological Order" 

where one of the two timestamps is always checked, and Topological order *may be* checked.  If it's checked, Topological order is the sorting order, if not, the displayed date field provides the sorting order.

Or, leave the 3 existing sorting options and just an option to chose the displayed date.

**Additional context (optional)**
https://github.com/tianocore/edk2/commit/b33cf5bfcb4c941370739dfbbe1532ff508fd29d
Commit: b33cf5bfcb4c941370739dfbbe1532ff508fd29d
Parents: fe66288873d055d9528f4bca6f299dc07967d626
Author: Abner Chang <abner.chang@hpe.com>
Author Date: Mon Nov 02 2020 19:32:44 GMT-0800 (Pacific Standard Time)
Committer: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Committer Date: Thu Mar 25 2021 19:56:22 GMT-0700 (Pacific Daylight Time)

**Comment by mhutchie** [comment]
Hi @BradL-Msft,

There is the existing [Date Type `git-graph.date.type`](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#type) extension setting for exactly this reason, to allow the user to chose which date is shown. As you mentioned, this approach handles the Topological case nicely.

It is only available as an extension setting (and not in the Column Header context menu), as user's typically choose there preference once, and keep it that way.

I'll close this improvement request, as I believe your request is already available in Git Graph.

**Comment by BradL-Msft** [comment]
Thank you - sorry I didn't notice the setting
