### ISSUE TITLE
command 'git-graph.view' not found

### ISSUE THREAD

**Issue by krisztiantobias** [mhutchie/vscode-git-graph#492]
**Describe the Bug**
After updating from 1.29 to 1.30 I get an error message for the git graph view. If I switch back to 1.29 the feature still works.

**Steps to Reproduce**
1. Install 1.30.0 version
2. Set Keyboard shortcut for git-graph.view
3. Try to use it

**Actual Behaviour**
Error message _"command 'git-graph.view' not found"_ is displayed

**Expected Behaviour**
The graph view should shown.

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.55.0
 - Git Version: 2.31.1
 - Operating System: Windows 10

**Screenshots (optional)**
![not_found](https://user-images.githubusercontent.com/11661824/113721224-9ec51b80-96ef-11eb-809b-820a506f7f7f.png)

**Comment by mhutchie** [comment]
Hi @krisztiantobias,

The Git Graph contributed command `git-graph.view` is used when:
1. Clicking the "Git Graph" Status Bar Item
2. Running the "Git Graph: View Git Graph (git log)" in the Visual Studio Code Command Palette.
3. When a keyboard shortcut is run (that's assigned to the command in the Visual Studio Code "Keyboard Shortcuts" interface).

I've just tested all three of these, with an identical environment to what you've specified, and they all work as expected. None displayed that error message.

Can you please re-install Git Graph 1.30.0, ensure the extension is enabled, and then try each of these three command usages, to see if one or more aren't working.

If none of them are working, please check to see whether any of the other Git Graph contributed commands are available, by searching "Git Graph" in the Visual Studio Code Command Palette.

You can also check the "Git Graph" Output Channel in Visual Studio Code, to confirm that the extension is starting correctly.

Another user faced a similar issue in #291, and uninstalling then reinstalling the extension resolved it for them (see their comment [here](https://github.com/mhutchie/vscode-git-graph/issues/291#issuecomment-612799755)).

**Comment by krisztiantobias** [comment]
Hi! Sorry about the issue creation, it was the same issue. The extension was not found and only the folder deletion solved the problem. Regards, Krisztián

**Comment by mhutchie** [comment]
Hi @krisztiantobias,

I’m glad to hear that you’ve resolved the issue! Thanks for letting me know what you needed to do to resolve it, I can pass this onto other users if they encounter it in the future.

It seems like Visual Studio Code can (in extremely rarely circumstances) fail to properly install an extension. You’re the third user that I’m aware of who’s encountered it, in over two years, over 35 updates, and over a million users.
