### ISSUE TITLE
Diff views are not shown on first click with wrapTabs = true

### ISSUE THREAD

**Issue by ghost** [mhutchie/vscode-git-graph#493]
When having  "workbench.editor.wrapTabs" : true and the width of the window is so that it would need an additional tab line when the windows is activated because of the menu bar symbols need some more place, the diff view in the side only loads the diff on the second click on the same file.
Better to have a look at the screencast. First normal behaviour is shown then I resize the window as mentioned.

![vscode_1](https://user-images.githubusercontent.com/68994013/113756259-78b07300-9711-11eb-9165-da2f95403866.gif)

**Comment by mhutchie** [comment]
Hi @kt-unzner,

I've been able to replicate this behaviour. I've determined that:
1. It occurs when the user shifts focus from another editor in Visual Studio Code to the Git Graph View. Visual Studio Code appears to change focus on the `mousedown` event.
2. Visual Studio Code recalculates the tabs, and resizes the Git Graph View.
3. If the `mousedown` event is also part of a click event, and Visual Studio Code is resizing the view after it's become focussed, then the click event isn't being fired in the Git Graph View. It occurs on all buttons in the Commit Details View when it's docked (not just when view a diff).
4. As no click event is received by the extension, it doesn't action it.

This resizing issue is also affecting CSS `:hover` selectors.

This behaviour will affect all extensions that use Visual Studio Code [Webview's](https://code.visualstudio.com/api/extension-guides/webview). There's also nothing I can do in the extension to work around it, as for the extension to have a button, the registered listener needs to be triggered on click events.

Please raise this as a bug with Microsoft in the [vscode](https://github.com/microsoft/vscode) repository. Make sure you present it as Webview bug (in the title & issue body), so it can be properly categorised and assigned (e.g. "Webview focussing with wrapTabs = true can prevent click events from being triggered within the Webview"). Just use Git Graph & this issue as an example of an extension that's affected by the Webview bug.

**Comment by ghost** [comment]
Thanks.
