### ISSUE TITLE
Creating annotated tag without message, how?

### ISSUE THREAD

**Issue by Igorgro** [mhutchie/vscode-git-graph#494]
Using this extension it is possible to create an annotated tag without message by not filling message field. However i can't reproduce this using git command, it just fails with 'fatal' message. I've investigated and found in "Output" tab that extension runs command `git tag -a <tag name> -m   <commit hash>`, but this command also doesn't work. So, how this is implemented and how it can be done without this extension?

**Comment by mhutchie** [comment]
Hi @Igorgro,

It depends on what terminal you use, but running `git tag -a <tag name> -m "" <commit hash>` in the Windows Command Prompt will produce an annotated tag without a message. I expect all other shells will have a way to specify an empty string argument.

Internally, the extension spawns a child process to execute each Git command, which accepts all of the command arguments as an array of strings (e.g. `["tag", "-a", "<tag name>", "-m", "<message>", "<commit hash>"]`) - which nicely handles empty strings and avoids escaping issues. The Git Graph Output Channel displays the executed commands by simply joining all these arguments with a space separator, hence the current behaviour with an empty message, and the double space between `-m` & `<commit hash>`.

I'll adjust the Output Channel to explicitly display empty string arguments as "" in the next release, to make it clearer.

**Comment by mhutchie** [comment]
I made several improvements to the logging of Git commands to the Output Channel, including to explicitly display empty string arguments as "".

This will be available in v1.31.0.

If you'd like to use it before the next release, you can download [v1.31.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.31.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
