### ISSUE TITLE
Git graph suddenly wont detect my git respiratory (used to work just fine)? 

### ISSUE THREAD

**Issue by ItsCubeTime** [mhutchie/vscode-git-graph#497]
![image](https://user-images.githubusercontent.com/20190653/114180387-6a946980-9940-11eb-9e8b-437fba70a3e9.png)

Any thoughts? Whats so strange about it is that the rest of VS Codes git tools detect it just fine (you can see some extension called git ease at the bottom left for instance reading the respiratory accurately)

**Comment by mhutchie** [comment]
Please try running the "Git Graph: Add Git Repository" command in the Visual Studio Code Command Palette, and select the folder your showing in the File Explorer (i.e. the Git repository), to either add it, or see an error message that's occurring.

You can also look in the Git Graph Output Channel in Visual Studio Code to see more information.

**Comment by ItsCubeTime** [comment]
> Please try running the "Git Graph: Add Git Repository" command in the Visual Studio Code Command Palette,

Ah yes, thank you :) Worked like a charm 👍
