### ISSUE TITLE
Add Issue linking by branch name (Optional)

### ISSUE THREAD

**Issue by shiipou** [mhutchie/vscode-git-graph#499]
**Describe the feature that you'd like**
On all my repo in my organization, issue linking is made by branch name. This is the case for a lot of people, so I post my idea here :
It can be really useful to automatically link any commit of a branch to an issue by regex.
(It can be done by automatically suffix the commit message by `#18`)

I hope this idea can help many people to became a lot more productive.

**Additional context (optional)**
Example : 
![image](https://user-images.githubusercontent.com/38187238/114837937-81b9d800-9dd4-11eb-940d-1e6d07254ae6.png)
![image](https://user-images.githubusercontent.com/38187238/114838231-c80f3700-9dd4-11eb-9dd1-9a71b2e24ca0.png)

**Comment by mhutchie** [comment]
Hi @shiipou,

This would be a great way to extend the existing Issue Linking functionality! I’ll include it in the next release.

**Comment by shiipou** [comment]
Yes really useful I think, thanks you.
For the moment, I just use a custom script in the `commit-msg` in each of my `.git` local repo.

**Comment by mhutchie** [comment]
After experimenting with a variety of implementation options that all achieved the core capability of this feature request, I settled on a new "View Issue" action on the Branch & Remote Branch right-click context menu's. There were benefit's and disadvantages to each option, but ultimately I felt the newly implemented solution made the best net trade-offs from both user experience & implementation perspectives.

This will be available in v1.31.0.

If you'd like to use it before the next release, you can download [v1.31.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.31.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
