### ISSUE TITLE
Filter repo

### ISSUE THREAD

**Issue by paradoXp** [mhutchie/vscode-git-graph#50]
**Describe the feature that you'd like**
The repo drop-down is a simple drop-down that does not respond to keyboard input. It would be awesome if I could click on the repo drop-down and have the ability to select from the list or type and have the list narrow based on what I type (i.e. filter based on what I type)

**Additional context (optional)**
Adding a keyboard shortcut to pick the repo could be nice as well.

**Comment by mhutchie** [comment]
Thanks for the suggestion, this is a great idea! It would also be useful on the branch dropdown, which may partly solve #49.

**Comment by mhutchie** [comment]
This will be available in v1.4.6, which will be released in the next few hours.
