### ISSUE TITLE
Tiny icon in latest vscode 1.56

### ISSUE THREAD

**Issue by deepnight** [mhutchie/vscode-git-graph#502]
**Describe the Bug**
The "Open GitGraph" button in SCM panel is microscopic since latest Vscode update (1.56.0). See screenshot below.

**Steps to Reproduce**
None, just open vscode.

**Environment**
GitGraph: v1.30.0
VScode:
```
Version: 1.56.0 (system setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1671695/117262973-16eb4200-ae52-11eb-86c9-3b6beb791d99.png)

**Comment by mhutchie** [comment]
This is a Visual Studio Code Bug that was introduced in 1.56.0 - it’s affecting extensions that contribute commands (with icons) to the `scm/title` menu.

I’ve linked this issue to [the issue](https://github.com/microsoft/vscode/issues/123036) that had already been raised in Microsoft’s Visual Studio Code repository. Please follow it to track the delivery of the fix.

If you’re another Git Graph user who is affected by this, please react to the linked Microsoft issue, and post screenshots to it to help them diagnose the issue (and prioritise fixing it).

**Comment by mhutchie** [comment]
Microsoft have included a fix for this in the latest insiders release. For me, it has resolved the issue for the icons that were affected in the extension. Would someone else please update to the latest Visual Studio Code Insiders release, and also verify the fix?

```
Version: 1.57.0-insider (user setup)
Commit: a19565da7dfc739fa26e36aae96113e19fe3806f
Date: 2021-05-07T17:19:03.737Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by mhutchie** [comment]
Visual Studio Code 1.56.2 has been released, which includes the fix for this bug.

```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041
```
