### ISSUE TITLE
Support for remote repositories ("RemoteHub")

### ISSUE THREAD

**Issue by borekb** [mhutchie/vscode-git-graph#503]
VSCode is adding "RemoteHub" functionality – the ability to browse remote repositories without cloning them locally. It's currently available in Insiders edition, see [VSCode 1.56 release notes](https://code.visualstudio.com/updates/v1_56#_remote-repositories-remotehub).

It would be great if Git Graph was supported for this "remote" scenario – I have no idea if that's possible technically or not but it would be a dream scenario to be able to view visual Git log for repositories that I wouldn't have to clone locally 😄.

Currently, it looks like this (quite naturally):

<img width="1194" alt="Screen Shot 2021-05-06 at 10 26 46" src="https://user-images.githubusercontent.com/101152/117267275-67649e80-ae56-11eb-9f51-d7d15657a4ee.png">

**Comment by mhutchie** [comment]
Hi @borekb,

Thanks for raising this feature request, it would definitely be a great integration to have in Git Graph!

As mentioned in the release notes, RemoteHub  is still as a preview “It is currently only available in the Insiders edition of VS Code.”. This means that Microsoft hasn’t finalised the API that extensions must use to integrate with it. Therefore it’s too soon to even consider integrating it with Git Graph, as there will almost certainly be breaking changes and incompatibilities.

I’ll close this feature request for now, and move it to the backlog. Once RemoteHub has matured a little, and is compatible with enough Git Graph users, I’ll definitely explore possible integrations, and re-open this feature request to track it’s delivery.
