### ISSUE TITLE
Add the ability to rebase children from commit interactively

### ISSUE THREAD

**Issue by Falven** [mhutchie/vscode-git-graph#504]
**Describe the improvement that you'd like**
A simple right-click menu option on a commit in the tree-view that allows the user to rebase the children of that commit interactively. 

https://i.stack.imgur.com/5co4C.png

**Additional context (optional)**
The menu option would just have to call `git rebase` with the selected branch and commit sha.

**Comment by mhutchie** [comment]
Hi @Falven,

You can do an interactive rebase of the children of a commit (if on the current branch), by using the "Rebase current branch on this Commit..." commit context menu option, and then check "Launch Interactive Rebase in new Terminal".

![image](https://user-images.githubusercontent.com/5315753/117296198-1f766380-aeb8-11eb-9940-4cc691b5faaf.png)

Currently it's only possible to do an interactive rebase via the terminal (as there currently isn't a dedicated interactive rebase interface implemented in Git Graph). There is already the feature request #113 for "Complete support of rebase operation", which I'm using to tracking the delivery of rebase related requests.

I'll close this request as a duplicate.
