### ISSUE TITLE
Alert error Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by Daners** [mhutchie/vscode-git-graph#508]
**Describe the Bug**
I try to display the git graph, but an alert is thrown with the error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Go to 'open git project in VScode'
2. Click on 'Git Graph" launch button in the Status Bar'
3. See error: Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.

**Expected Behaviour**
A new tab was expected with the git graph of the project

**Environment**
 - Git Graph Extension Version: v1.30.0
 - Visual Studio Code Version: v1.56
 - Operating System: Linux Mint 19.3 (Tricia)

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/3009697/117897725-02131200-b289-11eb-83ef-3b078b3f1be6.png)

![image](https://user-images.githubusercontent.com/3009697/117897758-13f4b500-b289-11eb-9bb3-7de2f6273d8d.png)

**Additional Context (optional)**
VScode recently updated from 1.55 to 1.56

**Comment by Daners** [comment]
Restart my computer, and everything works fine
![image](https://user-images.githubusercontent.com/3009697/117899299-684d6400-b28c-11eb-985b-b08c74472238.png)

**Comment by mhutchie** [comment]
Hi @Daners,

Please raise this as a bug in Microsoft’s Visual Studio Code repository. The error you’ve included is caused within Visual Studio Code, and will almost certainly occur for all [Webview’s](https://code.visualstudio.com/api/extension-guides/webview) contributed by any extension (the Git Graph View uses a Webview). Visual Studio Code has complete control and manages everything about Webview’s, extension’s only provide HTML + JS + CSS to be displayed in the view.

**Comment by akshay-nm** [comment]
Getting this one again.

**Comment by jodesous** [comment]
Same for me since 2 weeks, i have this error when i launch GitGraph. I have to restart vscode all the time.

I'm on linux (Pop!_OS 22.04 LTS)

**Comment by lorisberti** [comment]
What's the solution for that? I'm seeing it today
