### ISSUE TITLE
Reset file to specific revision feature

### ISSUE THREAD

**Issue by LinFor** [mhutchie/vscode-git-graph#516]
**Describe the feature that you'd like**
The ability to reset a single file to a specific revision from commit details view.

I often reorganize commits when preparing pull requests, and sometimes it is necessary to transfer part of the changes from one commit to another. To do this, I usually make a "`git checkout <commit-id> <filepath>`" to get a file with the necessary changes in the working tree. It would be great to be able to invoke such an operation with one click from the commit tree view - via context menu or so.

In "Git Extensions" git client this operation called "Reset file to specific revision".

**Additional context (optional)**
![image](https://user-images.githubusercontent.com/24222858/119514280-8da69b80-bd7d-11eb-9fa1-1283e676050d.png)

**Comment by mhutchie** [comment]
Hi @LinFor,

Thanks for raising this feature request, it would definitely be a great capability to include in Git Graph! I’ll include it in an upcoming release.

**Comment by mhutchie** [comment]
This will be available in v1.31.0.

If you'd like to use it before the next release, you can download [v1.31.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.31.0-beta.2), and install it following the instructions provided [here](https://docs.mhutchie.com/vscode-git-graph/general/downloading-and-installing-releases#manual-installation).

**Comment by LinFor** [comment]
Thanks!

**Comment by AlexeySmolenchuk** [comment]
I think I've put a similar request here https://github.com/mhutchie/vscode-git-graph/issues/791 but also mentioned stashes.
Would it work?

**Comment by ericchase** [comment]
bless you for this feature
