### ISSUE TITLE
Ability to copy branch and tag name to Clipboard like with hash

### ISSUE THREAD

**Issue by morganlombard** [mhutchie/vscode-git-graph#52]
**Describe the feature that you'd like**
Ability to copy branch and tag name to Clipboard like with hash.

**Additional context (optional)**
When right-clicking on a branch, add an option to copy the branch name to the Clipboard
When right-clicking on a tag, add an option to copy the tag name to the Clipboard

**Comment by mhutchie** [comment]
Thanks for the suggestion, this would be great functionality to have!

**Comment by mhutchie** [comment]
This will be available in v1.4.6.

If you'd like to use it before the next release, you can download [v1.4.6-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.6-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
