### ISSUE TITLE
Add "git commit --amend"

### ISSUE THREAD

**Issue by chr7** [mhutchie/vscode-git-graph#520]
**Describe the feature that you'd like**
A way to amend the last commit ("git commit -amend")

**Additional context (optional)**
Right clicking one the last commit of the current branch could offer next to "Checkout..." the entry "Amend".

![grafik](https://user-images.githubusercontent.com/7242780/120535720-9a616a00-c3e3-11eb-86a4-e517111e4f10.png)

**Comment by mhutchie** [comment]
Hi @chr7,

The ability to amend the latest commit is already available in Visual Studio Code’s built-in Git extension. As the Visual Studio Code implementation is already available, and is well integrated with their extensive commit capability, I wouldn’t want to duplicate it in Git Graph.

In general, I don’t duplicate any Git capability available in Visual Studio Code unless additional value can be gained by making it available in Git Graph (the extension is designed to complement Visual Studio Code, not duplicate it). It also allows me to focus feature development on new capabilities that aren’t already available (which provide the most value to users).

I’ll close this feature request for the above reasons.

**Comment by chr7** [comment]
Hi @mhutchie , actually, it's is not available in the same way as "git commit --amend".

For example, "git commit --amend" stages the last commit, you can edit those files, unstage files or stage new files. In contrast, the feature offered by Visual Studio Code offers just to add staged files to the commit but it doesn't stages the commit.
