### ISSUE TITLE
Add "squash" command

### ISSUE THREAD

**Issue by Ioannis-Raptis** [mhutchie/vscode-git-graph#531]
**Describe the feature that you'd like**
I would like to be able to graphically select a set number of commits, right click and select squash.
This will combine the multiple selected commits into one. I will also be able to alter the new commit message.

**Additional context (optional)**
GitKraken is able to do that, so it would be nice to have for git-graph as well :)

**Comment by mhutchie** [comment]
Hi @Ioannis-Raptis,

Thank you for raising this feature request!

Squashing commits in Git is achieved by performing a Git rebase. I already intend to support squashing multiple commits when an interactive rebase user interface is implemented for #113. I'll close this feature request, as the delivery of this functionality will be tracked in #113.

**Comment by Ioannis-Raptis** [comment]
@mhutchie thanks :)
