### ISSUE TITLE
Help icons are included in the checkbox's label

### ISSUE THREAD

**Issue by jacobweber** [mhutchie/vscode-git-graph#532]
**Describe the Bug**
When you right-click a commit and choose Cherry-Pick, the help (i) icons toggle the checkboxes, instead of showing help.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open Git Graph.
2. Right-click a commit.
3. Choose Cherry-Pick.
4. Click one of the (i) icons.
5. The checkbox next to it is toggled.

**Expected Behaviour**
Help text appears

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.57.1
 - Operating System: Mac OS 10.14.6

**Comment by mhutchie** [comment]
Hi @jacobweber,

Throughout the extension, the "help" icon's are only icons (not buttons) - when you hover over them, the cursor changes to the operating system's standard help cursor, and the help information appears in a tooltip for the icon.

For checkboxes in dialogs, any text and/or help icon associated with the checkbox are included in the checkbox's label. If a user clicks anywhere in the checkbox's label, the checkbox's state will be toggled (the standard behaviour for HTML checkboxes).

Up until now, none of the other ~1.3 million users have raised any concern over the current behaviour of the help icon being included in the checkbox labels. I think there's arguments both for and against it, and can understand both. I'll close this as an improvement request for now and add it to the backlog. If in the future enough other users raise similar concerns, I'd happy re-open it, and move the help icon to be outside the checkbox's label.

**Comment by jacobweber** [comment]
Fair enough — I see the tooltip now. I think part of my confusion was that the cursor becoming a question mark made me think I needed to click, but clicking actually **prevents** the tooltip from appearing.
