### ISSUE TITLE
Add "show stashes" toggle

### ISSUE THREAD

**Issue by JensMertelmeyer** [mhutchie/vscode-git-graph#534]
https://github.com/mhutchie/vscode-git-graph/issues/429 added the ability to show/hide stashes. It has a default setting and can even be set individually per repo. Very nice. 👍

Maybe I'm weird, but sometimes I want to see stashes, sometimes not. It takes quite some time to go into settings and toggle it on and off. Maybe it could make sense to add this as a toggle, directly to the UI?

There could be a small icon here
![image](https://user-images.githubusercontent.com/1827784/123397301-8eac3200-d5a2-11eb-9d46-77a74e805765.png)

But I think it makes much more sense like this:
![image](https://user-images.githubusercontent.com/1827784/123397352-9d92e480-d5a2-11eb-93ac-f3eb1d8feff5.png)

What do you think?

**Comment by mhutchie** [comment]
Hi @JensMertelmeyer,

"Show Stashes" can already be toggled via the Repository Settings Widget in the Git Graph UI.

![image](https://user-images.githubusercontent.com/5315753/123398227-9e4d6a00-d5e6-11eb-8510-8ef32f48866a.png)

![image](https://user-images.githubusercontent.com/5315753/123398140-8bd33080-d5e6-11eb-9f4e-4823e31bc9f2.png)

This is available for exactly your use case - please let me know if I've misunderstand your request.

**Comment by JensMertelmeyer** [comment]
No, thank you, this is exactly what I meant with 
> It takes quite some time to go into settings and toggle it on and off

I am aware of the toggle under "Repository settings". My point was that when used excessively, the time taken to perform the following steps adds up to a significant amount:

1. Move the mouse to the little cog ⚙ icon and click
2. Wait for the animation to finish
3. Toggle "Show stashes"
4. Dismiss settings by clicking ✖
5. Wait for the animation to finish

Maybe I'm weird that I'm using it so often (more than anything else), but having a toggle/checkbox right where "_Show Remote Branches_" is would save a lot of time in the long run. I honestly can't say whether I'm a special case or if it could benefit other users as well.

**Comment by mhutchie** [comment]
Hi @JensMertelmeyer,

The vast majority of users either don’t use stashes, or use them so want to see them in the Git Graph UI almost all the time. It took 15 months after stashes were first released (and permanently turned on), that anyone even requested to have a setting to toggle them on/off.

While at the moment there is enough space in the Git Graph View Control Bar, I expect the upcoming advanced filtering controls to take up the remaining space. This won’t leave space for any new controls (e.g. Show Stashes). Ultimately the advanced filtering will be used by far more users, and offer more net value to the extensions user-base.

I’ll close this feature request for now for the above reasons, and that there already is a toggle in the UI. However, once I’ve implemented the highly requested advanced filtering, and I know exactly how much space remains available in the Git Graph View Control Bar, I’ll review several feature requests that have requested other controls to see what can be fit in the remaining space (including this one).
