### ISSUE TITLE
Git Graph stays empty with remote development in container since VS-Code v1.57.1 (regression)

### ISSUE THREAD

**Issue by oschulz** [mhutchie/vscode-git-graph#535]
**Bug Description**

Since VS-Code v1.57.1, Git Graph doesn't seem to work in remote-development mode (tested with remote-SSH) any longer. This used to work fine until VS-Code v1.56.2. On v1.57.1, the Git Graph window just stays empty.

Git Graph may IMHO be the best Git GUI tool for remote systems, currently, it would be awesome to get that functionality back.

**Steps to Reproduce**

* Install the official "Remote - SSH (ms-vscode-remote.remote-ssh)" extension and the Git Graph extension.
* Use Remote-SSH to connect to a system (may just be "localhost") and open a folder with a Git repository
* Open Git Graph (opens, but will be empty on VS-Code v1.57.1).

**Expected Behaviour**

Git Graph should show the usual nice version tree. :-)

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.57.1
 - Operating System: Ubuntu Linux 20.04

**Comment by mhutchie** [comment]
Hi @oschulz,

Can you please provide a screenshot to demonstrate what you're experiencing?

Do you get any error messages, or are there any error logs in the console when you do the following steps? If so, please provide them.
1. Open the Visual Studio Code Command Palette
2. Run "Developer: Open Webview Developer Tools"
3. Navigate to the "Console" tab

**Comment by oschulz** [comment]
Hi @mhutchie ,

thanks, here are the screenshots:

VS-Code v1.56.2:

![git-graph-working](https://user-images.githubusercontent.com/546147/124118330-7f7d2680-da71-11eb-870b-4bf940e5006e.jpg)

VS-Code v1.57.1:

![git-graph-not-working](https://user-images.githubusercontent.com/546147/124120939-9b35fc00-da74-11eb-8b82-c40ee7a129d2.jpg)

**Comment by oschulz** [comment]
Are the "Webview Developer Tools" supposed to work in remote-SSH mode? I can only get them to open in VS-Code windows that don't use remote-SSH.

**Comment by oschulz** [comment]
Another thing I just noticed: I typically run the remote vscode-server session in a Singularity container that contains my software stack and does some bind mounts. When I don't use the container, then Git Graph *does* work in remote mode on v1.57.1. However, I've been running this vscode-server in container setup for a long time and many VS-Code versions now, and there were never any problems with Git Graph. I wonder if something has changed in Code with the new security improvements and so on?

**Comment by oschulz** [comment]
> Are the "Webview Developer Tools" supposed to work in remote-SSH mode? I can only get them to open in VS-Code windows that don't use remote-SSH.

I can use "Developer: Toggle Developer Tools" though, and see the console there. Is that sufficient?

**Comment by mhutchie** [comment]
What you've shown in your screenshot is enough. The behaviour you've observed is a Visual Studio Code [Webview](https://code.visualstudio.com/api/extension-guides/webview) bug that was introduced in Visual Studio Code 1.57.x. It prevents the extension's CSS & JS resources from being accessible in the Webview. It affects all extensions that use a Webview, not just Git Graph (the Git Graph View uses a Webview to render).

In Visual Studio Code 1.57.x, Microsoft made some fairly significant changes to their underlying Webview implementation, that has caused numerous bugs that affect all extensions using Webviews. This is the fourth I'm aware of - see the other issues tagged as "vscode-bug" on https://github.com/mhutchie/vscode-git-graph/issues.

Please raise this as a bug in https://github.com/microsoft/vscode, so Microsoft can fix. Make sure to call your issue something general (e.g. "Extension Webview resource error with Remote SSH"), so it is prioritised accurately as it's an issue affecting all extensions (not just one). Refer to Git Graph as an example of an affected extension in the bug you raise.

**Comment by oschulz** [comment]
Thanks!

**Comment by oschulz** [comment]
Should I close this here, then?

**Comment by mhutchie** [comment]
@oschulz I'll leave this open until Visual Studio Code fixes it, so other affected users can read it (and not raise further Git Graph bugs for it).

**Comment by pomack** [comment]
FYI the bug report is here: https://github.com/microsoft/vscode/issues/127770

**Comment by KaeLL** [comment]
Came here looking for this issue. Thing is, it was working fine up until yesterday's 1.59.0, unlike OP.

**Comment by pomack** [comment]
FYI, this may have been fixed in https://github.com/microsoft/vscode/issues/123494 if anyone is using the vscode insiders build to test. Otherwise will need to wait till 1.60 is released.

**Comment by oschulz** [comment]
> @pomack: this may have been fixed in microsoft/vscode#123494

Thanks - just tested with code-insider-x64-1628833345, the Git graph is back! :-)

**Comment by KaeLL** [comment]
> Otherwise will need to wait till 1.60 is released.

Fucking hell. Well, insiders it it, then.

**Comment by mhutchie** [comment]
This Visual Studio Code bug has been fixed by Microsoft in Visual Studio Code 1.60. If you continue to face this issue, please raise it again with Microsoft.

**Comment by oschulz** [comment]
Thanks again, @mhutchie !

**Comment by bjoham** [comment]
Again broken. :-(

It was working in 1.87, but has been broken in 1.88 - 1.90

[ Extension Webview resource error in Ubuntu #216513 ](https://github.com/microsoft/vscode/issues/216513)

**Comment by oschulz** [comment]
GitGraph is working for me on Ubuntu v22.04 with Remote-SSH to Ubuntu v22.04 using VSCode v1.90.1 .

**Comment by bjoham** [comment]
With 22.04 it is working.
Thanks!

**Comment by MichaelLiss** [comment]
In version 1.93.0 git graph works (_**on a mac, Sonoma 14.6.1**_) in a normal file view:
![image](https://github.com/user-attachments/assets/9d4be992-72d2-4aa8-816b-f63161f70c25)

![image](https://github.com/user-attachments/assets/d49bdd3a-bfe8-44a5-8713-2ca0a45a9267)

However, when I load my docker devcontainer: it's greyed out and will not load
![image](https://github.com/user-attachments/assets/a5521aad-ed8b-4c45-b8ef-f05bfcaf6a18)


Here is my devcontainer contents:
```
{
  "name": "React Dev Container",
  "dockerFile": "Dockerfile",
  "context": "..",
  "appPort": 3000,
  "customizations": {
    "vscode": {
      "extensions": [
        "ms-python.python",
        "esbenp.prettier-vscode",
        "dbaeumer.vscode-eslint",
        "mhutchie.git-graph"
      ]
    }
  },
  "postCreateCommand": "npm install",
  "remoteUser": "node"
}
```


tried adding "ms-vscode-remote.remote-ssh" - still does not load
```
{
  "name": "React Dev Container",
  "dockerFile": "Dockerfile",
  "context": "..",
  "appPort": 3000,
  "customizations": {
    "vscode": {
      "extensions": [
        "ms-python.python",
        "esbenp.prettier-vscode",
        "dbaeumer.vscode-eslint",
        "mhutchie.git-graph",
        "ms-vscode-remote.remote-ssh"
      ]
    }
  },
  "postCreateCommand": "npm install",
  "remoteUser": "node"
}
```
