### ISSUE TITLE
Unable to load Git Graph in Windows10 when I exec code.exe from msys2 bash

### ISSUE THREAD

**Issue by yumetodo** [mhutchie/vscode-git-graph#542]
When I want to develop BIG size repository, I often use `git clone --depth`. It's called shallow clone.

In such a repository, I manually edit `.git/config` like below:

```
...
[remote "origin"]
...
	fetch = +refs/heads/master:refs/remotes/origin/master
	fetch = +refs/heads/foo/bar1:refs/remotes/origin/foo/bar1
	fetch = +refs/heads/foo/bar2:refs/remotes/origin/foo/bar2
...
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "foo/bar1"]
	remote = origin
	merge = refs/heads/foo/bar1
[branch "foo/bar2"]
	remote = origin
	merge = refs/heads/foo/bar2
...
```

When I open such repository with vscode, and use this plugin to watch git graph, `Unable to load Git Graph` will be shown.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Create git repository which hold multiple branches and at least >=10 commit.
2. `git clone --depth=9 <git repo url>` and `cd`
3. edit `.git/config` like above
4. `git fetch origin`
4. Open local repo with vscode and open git graph

**Expected Behaviour**
show git graph

**Environment**
 - Git Graph Extension Version: 1.13.0
 - Visual Studio Code Version: 1.58.2
 - git version: 2.32.0
 - Operating System: Windows 10

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @yumetodo,

There are two possible high-level causes of the error message "Unable to load Git Graph", that are distinguished by the message underneath the heading. I assume you are likely facing the second:
1. Unable to find a Git executable. Either: Set the Visual Studio Code Setting "git.path" to the path and filename of an existing Git executable, or install Git and restart Visual Studio Code.
2. No Git repositories were found in the current workspace when it was last scanned by Git Graph.

Please try running the "Git Graph: Add Git Repository..." command in the Visual Studio Code Command Palette, and select the folder that is the repository you cloned. Please reply with the error message that was produced, as it will contain more detail, and be more informative of the exact issue you're facing.

**Comment by yumetodo** [comment]
@mhutchie Thank you. Shallow clone was not related.

In command prompt, I can found git in default search path. and vscode's other git operation works fine.

```
>"C:\Program Files\Git\bin\git.exe" --version
git version 2.32.0.windows.1
```

I also tried  "Git Graph: Add Git Repository..." and no effect.

**Comment by mhutchie** [comment]
Hi @yumetodo,

What message did you receive when running "Git Graph: Add Git Repository..."? It will always produce an information or error message in Visual Studio Code indicating the result of the command.

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/127273852-d4f655fe-91e9-4185-a6f6-222e33e5d9a4.png)

**Comment by mhutchie** [comment]
@yumetodo,

After the repository was added, can you confirm whether you are still receiving the "Unable to load Git Graph" error message after closing and re-opening the Git Graph View.

If you still receive the same message, please provide the entire contents of the Git Graph Output Channel after completing the following steps:
1. Close & re-open Visual Studio Code
2. Run the "Git Graph: Add Git Repository..." command (same as you just did)
3. Open the Git Graph View

**Comment by yumetodo** [comment]
Ok, now I got it how to reproduce.

I exec code.exe from:
- Windows10 start menu: 🆗  process env: [from_start_menu.tsv.txt](https://github.com/mhutchie/vscode-git-graph/files/6892793/from_start_menu.tsv.txt)
- msys2 bash like `code .`: ❌ process env: [from_msys2.tsv.txt](https://github.com/mhutchie/vscode-git-graph/files/6892798/from_msys2.tsv.txt)


```
$which code
/c/Users/21-0042/AppData/Local/Programs/Microsoft VS Code/bin/code

$git --version
git version 2.32.0

$which git
/usr/bin/git
```

`~/.bashrc`

```
export PATH='/c/Users/yumetodo/AppData/Local/Programs/Microsoft VS Code/bin/':'/c/ProgramData/chocolatey/bin/':'/c/Program Files (x86)/Common Files/Oracle/Java/javapath/':'/c/Program Files/Docker/Docker/resources/bin/':$NVM_HOME:$NVM_SYMLINK:'/c/Program Files/dotnet/':'~/bin/gibo':$PATH
```

**Comment by mhutchie** [comment]
Hi @yumetodo,

That now makes a lot of sense. There are a number of fundamental reasons why it's not feasible for the extension to be compatible with the version of Git included with msys2 (when run on Windows), so the extension cannot support it. For Windows systems, the extension must use a standard Windows Git executable.

You should be able to enforce that the Windows Git executable is always used by Visual Studio Code & Git Graph by setting the Visual Studio Code Setting [git.path](https://docs.mhutchie.com/vscode-git-graph/general/extension-settings#git-path) appropriately. This should resolve the issue for you - other users have done this in the past.

If it's possible, I'd recommend that you always start Visual Studio Code outside of msys2 bash - otherwise you'll face a number of limitations that cause issues with numerous Visual Studio Code extensions (not just Git Graph).

**Comment by zdimaz** [comment]
PLS install git bash and restart vscode

**Comment by yumetodo** [comment]
@zdimaz Whether git bash is installed or not is completely not related to this issue.

**Comment by akirax-git** [comment]
Could you please help me to solve this problem? I encountered a similar situation. 

Issue: Installed Git Graph extension into VSc on my new corporate laptop but it does not recognize the repository with the message as below,
![image](https://user-images.githubusercontent.com/18065622/168473223-87aa3d74-f4e0-4ed4-b88c-e231feb95ba8.png)

What I did:
1. Edit settings.json in VSC as below, yet not worked
![image](https://user-images.githubusercontent.com/18065622/168473200-5ce89f51-0de7-4046-b385-3f26df4c177e.png)

2. Added the git directory above to the env var, still not worked
![image](https://user-images.githubusercontent.com/18065622/168473799-f13430be-440f-4163-a086-1855358fb693.png)

3. Find this thread and followed to check the result on my bash terminal in VSc
```
$which code
/c/Users/***/AppData/Local/Programs/Microsoft VS Code/bin/code

$git --version
git version 2.36.1.windows.1

$which git
/mingw64/bin/git

```
then changed path as below
![image](https://user-images.githubusercontent.com/18065622/168473784-c199f772-0330-4eee-a3eb-afbeb9ed94af.png)

and not worked.

Just in case, git itself worked in my VSc
![image](https://user-images.githubusercontent.com/18065622/168473832-561f0e06-730d-48cd-9d1d-e533eb3f29c1.png)

Please help me to use Git Graph.

**Comment by khoale2022** [comment]
why this is closed? The suggestion does not work and there are no answer yet?

**Comment by kenji-shimada-zs** [comment]
Please open setting and edit settings.json.
and add standard Windows Git executable path.
![image](https://github.com/mhutchie/vscode-git-graph/assets/144294328/96301f8a-e24a-420f-9d02-f7476f2d5234)
