### ISSUE TITLE
Web Visualization - how to display the info directly on Github

### ISSUE THREAD

**Issue by wojm** [mhutchie/vscode-git-graph#544]
**Describe the feature that you'd like**
A clear and concise description of what you'd like to be included in Git Graph.
I would like a web interface for this app. I think the easiest one would be a Chrome extension. This extension would be responsible for the computation. Alternatively, I've considered using a tool like GitPod to be used to render VSCode and in turn the app.

**Additional context (optional)**

I have a curriculum that I teach out of Github ie the content is delivered through Github. One of the more important details is what prerequisites are required for a given commit. This tool is a fantastic way to describe it.

My possible solutions are:
 - turn the app into a website
 - turn the app into a Chrome extension
 - create a GitPod link for a repository that has git graph as a recommended extension. 
 - screen capture the app and commit it into the repository
 - capture the text resulting from `git log --graph --oneline` in a text file. 

Hoping to get some thoughts from the developers on the projects. 

Also wanted to say how much I appreciate the tool. Easily one of the most valuable tools in my workflow. Cheers!

**Comment by mhutchie** [comment]
Hi @wojm,

Thank you for your feedback!

As a Visual Studio Code extension, Git Graph is available through the official web-based version of Visual Studio Code (which is available via GitHub Codespaces).

It can also be installed on most third-party web-based Visual Studio Code equivalents. However, I would strongly recommend against using them as I frequently find the third-parties have many of their own bugs (on top of those released in Visual Studio Code).

It is already a huge effort to maintain and support the extension on all of the existing supported platforms, so it's simply not feasible to expand it onto other platforms (e.g. a website or Chrome extension).

I'll close this issue, however please reply to this thread if you have any further questions.
