### ISSUE TITLE
Remote Branches deleted outside of vscode don't update in Git Graph

### ISSUE THREAD

**Issue by ghost** [mhutchie/vscode-git-graph#545]
**Describe the Bug**
If I have a repo with a remote branch, and git graph shows the branch, deleting the branch via github/gitlab/other does not change what git graph is showing. Even if the local branch is also deleted, the remote branch is still shown in git graph. Reloading vscode, gitgraph, etc. does not change this.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Clone remote repo
2. Outside of vscode, delete a remote branch
3. View git graph
4. Observe the remote branch in git graph

**Expected Behaviour**
The remote branch should be no longer visible in git graph after the remote branch is deleted.

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.58.2-1
 - Operating System: Arch Linux (Also happens in Windows 10)
 
 **Screenshots**
 
![image](https://user-images.githubusercontent.com/69373044/127752380-b6d8026a-70ad-4830-8709-287bcb021321.png)
![image](https://user-images.githubusercontent.com/69373044/127752387-cafa6750-327a-454f-822d-26021b5498c7.png)

**Comment by mhutchie** [comment]
Hi @KrazyKirby99999,

The type of branch you are referring to is called a [remote-tracking branch](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches), and what you've observed is the expected Git behaviour (it has nothing to do with Git Graph). In this situation, you'd be able to see the same remote-tracking branch still in your local repository if you run the Git command `git log --graph`.

If you have deleted a branch on a remote, you need to prune the corresponding remote-tracking branch from your local repository.

You can do this in Git Graph by:
1. Open the Repository Settings Widget by clicking the Settings button on the Git Graph View Control Bar 
![image](https://user-images.githubusercontent.com/5315753/127756277-7cdc19b3-283d-4286-8720-6bbf6c889bda.png)
2. Click the "Prune Remote" button for the corresponding remote:
![image](https://user-images.githubusercontent.com/5315753/127756244-bd06b1b5-b1ed-4667-98ca-901173f6ad17.png)
3. Click "Yes, prune" after confirming the details are correct 
![image](https://user-images.githubusercontent.com/5315753/127756291-7e8f76e6-5b0b-4610-9430-fcd80c295504.png)

**Comment by andreas-vester** [comment]
I stumbled upon this issue, too.
I suggest to implement some kind of "auto-prune". Why would I keep a branch in my graph that doesn't exist anymore?

**Comment by janvorwerk** [comment]
@andreas-vester I stumbled upon this oldish issue as well, and actually the feature you were asking for does exist 🚀
<img width="914" alt="image" src="https://github.com/mhutchie/vscode-git-graph/assets/139635115/e2ef7d02-3a96-4584-ba65-4772f990e8a4">

or, in JSON settings:
```
"git-graph.repository.fetchAndPrune": true
```

Fantastic extension BTW!! Thanks a lot 🙏

**Comment by janvorwerk** [comment]
> ```
> "git-graph.repository.fetchAndPrune": true
> ```

This used to work, but fails to work now :'(
