### ISSUE TITLE
Allow to drag & drop to re-order commits when interactive rebase

### ISSUE THREAD

**Issue by piavgh** [mhutchie/vscode-git-graph#551]
**Describe the feature that you'd like**
A clear and concise description of what you'd like to be included in Git Graph.

Not sure if there is a duplicate request like this before, but please check this video to see what I mean:

https://youtu.be/GDTOsXejxYo

Basically, I have a git log like this:

```
A
B
X
C
```

I can drag and drop to re-order them to:

```
A
B
C
X
```

If this extension can do something like that, I think there will be a lot more users.

Thanks.

**Additional context (optional)**

**Comment by mhutchie** [comment]
Hi @piavgh,

Thank you for raising this feature request!

I'm using the existing feature request #113 to track the delivery of a far more feature-complete implementation of an interactive rebase capability (far more than just the original request). This feature request is a nice suggestion, that I'll be sure to further consider when #113 is implemented.

Closing as a duplicate.

**Comment by piavgh** [comment]
Thanks for your information
