### ISSUE TITLE
add features that are in gitkraken but not in vscode-git-graph

### ISSUE THREAD

**Issue by romanholidaypancakes** [mhutchie/vscode-git-graph#553]
**Describe the feature that you'd like**

- git graph
![image](https://user-images.githubusercontent.com/51652878/129669884-0040784c-d139-45c7-bef9-8b0bae996ade.png)

- gitkraken

![image](https://user-images.githubusercontent.com/51652878/129669843-f2fb5b63-0b7f-4b37-acb2-cbf44585fd6e.png)

such as "edit commit message" etc.

**Comment by mhutchie** [comment]
Hi @inaryart,

All of the actions in the screenshot (except "Edit commit message") are available in various context menu's in Git Graph ([see these docs](https://docs.mhutchie.com/vscode-git-graph/general/context-menus) for a full list).

For "Edit commit message" there are two cases where this would be used:
* Edit the last commit's message: This can be achieved through Visual Studio Code's built-in Git Extension. Git Graph leaves committing-related functionality to the built-in Git Extension as it already provides a very extensive set of capabilities that cover almost all use cases. (if the extension was to implement some of these features, it would just be duplicating functionality)
    * ![image](https://user-images.githubusercontent.com/5315753/133922496-742e7d8e-d3e9-4d21-b2f8-214769a03ff0.png)
* Edit a historical commit message: This is rarely done as it's generally considered bad practice to "rewrite history" in Git repositories. Therefore I don't provide a dedicated action in the context menu for it, however it can easily be achieved by choosing the interactive option with "Rebase current branch on this Commit...".
