### ISSUE TITLE
Git Graph not loading

### ISSUE THREAD

**Issue by JaredGlastetterPluto** [mhutchie/vscode-git-graph#554]
**Describe the Bug**
When opening the graph view, the repo seems to be fetching / loading continuously  and never stops. No branches are ever displayed and the large Loading ... text continues to animate, as well as the loading icon animating at the very top right beside the fetch icon. The whole top bar is unresponsive, the branches drop down, the check box and all the buttons at the top right.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Go to source control tab in VS code
2. Click on graph icon on the top right of source control tab
3. Git graph never loads

**Expected Behaviour**
The graphical tree view appears and finishes loading.

**Environment**
 - Git Graph Extension Version: [1.30.0]
 - Visual Studio Code Version: 1.50.1
 - Operating System: mac os 11.3 big sur

**Additional Context**
This only happens on one of my repos, other repos seem to be working as expected. Through git commands I am able to interact with remote through fetch, pull, push.

- Troubleshooting:
    - restarted system
    - restarted vs code
    - re installed extension
    - turned off auto load / auto fetch

**Comment by JaredGlastetterPluto** [comment]
After about 7 hours of loading the graph has started showing again and is acting as expected.

**Comment by mhutchie** [comment]
Hi @JaredGlastetterPluto,

As the extension is now acting as expected, the information you’ve provided isn’t enough to consistently replicate the issue, and no other users have reported it, I’ll close this issue for now.

If you do get this issue again, and can produce a set of steps that consistently replicates it, please reply to this thread and I can investigate it further.
