### ISSUE TITLE
Change contextMenuItem `click` to `mouseup`

### ISSUE THREAD

**Issue by githrdw** [mhutchie/vscode-git-graph#557]
**Describe the improvement that you'd like**
I am using Git Graph on daily basis and something I can't unlearn myself is the fact that I press the left mouse button in the context menu before selecting a contextMenuItem.
The context menu will close, but no action (handler) is called.

I have already tried to focus and hold my mouse still before clicking on a context item, but unfortunately I keep failing to stick to this behaviour😅

**Additional context (optional)**
The solution is fairly easy, as only this `click` event has to be `mouseup`:
https://github.com/mhutchie/vscode-git-graph/blob/e1365c9cc1de4a7bd7a9bc4f5032144fafeb2844/web/contextMenu.ts#L91
So I tested this solution locally and it's working exactly how my mind expects it to work.

(also thanks and compliments on your work, could not live without it)

**Comment by mhutchie** [comment]
Hi @githrdw,

Thanks for raising this improvement request and providing an implementation for it.

The reason for using the `click` event is that it requires the user to press and release the pointer on a specific action. Considering it's critical that the user doesn't accidently run the wrong Git action, I felt having this extra certainty was beneficial.

From the description you provided, I see how the `mouseup` event may work better for you (and other users like you). However, I could alternatively justify using the `mousedown` event for similar reasons for some other users. By using the `mouseup` or `mousedown` event it potentially negatively impacts the users in the other group. I ultimately feel that using the `click` event is a nice & unambiguous middle ground that.

I experimented with various other ways to improve the behaviour, and found an alternative way to improve the current experience somewhat, while still using the `click` event.
| Action | Previous Behaviour | New Behaviour |
| - | - | - |
| User clicks on a context menu item | Action handler is called | *Same as Previous Behaviour* |
| User clicks within the context menu (but not on a specific item) | Context menu is closed | Context menu stays open, allowing the user to reattempt clicking on a specific item |
| User clicks outside the context menu | Context menu is closed | *Same as Previous Behaviour* |

This will be available in v1.31.0.

If you'd like to use it before the next release, you can download [v1.31.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.31.0-beta.3), and install it following the instructions provided [here](https://docs.mhutchie.com/vscode-git-graph/general/downloading-and-installing-releases#manual-installation).
