### ISSUE TITLE
maybe we could add a shortcut for open view？

### ISSUE THREAD

**Issue by heartacker** [mhutchie/vscode-git-graph#559]
**Describe the feature that you'd like**
A clear and concise description of what you'd like to be included in Git Graph.
shortcut to view GG
**Additional context (optional)**
maybe <kbd>ctrl+shift+g ctrl+g</kbd> is good 
thanks

**Comment by mhutchie** [comment]
Hi @heartacker,

Git Graph contributes the `git-graph.view` command to Visual Studio Code, that opens the Git Graph View. Any command in Visual Studio Code can have a keyboard shortcut assigned to them by the user, via Visual Studio Code's "Keyboard Shortcuts" interface. This will allow you to assign any keyboard shortcut you like to open the Git Graph View.

I decided not to have a keyboard shortcut assigned to `git-graph.view` by default, as it was virtually impossible to find a suitable keybinding that didn't conflict with keybindings already used by other popular extensions in Visual Studio Code. By allowing users to assign their own preferred keybindings via Visual Studio Code's "Keyboard Shortcuts" interface, users also have the ability to reassign & make use of a keybinding from another extension (for example, I have `ctrl+g` bound to run `git-graph.view`).

FYI: The full list of all commands contributed by Git Graph is [here](https://github.com/mhutchie/vscode-git-graph/blob/develop/README.md#extension-commands).
