### ISSUE TITLE
Commit hashes should be monowidth 

### ISSUE THREAD

**Issue by nopeless** [mhutchie/vscode-git-graph#562]
**Describe the feature that you'd like**
![image](https://user-images.githubusercontent.com/38830903/132121754-d4b3894c-958f-4903-83df-928b68377ff1.png)
this should be code

**Additional context (optional)**
I'm pretty sure this is trivial. Discussions are welcome

**Comment by mhutchie** [comment]
Hi @nopeless,

I experimented with this, however I've found that monospace fonts in Visual Studio Code are very inconsistent across platforms. Therefore I was unable to find a suitable monospace font that rendered suitably on Windows, Mac, and Linux.

Considering this is a purely cosmetic change, and no other users have expressed interest in it during the last 2.5 years, I don't want to spend any more time on it at the present time. I'll close this feature request and move it to the backlog for now. Hopefully in the future Visual Studio Code will provide a more consistent cross-platform font experience, in which case I'll re-open and implement this feature request.
