### ISSUE TITLE
git graph extension does not build a branch graph

### ISSUE THREAD

**Issue by AndreyDementev** [mhutchie/vscode-git-graph#563]
**Describe the Bug**
The gif graph extension does not build a graphical representation of the branches. Instead of several branches, I see one straight line with marked commits.

**Steps to Reproduce**
This behavior occurs under any conditions. I was reinstalling this extension. No changes.

**Environment**
 - Git Graph Extension Version: v1.30.0
 - Visual Studio Code Version: v1.60.0
 - Operating System: Windows 10 v21H1
 - git version 2.33.0.windows.2

**Screenshots (optional)**
<img width="649" alt="Screenshot" src="https://user-images.githubusercontent.com/59799940/132401462-df08e064-ea94-4448-851e-91367980e7de.png">
The screenshot shows 3 branches.

I will answer any clarifying questions.
My email: adementev@mail.ru

**Comment by mhutchie** [comment]
Hi @AndreyDementev,

Please provide the output of the Git command `git log --graph --all`, as it is a way to independently verify the structure of your repository.

Branches are only shown with different colours (and in different columns) where multiple lines of history run in parallel. In other words, two commits or the uncommitted changes must share the same parent commit. It's entirely possible that this never occurs in your repository, which explains why the graph is rendered as you currently see.

**Comment by AndreyDementev** [comment]
Hi Michael.
 
PS C:\Users\ademe\Projects\IUS-OTB\ESP32\Control_Unit> git branch -a
* NewWaitResponce
  Test1
  master
  remotes/origin/NewWaitResponce
  remotes/origin/Test1
  remotes/origin/main
  remotes/origin/master
 
PS C:\Users\ademe\Projects\IUS-OTB\ESP32\Control_Unit> git log --graph --all
* commit 850b0ac23a61b4fef98871a0ef192352a76f3768 (HEAD -> NewWaitResponce, origin/NewWaitResponce)       
| Author: AndreyDementev ***@***.***>
| Date:   Tue Sep 7 18:11:47 2021 +0300
|
|     Добавил большие паузы. Вроде заработало
|
* commit 2c4cf0b8c2cefde58a23a95558d0396ee0177fd0
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 22:20:08 2021 +0300
|
:...skipping...
* commit 850b0ac23a61b4fef98871a0ef192352a76f3768 (HEAD -> NewWaitResponce, origin/NewWaitResponce)       
| Author: AndreyDementev ***@***.***>
| Date:   Tue Sep 7 18:11:47 2021 +0300
|
|     Добавил большие паузы. Вроде заработало
|
* commit 2c4cf0b8c2cefde58a23a95558d0396ee0177fd0
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 22:20:08 2021 +0300
|
|     Окончание переделки
|
:...skipping...
* commit 850b0ac23a61b4fef98871a0ef192352a76f3768 (HEAD -> NewWaitResponce, origin/NewWaitResponce)       
| Author: AndreyDementev ***@***.***>
| Date:   Tue Sep 7 18:11:47 2021 +0300
|
|     Добавил большие паузы. Вроде заработало
|
* commit 2c4cf0b8c2cefde58a23a95558d0396ee0177fd0
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 22:20:08 2021 +0300
|
|     Окончание переделки
|
* commit 2bec7b79a5513a54c73e4acb7d410a9f3956fdd3
| Author: AndreyDementev ***@***.***>
:...skipping...
* commit 850b0ac23a61b4fef98871a0ef192352a76f3768 (HEAD -> NewWaitResponce, origin/NewWaitResponce)       
| Author: AndreyDementev ***@***.***>
| Date:   Tue Sep 7 18:11:47 2021 +0300
|
|     Добавил большие паузы. Вроде заработало
|
* commit 2c4cf0b8c2cefde58a23a95558d0396ee0177fd0
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 22:20:08 2021 +0300
|
|     Окончание переделки
|
* commit 2bec7b79a5513a54c73e4acb7d410a9f3956fdd3
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 13:50:29 2021 +0300
:...skipping...
* commit 850b0ac23a61b4fef98871a0ef192352a76f3768 (HEAD -> NewWaitResponce, origin/NewWaitResponce)       
* commit 850b0ac23a61b4fef98871a0ef192352a76f3768 (HEAD -> NewWaitResponce, origin/NewWaitResponce)       
| Author: AndreyDementev ***@***.***>
| Date:   Tue Sep 7 18:11:47 2021 +0300
|
|     Добавил большие паузы. Вроде заработало
|
* commit 2c4cf0b8c2cefde58a23a95558d0396ee0177fd0
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 22:20:08 2021 +0300
|
|     Окончание переделки
|
* commit 2bec7b79a5513a54c73e4acb7d410a9f3956fdd3
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 13:50:29 2021 +0300
:...skipping...
* commit 850b0ac23a61b4fef98871a0ef192352a76f3768 (HEAD -> NewWaitResponce, origin/NewWaitResponce)
| Author: AndreyDementev ***@***.***>
| Date:   Tue Sep 7 18:11:47 2021 +0300
|
|     Добавил большие паузы. Вроде заработало
|
* commit 2c4cf0b8c2cefde58a23a95558d0396ee0177fd0
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 22:20:08 2021 +0300
|
|     Окончание переделки
|
* commit 2bec7b79a5513a54c73e4acb7d410a9f3956fdd3
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 13:50:29 2021 +0300
|
* commit 5849b31286aed1e1d7f0ef912a7f8909916aec7a
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 13:15:05 2021 +0300
|
|     Some errors
|
* commit 1161f5bb74ab91bd1a65aa4b7cab337c660bc47e
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 13:00:41 2021 +0300
|
|     переделал WaitResponce и изменил параметр Timeout на  RowCount
|
* commit 62624bbaced4b90f5786f45472ce545da3b1d7c8 (origin/Test1, Test1)
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 11:45:25 2021 +0300
|
* commit bb733e768fc955856ee95d28a45ed009aa636ac2
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 11:44:44 2021 +0300
|
* commit e41fc127c60e69461ce65b70335fad7755acc656
| Author: AndreyDementev ***@***.***>
| Date:   Mon Sep 6 11:07:18 2021 +0300
|
* commit db551518f31182a0ffddcce14722d299eda2c03e
| Author: AndreyDementev ***@***.***>
| Date:   Sun Sep 5 23:23:07 2021 +0300
|
|     Подправил синтаксис
|
* commit 2d0cdbd04d72300cab372f62efc8f46feebadf47
| Author: AndreyDementev ***@***.***>
| Date:   Sun Sep 5 15:32:31 2021 +0300
|
|     Подправил имя кнопки
|
* commit f35a1c38f2696a6db0849917a03fa7226448d8c7 (origin/master, master)
| Author: AndreyDementev ***@***.***>
| Date:   Sun Sep 5 10:51:12 2021 +0300
|
|     first commit
|
* commit 0cc415c7504567a452939da81a02ec094fb42cdb (origin/main)
  Author: AndreyDementev ***@***.***>
  Date:   Sun Sep 5 02:30:00 2021 +0300
      inintial commit
(END)
 
 
Best regards,
Andrey Dementev
***@***.***

**Comment by mhutchie** [comment]
The output you provided from Git confirms that all commits in your repository are on a single line of history, with no two commits sharing the same parent.

Therefore, just like the Git command's graph output, all the commits are rendered on a single line of history, with branch labels attached to the correct commits. This behaviour is consistent with most common Git UI's (and Git itself).

Once your repository contains multiple lines of history running in parallel, the graph will change to reflect it (with multiple coloured lines running in parallel).

**Comment by AndreyDementev** [comment]
Thanks for the quick answers
