### ISSUE TITLE
[UX]PLEASE, divide Reset and Rebase buttons out of each other

### ISSUE THREAD

**Issue by elkemper** [mhutchie/vscode-git-graph#567]
Hey guys!!

While using your extension, i'm using rebase feature sometimes. But this button is SO similar and SO close to Reset button, so i've mis-clicked few times. And you know, how distracting and annoying is this.

![image](https://user-images.githubusercontent.com/21986537/133758837-19002f1f-6900-4cc8-a9de-8a782ac8367b.png)
Yeah, yeah, there was a confirmation pop-up. But c'mon, who is reading it? 

So, please, make this feature more user-friendly, and forgivable. At last, we're not using vim thou!

**Comment by mhutchie** [comment]
Hi @elkemper,

While I understand that the names of these two actions are fairly similar, there aren't alternative names that are more distinct. Additionally, the existing grouping (see below) separates the 11 actions into four fairly even logical groups (according to the type of action). As no other users have ever raised any concerns over the similarity of these actions, I'll close this feature request for now. If a substantial portion of users express similar concerns in the future, I'd happily reconsider the grouping of these actions.

Create Actions on the Commit:
* Add Tag...
* Create Branch...

Action on the Commit:
* Checkout...
* Cherry Pick...
* Revert...
* Drop... *(if topologically possible)*

Actions on the current branch (related to this commit):
* Merge into current branch...
* Rebase current branch on this Commit...
* Reset current branch to this Commit...

Copy Actions:
* Copy Commit Hash to Clipboard
* Copy Commit Subject to Clipboard
