### ISSUE TITLE
backslash not display  

### ISSUE THREAD

**Issue by msongz** [mhutchie/vscode-git-graph#568]
**Describe the Bug**
lets say I have a commit message : http:\\/\\/
on the side bar it shows correct

but in the main graph, it shows: http://

**Environment**
 - Git Graph Extension Version: 1.60.1
 - Visual Studio Code Version: [e.g. 1.37.1]
 - Operating System: macOS 11.4

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/2059694/133846919-9a2a8da0-3a08-4e26-9818-9cb2f84a0edd.png)

**Comment by mhutchie** [comment]
Hi @msongz,

The backslash characters are being removed (as expected) when Git Graph is formatting the commit message using Markdown. This is according to the Markdow specification [here](https://spec.commonmark.org/0.30/#backslash-escapes). You can independently observe this behaviour using the GitHub Markdown Formatting:
| Raw Input Text | Markdown Formatted Text |
| - | - |
| `http://` | http:// |
| `http:\/\/` | http:\/\/ |
| `http:\\/\\/` | http:\\/\\/ |

If you don't want the extension to perform Markdown formatting, you can disable it with the extension setting [`git-graph.markdown`](https://docs.mhutchie.com/vscode-git-graph/general/extension-settings#markdown).
