### ISSUE TITLE
Fetch button

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#57]
I think a git fetch button could be a plus for this amazing extension
Could be located in this position
![image](https://user-images.githubusercontent.com/44493964/56788940-fdde3e00-6800-11e9-9343-a09dac1a87ca.png)

**Comment by mhutchie** [comment]
Thanks for the suggestion, this is a great idea!

**Comment by rbalet** [comment]
Nice, tell me if you need helps develop the plugin.
I would be glad to help you

**Comment by mhutchie** [comment]
Thanks for the offer! I'm just wrapping up the last minor release 1.4.6 of 1.4.#, and will then work on the next major release 1.5.0. The planned features in 1.5.0 would probably be best completed by me as they are quite complex, and I already have a good idea of how I intend to implement them. If you're still interested once 1.5.0 is released, let me know then, it would be great if you can help out with some smaller, more isolated features.

**Comment by mhutchie** [comment]
This will be available in v1.7.0, which will be released in the next day.
