### ISSUE TITLE
Folders from workspace is not added automatically in Git-Graph view

### ISSUE THREAD

**Issue by Satheeshkumar-Duraisamy** [mhutchie/vscode-git-graph#578]
All the git repositories are configured as folders in a workspace and saved as xyz.code-workspace file as follows
```
{
	"folders": [

		{
			"name": "server",
			"path": "projects/xyz/server"
		},
		{
			"name": "client",
			"path": "projects/xyz/client"
		}
	]
}
```

When Git-Graph view is opened, the **Repo** dropdown is not available to select the desired git repository

I have added all the git repositories manually using **Git-Graph: Add Git Repository...** command

Can't be add all the folders form workspace folders into Git-Graph Repo dropdown automatically?
(or)
Is there any way to save these configurations in a file and restore back?

**Comment by mhutchie** [comment]
Hi @Satheeshkumar-Duraisamy,

Once you've added the Git repositories to a saved workspace, Git Graph will remember them across Visual Studio Code sessions for that workspace.

The extension setting [`git-graph.maxDepthOfRepoSearch`](https://docs.mhutchie.com/vscode-git-graph/general/extension-settings#max-depth-of-repo-search) can be used to configure the maximum depth of subfolders to search when discovering repositories in the workspace. By default it's set to 0 (don't search subfolders).

**Comment by Satheeshkumar-Duraisamy** [comment]
@mhutchie 

thanks for the quick reply. I need this information to be persisted and available across the users who uses this workspace file. Is there a way to achieve this?

**Comment by mhutchie** [comment]
@Satheeshkumar-Duraisamy,

The repositories are persisted per workspace, so once a user has set them up, they will be remembered.

It’s not possible at the current time for the repositories to be defined for a workspace in a config file (for a number of reasons).
