### ISSUE TITLE
Remove Checkout Branch option on selected branch

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#58]
_Absolutely not important_, but could still be a nice small improvement to juste remove the "Checkout Branch" Option when we already checkout the branch and selecting this branch again.
![image](https://user-images.githubusercontent.com/44493964/56789211-aa202480-6801-11e9-8c48-daa76da3cf1f.png)

(Could be replace with a push option)

**Comment by mhutchie** [comment]
This is a great idea! I already have the required logic removing the "Merge into current branch..." item when the context menu is on the current head, its an easy change for me to make "Checkout Branch" behave the same.

**Comment by mhutchie** [comment]
This will be available in v1.4.6. I also removed "Delete Branch..." as it's impossible to delete the checked out branch.

If you'd like to use it before the next release, you can download [v1.4.6-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.6-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
