### ISSUE TITLE
Visual Studio Code 1.61.2 Webview Bug / Installation Issue

### ISSUE THREAD

**Issue by mattiasthalen** [mhutchie/vscode-git-graph#581]
**Describe the Bug**
Git Graph is blank after applying the latest update to vs code.

**Steps to Reproduce**
1. Go to 'Source Control'
2. Click on 'View Git Graph (git log)'
3. See error

**Expected Behavior**
A visualization of the git log

**Environment**
 - Git Graph Extension Version: [1.30.0]
 - Visual Studio Code Version: [1.61.2]
 - Operating System: [Windows 10]

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/2592140/138814518-8ccdc753-bf5d-4f0b-af6e-02c12aab553b.png)

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @mattiasthalen,

Do you get any Visual Studio Code error messages (bottom right of your window) when you open the Git Graph View? If so, please provide it. It may be one of a few [Visual Studio Code Webview](https://code.visualstudio.com/api/extension-guides/webview) bugs that are currently affecting all extensions that use them (e.g. #524) - Git Graph is just one of many affected extensions.

When the Git Graph View (Webview) is open, run the "Developer: Open Webview Developer Tools" in the Visual Studio Code Command Palette, and see if there are any informative error logs relating to the Webview. Please respond with any relevant error logs.

Are there any elements in the Git Graph View that are cropped out of your screenshot (e.g. some text on the top left)?

As Visual Studio Code provides the Webview for extensions to render content in, it's up to Visual Studio Code to configure the view, and load the content instructed by the extension. The information you've provided so far leads me to believe this is a Visual Studio Code bug, or an isolated issue with your installation after updating.

Please let me know your responses and any error messages, so I can try to help diagnose this further.

FYI: Visual Studio Code 1.61.2 has been released for almost a week now, and no other users have reported any other issues to me so far.

**Comment by mattiasthalen** [comment]
Hi @mhutchie,

Thanks for taking the time.
I have no error shown in the bottom right and the command `Developer: Open Webview Developer Tools` does nothing.

Edit:
Ok, just had a reboot again, and all of a sudden it works... go figure :)

**Comment by mhutchie** [comment]
Hi @mattiasthalen,

> Ok, just had a reboot again, and all of a sudden it works... go figure :)

In the past when these sort of issues occur after a Visual Studio Code update, restarting it or their computer usually sorts it out. (hardly a satisfying answer though)

I'll close this for now as it seems to have been a one-off that is no longer affecting you.
