### ISSUE TITLE
Git Graph creates index.lock files conflicting with embedded VSC terminal git commands

### ISSUE THREAD

**Issue by Baccanno** [mhutchie/vscode-git-graph#583]
**Describe the Bug**
Most of operations needing a lock are having issues when done in the terminal while git graph window is open.
It's consistent, I need to manually close git graph window in order to make these operation work, or try them multiple time to force them to complete.
```
error: Unable to create '.../.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**Steps to Reproduce**
1. Open a terminal and git graph on same repo with VSC
2. Try rebase / cherry-pick, etc ...

**Expected Behaviour**
Operation should not fail because of index.lock file

**Environment**
 - Git Graph Extension Version: 1.30
 - Visual Studio Code Version: 1.61.2
 - Operating System: Windows 10

**Comment by mhutchie** [comment]
Hi @Baccanno,

This locking behaviour was brought to my attention by a user once before. It seemed to occur when the extension was doing an automatic refresh of the Git Graph View, while an independently run Git command was in the middle of making heaps of changes to files in the repository. It also seems to only occur under a very specific set system conditions & use cases, as you're only the second user to raise it with me out of over 1.8 million users in over 2.5 years.

There is a substantial amount of work required to resolve the current locking side effect in a good way for everyone. As there haven't been enough users affected, I currently can't justify the significant time to implement a solution to this issue. If in the future more users face this issue, or the higher priority items are implemented, I'd be happy to implement it. I appreciate that in the meantime this is negatively impacting you, however I have to ensure that all the time I spend on the extension is allocated to delivering the most net-value to the entire user community.

I'll close this issue and move it to the backlog for now, however please know I intend to re-open & implement it as soon as prioritisation allows.

**Comment by Baccanno** [comment]
@mhutchie Thanks for your time though. Indeed pretty strange that is only occured this couple of times. I'll try moving things around and it will maybe go away.

The option is maybe to use an external cli tool that would not let the focus VSC and so avoid refreshes. 
Is there any option to disable auto refresh though and only use the shortcut for it ?

**Comment by Baccanno** [comment]
I've looked into https://github.com/mhutchie/vscode-git-graph/issues/17 and associated PR. It looks like there is no optional refresh. Am I wrong ?

https://github.com/mhutchie/vscode-git-graph/commit/226a75cc4fd333585e6630ca39c7280b3fd74145#diff-bcb94b4b02c2679f4a3fb80421eef7bf1b9ebd5fccf5378e4938b9f389b0b5d4R56

Well it looks like the timer is hard coded. Should it be null I could deactivate it.

**Comment by mhutchie** [comment]
Hi @Baccanno,

The automatic refresh is not optional, and will occur whenever the Git Graph View is visible (if you switch to a different tab in Visual Studio Code, the background refresh won't occur). In general, the automatic refresh is what users expect to occur. I'm fairly confident that if there was the ability to disable it, any users that did try it out would switch back to enabling it after the realise how much they rely on it.

> Well it looks like the timer is hard coded. Should it be null I could deactivate it.

You could if you wanted to create a custom build of the extension for yourself without the automatic refresh.

**Comment by matherm-aboehm** [comment]
I have the same locking problem when doing an interactive rebase from git graph, because it also opens a new terminal in VSC to actually do the rebase while git graph has focus.
Is it possible that you change the extension to not spawn a new terminal for the rebase commands? It's already doing so, when you do a non-interactive rebase from git graph.

**Comment by NathanJPhillips** [comment]
I get the same problem every time when I do an interactive rebase from a terminal started by git graph. If I forget to close git graph first I have to redo all the rebase changes again when it fails because of this.

**Comment by a4lg** [comment]
I frequently get the same problem (especially while rebasing).  It would be nice if you consider the priority of this issue.

**Comment by MetRonnie** [comment]
I would have upvoted/reported much earlier. However I have only just narrowed this problem down to git-graph

**Comment by rolpks** [comment]
I have this problem a lot. I work on a big team maintaining a really large monorepo with a lot of outstanding branches. So the refresh time is long relative to the refresh timeout, and Git Graph basically spends the whole time holding the lock. I tried a simple commit and couldn't get that to go through right now.

**Comment by builder-main** [comment]
For everyone stumbling and as a workaroud, I started using the shortcuts allowing to fullscreen the command line. When the Graph UI is hidden there is no lock issue. I've been doing this for the last year because git graph is sill damn useful.

**Comment by rjhind** [comment]
I see this frequently too, mostly when doing an interactive rebase from the Git Graph UI context menu.

**Comment by tonyganchev** [comment]
@mhutchie it is not a rare occurrence. I hit this issue constantly and multiple times during a single rebase when I am doing a large chain of branches. I basically cannot leave along git process running while GitGraph is open.

**Comment by builder-main** [comment]
Shouldn't we find a way to disable view refresh when not in focus of git graph for instance. Or should git graph disable refresh/locks when an operation is ongoing. I guess it might be feasible ?

Some ref: 
https://stackoverflow.com/questions/47901986/how-to-tell-if-a-git-operation-is-in-progress

Maybe there is an API with VSC directly as well.

**Comment by MetRonnie** [comment]
FYI: https://github.com/mhutchie/vscode-git-graph/issues/715
