### ISSUE TITLE
Create A Checkout branch from the graph 

### ISSUE THREAD

**Issue by GKoukounis** [mhutchie/vscode-git-graph#584]
**Trying to checkout a branch from the graph  - description but is not creating it **
Hello , i was trying to checkout a branch from the graph but initially it was not getting me the checked out branched 
and i was wondering if it is possible to make it happen 

**Steps to Reproduce**
1. Go to 'Git Graph'
2. Click on 'Any committed branch you want to check out'
3. Then Right click on it a click checkout
4. Make changes and after commit them
5. After it try going back to master branch the branch checked out is no longer available

**Expected Behavior**
To be able to checkout branch from the graph and commit the new changes

**Environment**
 - Git Graph Extension Version: [e.g. v1.30.0]
 - Visual Studio Code Version: [e.g. 1.61]
 - Operating System: [e.g. Windows 10]

**Comment by mhutchie** [comment]
Hi @GKoukounis,

The use case you described is very common, and it definitely works. For something so common, if there was a bug in Git Graph it would have been raised countless times by the ~1.8 million users.

If you want to check out a branch, make sure you right click on the branch's label and select "Checkout Branch". This is different from right clicking on a commit and selecting "Checkout" (as this only checks out the commit, and should only be used in certain circumstances - hence the dialog warning).

Please reply if you have further questions, and can't work out how to achieve what you're expecting.
