### ISSUE TITLE
Rename and edit option for commits and branches.

### ISSUE THREAD

**Issue by Shadowblitz16** [mhutchie/vscode-git-graph#586]
**Describe the feature that you'd like**
Can we have a option to rename or edit any commit or branch in the graph editor by right clicking?
I know its possible with amend and rebase but the idea is it would just be easier to right click rename a branch or commit.

**Additional context (optional)**
ideally when rewriting remote history there would be a popup that says...
```
WARNING!: You are rewriting remote history do you want to continue?
- yes 
- no (default)
```

You could even have settings in the plugin to either... 
- `never allow remote history`
- `always allow remote history`
- `notify when rewriting remote history (default)`

![image](https://user-images.githubusercontent.com/2453707/141410786-abf5ff39-925f-4396-a083-20499039baf4.png)

**Comment by mhutchie** [comment]
Hi @Shadowblitz16,

**Renaming Branches:**

Any local branch can be renamed by right clicking on it's label and clicking "Rename Branch..."
![image](https://user-images.githubusercontent.com/5315753/141674236-bda55499-cf93-4680-b7f2-35e6f1c85ac2.png)

**Editing Commit Messages:**

There are two cases where this would be used:
* Edit the last commit's message: This can be achieved through Visual Studio Code's built-in Git Extension. Git Graph leaves committing-related functionality to the built-in Git Extension as it already provides a very extensive set of capabilities that cover almost all use cases. If the extension were to implement some of these features, it would just be duplicating functionality. I focus on implementing new features that aren't already available in Visual Studio Code, or features that benefit from a graphical interface.
    * ![image](https://user-images.githubusercontent.com/5315753/133922496-742e7d8e-d3e9-4d21-b2f8-214769a03ff0.png)
* Edit a historical commit message: This is rarely done as it's generally considered bad practice to "rewrite history" in Git repositories. Therefore I don't currently provide a dedicated action in the context menu for it, however it can be achieved by choosing the interactive option with "Rebase current branch on this Commit...".

The Commit context menu is already quite full, so until I support submenu's in context menu's, I'm postponing adding any new less frequently used actions. However, once submenu's are supported, I intend review all features that may not have previously been feasible. This should allow many less frequently used actions (including some of the popular rebasing options - like rewording), to be included. I'll add this feature request to the back log for now, with the intention of implementing it in the future.
