### ISSUE TITLE
why is the git-graph icon not showing on status bar in VS Code

### ISSUE THREAD

**Issue by spider-eu** [mhutchie/vscode-git-graph#593]
![Screenshot from 2021-11-26 08-58-53](https://user-images.githubusercontent.com/93572913/143523409-a4574d88-79a3-4769-a6ef-04d27f68141b.png)

**Comment by spider-eu** [comment]
solved

**Comment by iulianraduat** [comment]
@spider-777 How did you solved it? Thanks

**Comment by spider-eu** [comment]
@iulian-radu-at, I reinstalled the extension, as well as vscode. After that, it appeared in the status bar. The real reason is still a mystery to me.

**Comment by Stefan13-13** [comment]
I had this to, but it turned out I had the wrong folder open in Visual Studio Code which was not initialized as a Git repository. So someone ending up here in the future can double check this right away ;). Hope it helps.

**Comment by dkorobchenko** [comment]
Git Graph icon is not showing on status bar, if installed in WSL environment.
In regular Windows environemnt it works normally.
If I uninstall and the install Git Graph extension again -- the icon appears in the status bar.
But it dissapears again if I reload CSCode

**Comment by csmyx** [comment]
this problem still exists in WSL2 environment。:(

**Comment by MilanSkocic** [comment]
Same problem on MacOS even after reinstalling VSCode and the extension.

**Comment by Hadatko** [comment]
I have same issue. Unable to stage/unstage files.

**Comment by wdzeng** [comment]
Same issue. It appears when VSCode just loads, but disappears whenever I open any file.

**Comment by AdoKevin** [comment]
Same issue, only occurred with remote-ssh from Windows to linux, and seems this issue is intermittent, and if it occurs, trying to reopen VSCode can solve it. It's a very strange.

**Comment by AdoKevin** [comment]
> Same issue, only occurred with remote-ssh from Windows to linux, and seems this issue is intermittent, and if it occurs, trying to reopen VSCode can solve it. It's a very strange.

After some research, it seems I've found a workaround to this problem. I changed the `activationEvents` of the plugin from `*` to `onStartupFinished`, and tested it for a while and this issue hasn't reappeared, although I'm not certain if this is the root cause, as I'm not an expert here.

Since it appears that this project is no longer maintained, I've submitted the changes to my fork. Others facing the same issue can give it a try.

**Comment by pouss06** [comment]
Thanks @AdoKevin , btw for those who are seeking, the settings file is under:
~/.vscode/extensions/mhutchie.git-graph-1.30.0/package.json
The file will be override if any update is made, but as the project is not maintained, it will do the job.

**Comment by wdzeng** [comment]
Sad to hear this is no longer maintained. @AdoKevin did you have plans to take over this extension?

**Comment by AdoKevin** [comment]
> Sad to hear this is no longer maintained. @AdoKevin did you have plans to take over this extension?

The great extension already meets my requirements quite well. If I encounter any issues like this, I'll try to fix them. As for new features, I don't have any specific needs at the moment. If you have any ideas, feel free to raise an issue in the repository I forked. I am willing to contribute to the community when I have time. But I'm not quite sure about the current license of the project.

**Comment by wdzeng** [comment]
I looked at the license and #715 , it seems that even you can fork the repo, you cannot publish a forked extension on vscode 🥲🥲

**Comment by m4ss1m0g** [comment]
Seem to be very painful but you can start to fork and publish a new extension from version [1.4.7](https://github.com/mhutchie/vscode-git-graph/tree/v1.4.7-beta.0) BEFORE the modified license.

**Comment by eduardo4jesus** [comment]
I solved it by removing Rewrap

```
Name: Rewrap
Id: stkb.rewrap
Description: Hard word wrapping for comments and other text at a given column.
Version: 1.16.3
Publisher: stkb
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=stkb.rewrap
```

**Comment by art2url** [comment]
<img width="438" alt="Screenshot 2024-10-04 at 13 27 12" src="https://github.com/user-attachments/assets/18afefc9-e369-4b48-a925-8691a6a34aff">

Hey guys, just got the same problem and the solution was simple – just enable the Git Graph button on the source control. Extension will also appear in the status bar.

**Comment by eduardo4jesus** [comment]
> just enable the Git Graph button on the source control.

I have that enabled. But it still does not show in the status bar. `Rewrap` seems to be interfering with it.

**Comment by zhaohuiwang** [comment]
There are my solutions. Environment: Window11 pro / WSL / VSCode / Ubuntu

Install/setup Git, Git Graph extensions
Go to Extension search by extension names, once found install them
If “No source control providers registered” in Source Control. Put @builtin git in Search Extensions in Marketplace bar in Extension > Click Git in gray and Enable.

If Git Graph extension for VSCode not showing in the bottom status bar
Go to Setting > Settings > extension settings > search for "Git-graph: Max Depth Of Repo Search" > look into Git Graph extension > it might be zero. Change it to 1 or 2.

**Comment by haughki** [comment]
> Git Graph icon is not showing on status bar, if installed in WSL environment. In regular Windows environemnt it works normally.

> this problem still exists in WSL2 environment。:(

I've use Git Graph in WSL 2 for years. It only recently stopped working for me, and I don't think it's related to WSL 2 at all. I recently installed Rewrap (see @eduardo4jesus comment above). I've disabled it, reloaded, and the Git Graph button appeared.

**Comment by Danjd-coder** [comment]
Hey guys, just got the same problem and the solution was simple:

![Image](https://github.com/user-attachments/assets/2c3df0c8-ca97-48ec-b412-34a5fe711180)

then just drug and drop "SOURCE CONTROL" to the left and extension will also appear.

![Image](https://github.com/user-attachments/assets/4626d9ed-4cad-4fb5-b0fd-441e891ae402)

**Comment by cameronfrye-eaton** [comment]
> I've use Git Graph in WSL 2 for years. It only recently stopped working for me, and I don't think it's related to WSL 2 at all. I recently installed Rewrap (see [@eduardo4jesus](https://github.com/eduardo4jesus) comment above). I've disabled it, reloaded, and the Git Graph button appeared.

I've been using the "Rewrap Revived" extension and by removing this extension the issue was solved for me as well. It is only necessary to remove the extension locally in WSL. It seems like I can still use "Alt+Q" and wrap text so I'm happy with this.
