### ISSUE TITLE
How to Reset Repo Settings?

### ISSUE THREAD

**Issue by markm77** [mhutchie/vscode-git-graph#599]
I have a large number of repos (projects) in a workspace and I noticed e.g. some are not responding to `git-graph.defaultColumnVisibility` as I believe repo-level settings were applied at some point? How do I clear such settings - either repo by repo or for all repos? I couldn't find a way....

**Comment by mhutchie** [comment]
Hi @markm77,

Background: For the vast majority of the repository settings, there is a Git Graph extension setting that can be used to specify the preferred behaviour at a user or workspace level (via the Visual Studio Code Settings interface). The setting can then be overridden per repository via the Git Graph View interface.

Once a setting has been overridden at a repository level, there currently isn't an easy way to clear the override, and go back to using the default value from the Git Graph extension setting.

FYI: The `git-graph.defaultColumnVisibility` extension setting is the only exception to the above rule. When a repository is first viewed in the Git Graph View, the repository's column visibility is initialised according to this extension setting. From that point onwards, the column visibility is only controlled via the Git Graph View's column headers. *(there are good reasons why this extension setting is treated differently to the rest)*

---

Currently, the best way to achieve what you're requesting is to:
1. (Optional) Export your current Repository Configuration
    * ![image](https://user-images.githubusercontent.com/5315753/145708035-16e1dcc2-fe1b-41a1-bb12-36866531f2ae.png)
    * Once exported, a file `./.vscode/vscode-git-graph.json` will be added to your repository. You can review this file, and delete any repository-level configuration and/or overrides you wish to discard.
    * When you do Step 3, any configuration in `./.vscode/vscode-git-graph.json` will be restored.
2. Run `Git Graph: Remove Git Repository...` in the Visual Studio Code Command Palette to remove the Git repository from Git Graph. This will clear all repository level state stored in the extension.
3. Run `Git Graph: Add Git Repository...` in the Visual Studio Code Command Palette to add the Git repository back into Git Graph.
4. (Optional) If you chose to do Step 1, you can delete `./.vscode/vscode-git-graph.json` as it's no longer needed.

**Comment by markm77** [comment]
Hi @mhutchie , thanks for the quick and helpful response. Actually seems all I need to do is your step (2) and then click the repo's Git Graph icon under Source Control / Source Control Repositories to view the repo's log with reset settings. A shame this has to be done repo by repo though. I did try uninstalling/reinstalling Git Graph but it doesn't clear repo settings.

> (there are good reasons why this extension setting is treated differently to the rest)

I understand but please be aware this makes it seem `git-graph.defaultColumnVisibility` is broken as it has no effect on a previously-viewed repo. Certainly that's what I initially thought and was considering filing a bug report.
