### ISSUE TITLE
Add the word "log" to command name

### ISSUE THREAD

**Issue by borekb** [mhutchie/vscode-git-graph#6]
For discoverability, it would be great if the command palette found the "graph" command even for a "git log" search term. The [Git History](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory) extension does that:

![image](https://user-images.githubusercontent.com/101152/52998952-d0ea6500-3424-11e9-8846-908216374b0b.png)

**Comment by borekb** [comment]
Awesome extension, by the way!

**Comment by mhutchie** [comment]
Thanks for the suggestion! The name of the command in the Command Palette now is "Git Graph: View Git Graph (git log)". Ready for the next release.
