### ISSUE TITLE
Repository search improvement (same named Repositorys in subfolders)

### ISSUE THREAD

**Issue by iMarc92** [mhutchie/vscode-git-graph#60]
Improvement for Repository search in subfolders.
If you have same named Repository in subfolders, you got a problem to pick the right one.
Maybe you can add a hover/Infobox to show the folder path (last 2 foldernames or something else).

![grafik](https://user-images.githubusercontent.com/12292086/56968692-ed60f700-6b63-11e9-855a-f622b0b89d97.png)

**Comment by mhutchie** [comment]
Thanks for pointing this out, I’ll put some logic in to make sure two subfolders with the same name can be differentiated.

**Comment by mhutchie** [comment]
This will be available in the next release, which will be either v1.4.7 or v1.5.0.

If you'd like to use it before the next release, you can download [v1.4.7-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.7-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by iMarc92** [comment]
Wow, that was a fast improvement :)
I will test it tomorrow 👍

**Comment by iMarc92** [comment]
Works great :) Thank you!
