### ISSUE TITLE
Re-attach HEAD when checking out latest commit again

### ISSUE THREAD

**Issue by lprc** [mhutchie/vscode-git-graph#600]
**Describe the improvement that you'd like**
It would be great if HEAD was no longer detached when re-checking out master while being in detached head mode.

**Additional context (optional)**
Consider the following steps to reproduce (see image also):
1. Be on latest commit on master
2. checkout older commit on master -> detached head
3. checkout latest commit on master again via context menu -> still detached head

After step 2, if I checkout master again via `git checkout master` using the command line my HEAD is no longer detached so I was expecting the same behaviour using this extension.

Here's an image showing the 3 steps from above including the top of GitHub Desktop so you can see when HEAD gets and remains detached:

![gitgraph_detached_head](https://user-images.githubusercontent.com/13603403/145829141-8461ab19-474d-4597-9d60-dd5dff542e64.png)

Thank you for this wonderful vs code extension!

**Comment by mhutchie** [comment]
Hi @lprc,

Please be aware that there is a distinction between checking out a branch and checking out a commit:
* **Checking out a Branch**: When you right click on a branch label (e.g. "master") and select "Checkout Branch", it will checkout the branch. This is the equivalent of `git checkout master`, and your repo will no longer be in a detached head state. (you can also double click on the branch label to perform a checkout)
* **Checking out a Commit**: When you right click on a commit, and select "Checkout..." it will checkout that specific commit, causing a detached head.

There is also a subtle visual indicator between these scenarios:
* When the **branch is checked out** in your first screenshot, "master" is bolded, and the label's border is coloured to match the branch.
* When the **commit is checked out** in your third screenshot, the "master" branch label doesn't have this formatting and appears the same as any other branch.

**Comment by babipsylon** [comment]
So, checking out a Branch will attach the head back to the latest commit in that branch when you were in a detached head state? Bit weird way of achieving this. But I'm looking for a way to achieve this and if this works, great. Don't know any other way.
