### ISSUE TITLE
Make git-graph work with code-server

### ISSUE THREAD

**Issue by t-d-d** [mhutchie/vscode-git-graph#61]
**Describe the feature that you'd like**
We're moving to hosted VSCode, see https://github.com/cdr/code-server .  We're looking for a VSCode-based git log explorer and this extension stands out.

However I can't get it to work in code-server.  A number of issues:
1) git-graph isn't in code.com's extension repo.  I installed manually.
2) Get the error 'Unable to load Git Graph...'  Git is in the path and I also tried setting git.path.  This seems to be related to multi-folder project.  If I `git init` in the root folder, the error goes away.
3) If enabled at startup, git-graph seems to cause the extension host to time out causing loads of extension not to load
4) Graph display didn't work.

Git Graph 1.4.6
Host environment is ubuntu 18.10 (in docker.)  The project folder is mounted into the container (may be relevant to 1 because of the filesystem boundary.)
**Additional context (optional)**
Git lense and most other extensions work fine in code-server.  Would be great to be able to compliment it with git-graph.

**Comment by mhutchie** [comment]
Hi Thomas,

I hadn't come across code-server before, hosted VSCode solutions seem quite useful!

After setting up an Ubuntu instance and installing code-server, I was able to get the Git Graph view to open, but not display (I assume this is what you observed in point 4). After looking into why it didn't load, it appears to be related to the code-server handling of the [Webview API](https://code.visualstudio.com/api/extension-guides/webview), which Git Graph uses to render its view. It appears that the `vscode-resource` scheme, which is used for accessing file system resources from within Webviews, is not correctly handled, preventing the Git Graph view from rendering. I also had a search for code-server supported extensions, I couldn't find any that use the `vscode-resource` scheme.

I'll close this issue for now as it appears this is currently a limitation with code-server. If code-server does properly support the `vscode-resource` scheme in a future release, I'll have a look into making Git Graph available for code-server users.

**Comment by t-d-d** [comment]
Michael - thanks for taking the time to investigate.

**Comment by thekingofcity** [comment]
Looks like `code-server` couldn't fix this either cdr/code-server#817. 😫
