### ISSUE TITLE
Multiple entries for issue linking

### ISSUE THREAD

**Issue by Chrismettal** [mhutchie/vscode-git-graph#612]
If a project uses more than one bug tracker for the same repo or the tracker can have different prefixes for the issues, currently you can only have git-graph detect and link to one of the bug trackers.

For example, a tracker `jira.fakecompany.com/<ticket>` could have tickets like "XYZ-12345" as well as "abcd-12345" and currently I can only have one of those be automatically detected.

With more regex knowledge I might be able to make this scenario work, but if we start adding a second issue tracker then the regex would need to point to another URL.

**Comment by mhutchie** [comment]
Hi @Chrismettal,

Thanks for raising this feature request, this is definitely a capability I want to implement in Git Graph!

I’ll close this request, as it’s covered by the existing feature requests #313 & #451.
