### ISSUE TITLE
Open to the repo of the active text editor document doesnt work

### ISSUE THREAD

**Issue by peterdickx** [mhutchie/vscode-git-graph#617]
When i set this setting to true, the git graph doesnt open to the repo of the active text editor

![gitgraphopen](https://user-images.githubusercontent.com/19954023/151353513-634ba35c-3fac-4c0f-aa3c-8d040ef9bbc2.png)

**Comment by mhutchie** [comment]
Hi @peterdickx,

I've double checked this extension setting is definitely functioning as it was designed, using the latest version of Visual Studio Code & Git Graph.

The current behaviour is:
1. User requests to open the Git Graph View (either by the Status Bar Item, or the "View Git Graph" command in the Visual Studio Code Command Palette)
2. The extension gets the path of the active text editor document, and checks whether it is contained within any of the repositories known to Git Graph.
    - If so, the repository will be loaded when the Git Graph View is opened.
    - If not, open the Git Graph View to the last viewed repository.

Please note: This only applies when the Git Graph View is being opened, _not_ when switching between tabs in Visual Studio Code.

This feature has been available for years, and no other users have ever indicated that it didn't function as they expect. As you haven't provided steps to reproduce the issue you're facing, this is the best response I can provide given the current information.

I hope this explanation resolves any confusion you may have around the behaviour of this extension setting. If not, please respond to this issue with further information (as outlined in the Bug Template), so I can either:
- provide further clarification.
- reproduce the behaviour you're observing, and re-open this issue as a bug if there is some specific edge case that no other user has previously reported.
