### ISSUE TITLE
Amend commit message

### ISSUE THREAD

**Issue by ericxyan** [mhutchie/vscode-git-graph#619]
**Describe the feature that you'd like**
I would like to edit a commit message when right click on a commit.
**Additional context (optional)**
 A feature like [Edit a commit message](https://www.jetbrains.com/help/idea/edit-project-history.html#reword-commit) in IntelliJ.

**Comment by mhutchie** [comment]
Duplicate of #520.

I gave a more recent response with some additional information under the "Editing Commit Messages" header in my comment https://github.com/mhutchie/vscode-git-graph/issues/586#issuecomment-968254562.
