### ISSUE TITLE
Add docs about how to show non-ASCII file names properly

### ISSUE THREAD

**Issue by kazuma1989** [mhutchie/vscode-git-graph#62]
**Describe the improvement that you'd like**
Add docs about how to show non-ASCII file names properly.

This is the command:
```sh
git config --global core.quotepath false
```

**Additional context (optional)**
I found that the extension shows incorrect non-ASCII filenames in diff panel.
First I thought this is a bug because the VS Code's native Git panel shows correct non-ASCII filenames.

<img width="1007" alt="スクリーンショット 2019-05-05 15 23 43" src="https://user-images.githubusercontent.com/15844862/57189449-e8c48600-6f49-11e9-8822-558d6e496304.png">

After some investigating, I found this is not a bug but a limitation that comes from Git options.
`core.quotepath` is true by default so I have to set the option false.

---

The extension is super awesome, thank you for creating it!
This issue is a note to self but I want it might help someone who uses the extension and might support contributors.

**Comment by mhutchie** [comment]
Thanks for spotting this and letting me know!

I should be able to adjust the handling of file names so this works without having to change any settings.

**Comment by mhutchie** [comment]
This will be available in v1.5.0.

If you'd like to use it before the next release, you can download [v1.5.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.5.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
