### ISSUE TITLE
Allow user to specify git executable path

### ISSUE THREAD

**Issue by tapr00t** [mhutchie/vscode-git-graph#620]
Please add a setting to allow the user to override the git executable path, or use the path defined in the existing "git.path" setting.  I'm noticing that git graph is not using that git executable.

**Comment by mhutchie** [comment]
Hi @tapr00t,

Please read the documentation on [Git Executable Detection](https://docs.mhutchie.com/vscode-git-graph/general/git-executable-detection). It explains the extension's behaviour, and when the `git.path` setting is used.
