### ISSUE TITLE
Allows to name branch with space, and replace it with "-"

### ISSUE THREAD

**Issue by DavidBabel** [mhutchie/vscode-git-graph#622]
**Describe the feature that you'd like**
Allows to name branch with space, and replace it with "-"

**Additional context (optional)**
This is a common easy feature on most of visual git managers

**Comment by mhutchie** [comment]
Hi @DavidBabel,

This feature was already implemented and released in Git Graph 1.30.0:

> #471 Spaces can be automatically substituted with hyphens or underscores in reference inputs on dialogs (e.g. Create Branch, Add Tag, etc.), by configuring the new extension setting `git-graph.dialog.general.referenceInputSpaceSubstitution`.
