### ISSUE TITLE
Automatic refresh after terminal commands

### ISSUE THREAD

**Issue by sereyn** [mhutchie/vscode-git-graph#628]
**Describe the feature that you'd like**
Some weeks ago, I was using the extension mostly as a graph viewer while I was typing git commands in the vscode integrated terminal. That was nice because the graph was refreshing automatically after I typed a command, but now it doesn't resfresh automatically anymore, I would like to see this feature back.

**Comment by mhutchie** [comment]
Hi @sereyn,

As all terminals (including the Visual Studio Code Integrated Terminal), are a completely independent processes from the extension, the only way for Git Graph to detect the changes made externally by Git commands is to monitor the File System for changes in the repository.

As recommended by Microsoft, the extension uses a Visual Studio Code [FileSystemWatcher](https://code.visualstudio.com/api/references/vscode-api#FileSystemWatcher) to achieve this. In the past, Microsoft has occasionally introduced regressions to the FileSystemWatcher for some operating systems, which they usually resolve shortly after.

I've checked multiple computers using the latest Git Graph & Visual Studio Code release, and the extension's automatic refresh capability is working correctly for me. No other users have reported this issue either.

As the extension hasn't been updated in months, and Visual Studio Code has had multiple recent releases, the regression you describe must have been introduced in a recent Visual Studio Code release. As mentioned above, Microsoft will likely resolve this shortly, and therefore this issue also will be resolved at the same time.
