### ISSUE TITLE
enable git-graph.useMailmap by default

### ISSUE THREAD

**Issue by BMBurstein** [mhutchie/vscode-git-graph#629]
Currently the setting `git-graph.useMailmap` is disabled by default. I hadn't realized this setting even exists, and was very confused when `git log` was showing something different than git-graph. I think that since git uses `.mailmap` by default (I don't even know if there is a way to disable it), git-graph should use it, too, in order to prevent discrepancies by default between `git` and git-graph

**Comment by mhutchie** [comment]
Hi @BMBurstein,

When using Git mailmap, it requires Git to do more work when retrieving every commit that's requested by Git Graph. As only a few users have ever indicated they want / use this capability, it didn't seem right to enable this setting by default for everyone, as it would somewhat degrade the performance of the extension for the 99.9% of users that get no value from mailmaps. With all extension settings, I carefully consider what the default value should be, trying balance the pro's & con's to chose an option that offers the best net value across all extension users.

I'll close this request and move it to the backlog for now. However, if more users indicate they'd like this extension setting enabled by default, I'd happily re-open it and make this change.
