### ISSUE TITLE
merge option to use "git merge --squash"

### ISSUE THREAD

**Issue by iMarc92** [mhutchie/vscode-git-graph#63]
It would be nice, when we had an option to use "git merge --squash"

If you have an feature branch with 100+ commits i dont want them all in master and it`s much easier to implement than rebase.

Maybe there is already an option, but i didnt see them :) .

**Comment by mhutchie** [comment]
Thanks for the suggestion, this would be really useful!

**Comment by mhutchie** [comment]
This will be available in v1.5.0.

If you'd like to use it before the next release, you can download [v1.5.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.5.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
