### ISSUE TITLE
Don't scroll when clicking commit to expand/collapse

### ISSUE THREAD

**Issue by jacobweber** [mhutchie/vscode-git-graph#630]
**Describe the feature that you'd like**
Right now when you click a commit to collapse or expand it, the window almost always scrolls. I'd prefer (an option) to disable this, since it makes me lose my place.

**Comment by mhutchie** [comment]
Hi @jacobweber,

I believe your request will likely already be achieved by disabling the [`git-graph.commitDetailsView.autoCenter`](https://docs.mhutchie.com/vscode-git-graph/general/extension-settings#auto-center) extension setting. Disabling this extension setting will stop the commit from automatically being scrolled to the center of the view. With this extension setting disabled, the only time the view will scroll is if the Commit Details View would extend past the bottom of the window and not be readable (in this case, the view scrolls just enough so the Commit Details View is readable).

Additionally, you may also like to try changing [`git-graph.commitDetailsView.location`](https://docs.mhutchie.com/vscode-git-graph/general/extension-settings#location) to "Docked to Bottom" - some users prefer it.

Please try these existing extension settings first, as all other users have found them to be more than sufficient. If not, please let me know and I can re-open this request, and we can explore other potential solutions

**Comment by jacobweberbowery** [comment]
Thanks @mhutchie — didn't know about those settings. I think I can make do with that, and just avoid expanding near the bottom of the window when I'm concerned about losing my place.
