### ISSUE TITLE
Git Graph can't load my file

### ISSUE THREAD

**Issue by cianyastone** [mhutchie/vscode-git-graph#631]
My Git Graph always load the graph of upper file, but I need it to be the file "expo-wk3".
How to deal with it? 
It really confused me for a long time :(.

https://user-images.githubusercontent.com/71207467/156504049-94a83c03-f583-453d-81a8-eae7fca1b5e0.mov

**Comment by mhutchie** [comment]
Hi @cianyastone,

Unless you've manually overridden the name of your repository to "Desktop", I suspect the repository shown in Git Graph is the "Desktop" repository, and you're opening the "expo-wk3" folder in Visual Studio Code (that's contained within the "Desktop" repository).

If you run the Git command `git rev-parse --show-toplevel` in a Terminal, you can identify which repository contains the current directory.

Although repositories are automatically detected when Visual Studio Code is opened, you can manually override the repositories shown in Git Graph using the `Git Graph: Add Git Repository...` and `Git Graph: Remove Git Repository...` commands in the Visual Studio Code Command Palette. Depending on your issue, these commands may be of some use to you. You shouldn't use them unless absolutely necessary.

I'll close this question for now, as I've provided the best answer I can from the information you've provided. However, if you have any further questions please reply to this thread, as I'll still be notified and reply to them.
