### ISSUE TITLE
Fix top bar while scrolling

### ISSUE THREAD

**Issue by gtnIIS** [mhutchie/vscode-git-graph#636]
When scrolling down in git-graph the bar at the top (containing dropdowns with repo name, branch name, update and search buttons...)  will move out of the window. That means to switch the displayed repo or search for a certain commit, I have to scroll all the way up again, which is cumbersome.  
  
*Suggestion*  
Fix the top bar when scrolling in git-graph  
  
*Current state*
Top bar moves out of the window when scrolling down.

**Comment by TheBrenny** [comment]
Being worked on at #394.

**Comment by gtnIIS** [comment]
Thanks. I'll follow that and close this issue here.
