### ISSUE TITLE
Missing support for git ssh signing

### ISSUE THREAD

**Issue by sebastinez** [mhutchie/vscode-git-graph#638]
**Describe the Bug**
Since git 2.34.0, there is support for signing commits with a SSH key, for that to be possible one has to add `gpg.format = ssh` to their git config.
Now when doing that the extension does not load and shows the following error `error: unsupported value for gpg.format: ssh
fatal: bad config variable 'gpg.format' in file '.git/config' at line 9`

**Steps to Reproduce**
Add `gpg.format = ssh` to your git config globally or to a local project you want to see a git graph

**Expected Behaviour**
I don't expect SSH keys to be working in the extension but the extension should show the graph no matter which way of commit signature is being used.

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.65.2
 - Operating System: macOS 12.3

**Screenshots (optional)**
<img width="495" alt="Bildschirmfoto 2022-03-24 um 15 44 38" src="https://user-images.githubusercontent.com/7912302/159942094-6da663ee-9e9a-435c-8f65-f568f2e4d84a.png">

**Comment by jochemkeller** [comment]
@sebastinez I ran into this problem today after migrating to SSH key signing. Not sure if you still need help, but I fixed it by explicitly setting the following in my global VS Code settings:

```json
{
  "git.path": "<path to your git>",
}
```

You can obtain your git path by opening a terminal instance in VS Code and executing the following:

```shell
which git
```

I use [Homebrew](https://brew.sh) myself, so in my case the resulting settings addition was:

```json
{
  "git.path": "/opt/homebrew/bin/git",
}
```

I suspect — without setting this override — VS Code utilises the macOS system version of Git, which isn't the required 2.34.0 at time of writing (macOS Monterey 12.5.1).

Hope this helps!

@mhutchie thanks for an amazing extension. I literally can't git without it 💪

**Comment by sebastinez** [comment]
🤯 Thank you so much @jochemkeller! This solved my issue and I'm finally able to go back using Git Graph!
Also thanks @mhutchie for this extension, it is really needed! 👏 

Will close this issue, hope it helps others who stumble upon this.

Maybe there is a place somewhere to write this down outside of this issue for others stumbling upon this issue.
