### ISSUE TITLE
Delete remote branch?

### ISSUE THREAD

**Issue by vfonic** [mhutchie/vscode-git-graph#64]
**Describe the feature that you'd like**

It would be cool to be able to open context menu (right click) on a remote branch name and have the option to remove the branch. This is possible with the following command:
`git push $remote --delete $feature_branch`

Thanks!

**Comment by mhutchie** [comment]
Thanks for the suggestion! This is scheduled for the next release.

**Comment by mhutchie** [comment]
This will be available in v1.5.0.

If you'd like to use it before the next release, you can download [v1.5.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.5.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
