### ISSUE TITLE
How can I hide the gh-pages branch

### ISSUE THREAD

**Issue by alanlivio** [mhutchie/vscode-git-graph#655]
How can I hide one of the gh-pages branch?
The extension settings only have the   "git-graph.repository.showRemoteBranches" to hide all remote ones.

**Comment by kenji-miyake** [comment]
It would be nice if this feature is supported!

@alanlivio As a workaround, I think the `Unselect in Branches Dropdown` button can be used.
![image](https://user-images.githubusercontent.com/31987104/173274023-c9bae13e-0fa8-4db8-b52b-75b24a82e17e.png)

**Comment by alanlivio** [comment]
Many thanks @kenji-miyake. It works. But I still thing that it may be done by some json vsconfig given the recurrence, so otherse it requreded to be done for each repo. So, can I made a feature request?

**Comment by kenji-miyake** [comment]
I agree with you, but I'm not sure you can make a feature request because I'm not a maintainer. :disappointed:
