### ISSUE TITLE
Show commit details at bottom without disrupting graph

### ISSUE THREAD

**Issue by positron96** [mhutchie/vscode-git-graph#660]
**Describe the feature that you'd like**
First of ll, thanks for a very useful plugin!

It would be nice to have commit details not inside the graph but somewhere else. Most git browsers that I've used (gitk, SmartGit, TortoiseGit) show commit details at the bottom of the window. This way when you click-through commits you don't have to aim at different places all the time, the commits are where they were before previous click. Also part of graph moves when details open/close, this gives visual distraction.

**Comment by mhutchie** [comment]
Hi @positron96,

This feature is already available via the extension setting [`git-graph.commitDetailsView.location`](https://docs.mhutchie.com/vscode-git-graph/general/extension-settings#location).

**Comment by positron96** [comment]
Thank you very much! For some reason, I missed that setting.
