### ISSUE TITLE
Add option not to centre the view on the expanded commit

### ISSUE THREAD

**Issue by krupenja** [mhutchie/vscode-git-graph#7]
**Describe the feature that you'd like**
Consider the current behaviour:
1. Open Git Graph.
2. Click on a commit.

The view jumps so that the expanded commit is centred. This results in a visible flicker.  I would suggest adding an option for the graph not to move when a commit is clicked on.

**Comment by mhutchie** [comment]
Great suggestion, I'll add this for the next release!

**Comment by mhutchie** [comment]
This will be available in v1.4.0.

If you'd like to use it before the next release, you can download [v1.4.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
