### ISSUE TITLE
UI: move branch name to a separate column

### ISSUE THREAD

**Issue by yzhang-gh** [mhutchie/vscode-git-graph#71]
**Describe the feature that you'd like**

Add a column for branch name so that the commit messages are aligned

**Additional context (optional)**

![current](https://user-images.githubusercontent.com/7588612/57587185-dffb2380-74f8-11e9-8da8-2260ce8eba62.png)

**Comment by mhutchie** [comment]
Thanks for the suggestion! This would be nice if there was only ever one branch or tag per commit, but it’s quite common for multiple to occur on the same commit, especially when the repo has a remote, so almost all branches have pairs plus any tags. How do you think multiple labels should be handled, as I don’t think they should be constrained to a column width as some labels would be hidden if they overflow, and if they weren’t constrained, the amount of available commit text would be significantly reduced to fit with the longest label set of a commit in the table.

**Comment by yzhang-gh** [comment]
Thanks for the reply.

Then I would suggest making the tags right-aligned. A quick mockup

![image](https://user-images.githubusercontent.com/7588612/57588559-ec3dab80-750d-11e9-9354-86e65eb98c7d.png)

**Comment by mhutchie** [comment]
Thanks for the idea, I’ll try it out and see what works the best for keeping commit messages aligned.

**Comment by mhutchie** [comment]
I've added three reference label alignment options, I think the last one will work well for you. The alignment options are configured by the new setting `git-graph.referenceLabelAlignment`, and are:
* Normal: Show branch & tag labels on the left of the commit message in the 'Description' column.
* Branches (on the left) & Tags (on the right): Show branch labels on the left of the commit message in the 'Description' column, and tag labels on the right.
* Branches (aligned to the graph) & Tags (on the right): Show branch labels aligned to the graph in the 'Graph' column, and tag labels on the right in the 'Description' column.

This will be available in v1.6.0.

If you'd like to use it before the next release, you can download [v1.6.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

Please reply letting me know if the last option works for you. I tried multiple alignment options, but found that the three above worked well for a broad range of repos with different branch and tag usage patterns. Other alternatives, including the two options you suggested, didn't feel as smooth, intuitive, and easy to use & understand when they were fully implemented, however I'd be happy to revisit them if none of the options I have done work well for you.

**Comment by yzhang-gh** [comment]
Just tried it out. I am happy with the last option. Thank you so much!

**Comment by mhutchie** [comment]
Awesome, thanks for trying it out!

**Comment by yzhang-gh** [comment]
Have to say the last option is really intuitive.

![image](https://user-images.githubusercontent.com/7588612/58130398-d322b200-7c13-11e9-8aff-e2a574d77f21.png)

This is awesome!
