### ISSUE TITLE
Diff'ing branches as a whole

### ISSUE THREAD

**Issue by niccolomineo** [mhutchie/vscode-git-graph#714]
It would be great to be able to diff a whole branch content against another's.

When you open a PR, you have a unified view for what was added in that whole branch. The usefulness is that, if you want to check a specific file's changes and have a hundred commits, you don't have to go through each commit to see whether that file was changed and how.

**Comment by bobatsar** [comment]
Hey @niccolomineo you can do this already. You just have to select both commits with the ctrl key pressed down. Then you can compare different commits (and you can of course also take two commits from different branches. I also had to search for this functionality and found it in one of the tickets here.

**Comment by niccolomineo** [comment]
Awesome, thanks. I had no clue.
