### ISSUE TITLE
Filter graph by file and Author and open filter input

### ISSUE THREAD

**Issue by seetpalsingh** [mhutchie/vscode-git-graph#72]
**Describe the feature that you'd like**
I was using **git history**. but, I like the graph you created clean and better visibility.
But, I like your version. I request for a new feature for filter the history as Author and an open input field as a random search option.

**Additional context (optional)**

![Screen Shot 2019-05-13 at 1 09 44 PM](https://user-images.githubusercontent.com/4477434/57603879-732b6c00-7580-11e9-99f0-4ba2553cdd2b.png)

**Comment by mhutchie** [comment]
Thank you for these suggestions! Both of them will be implemented as part of #31 (Text box for search logs - including author), & #70 (Filtering by file).
