### ISSUE TITLE
i like commit detail info view in seperated window.

### ISSUE THREAD

**Issue by sim511777** [mhutchie/vscode-git-graph#74]
**Describe the feature that you'd like**
i like commit detail info view in seperated window.
when i click on a commit item, graph is spreaded and there shows commit detail info.
i want git graph shape is static.
like git history do.

**Comment by mhutchie** [comment]
Thanks for this suggestion! I'll add support for this in an upcoming release.

**Comment by mhutchie** [comment]
This will be available in v1.5.0, which will be released soon.

**Comment by yzhang-gh** [comment]
Thank you @mhutchie. The docked view looks better. I would suggest making it the default setting.
