### ISSUE TITLE
Restore/Open Git Graph Editor View when vscode window reloads/opens

### ISSUE THREAD

**Issue by rosmcmahon** [mhutchie/vscode-git-graph#767]
**Describe the feature that you'd like**
Option to automatically restore the Git Graph editor view when vscode reloads or restarts. This should also pin the editor if it was previously pinned.

**Additional context (optional)**
When the window closes, I need to click on the Git Graph status bar button below to reopen and then right-click the editor title to re-pin it. it's tedious as i usually have many windows open and always use Git Graph in this way.

**Comment by rosmcmahon** [comment]
this seems like a pretty obvious feature, but i checked through previous PRs and Issues and didn't come across anything related. apologies if i'm repeating previous conversations.

**Comment by phil294** [comment]
here you go #589 #590 #675 #348 #276

#675 also contains a nice workaround :-)

**Comment by rosmcmahon** [comment]
hmm, i'm not familiar with `tasks` in vscode, but this workaround doesn't seem to work, plus it is starting random language tools all over the place, which all seem to be failing

**Comment by rosmcmahon** [comment]
ok, thanks for your efforts :-)
