### ISSUE TITLE
Revert design changes

### ISSUE THREAD

**Issue by mindplay-dk** [mhutchie/vscode-git-graph#783]
Why these drastic design changes?

Before:

![Screenshot 2023-09-01 121614](https://github.com/mhutchie/vscode-git-graph/assets/103348/6014760a-bee4-4aea-a645-1054ed0bd6db)

After:

![Screenshot 2023-09-01 121435](https://github.com/mhutchie/vscode-git-graph/assets/103348/2b4b0e53-f398-4df0-93b7-8f6a25424e77)

The original design was much easier to read - things are too small, the text is low contrast, and the full intensity red on black is actually hard on the eyes.

I'm *extremely* grateful that someone is willing to take over from the original maintainer, so please don't take this the wrong way, but this really needs a designer's eye. I would offer to help, but I'm not a designer either. Maybe we could find someone who's willing to help out and make this look beautiful again?

If not, please consider reverting the design changes. 🙏

**Comment by phil294** [comment]
you're looking at an entirely different extension here 😄

please go to: https://github.com/phil294/git-log--graph/issues/56

**Comment by mindplay-dk** [comment]
Yeah, whoops. For some reason I thought this was a fork. Let's close this issue and track any design changes in the one you opened. :-)
