### ISSUE TITLE
Option to hide individual columns

### ISSUE THREAD

**Issue by ashelleyPurdue** [mhutchie/vscode-git-graph#79]
**Describe the feature that you'd like**
An option to hide individual columns, such as the "date" column.

**Additional context (optional)**
I don't particularly care about the date or author of a commit when I'm skimming through the graph.  It'd be nice if I could reclaim that real-estate so there's more room to see the description.  Please and thank you!

**Comment by ashelleyPurdue** [comment]
Also, I meant to put a "nice to have" label on this issue, but I can't find the option for that :/

**Comment by mhutchie** [comment]
Thanks for this suggestion, it’s a great idea! I’ll add support for this in an upcoming release.

**Comment by mhutchie** [comment]
This will be available in v1.7.0.

If you'd like to use it before the next release, you can download [v1.7.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.7.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
