### ISSUE TITLE
Make Git Grpah Work with "Floating editor windows"

### ISSUE THREAD

**Issue by armada45-pixel** [mhutchie/vscode-git-graph#797]
Make Git Grpah Work with ["**Floating editor windows**"](https://code.visualstudio.com/updates/v1_85#_floating-editor-windows)
![image](https://github.com/mhutchie/vscode-git-graph/assets/59261678/d4706176-de62-4117-b4f4-875fea1ea9c4)

**Comment by Keavon** [comment]
This avenue is likely our best hope of ever getting this added (show your support for it there):

[**COMMUNITY CALL: Add your support for rebuilding Git Graph as an official VS Code feature (#804)**](https://github.com/mhutchie/vscode-git-graph/issues/804)

**Comment by armada45-pixel** [comment]
Git Grpah already support ["Floating editor windows"](https://code.visualstudio.com/updates/v1_85#_floating-editor-windows) now.
