### ISSUE TITLE
Branch drop-down is white when VSCode is set to a dark theme

### ISSUE THREAD

**Issue by krupenja** [mhutchie/vscode-git-graph#8]
**Describe the feature that you'd like**
If VSCode is set to a dark theme, Branch drop-down is white:

![image](https://user-images.githubusercontent.com/26354715/53204532-8808fb00-3634-11e9-9cff-59b9b2c1efd3.png)

Compare to e.g. the dropdown in settings UI:

![image](https://user-images.githubusercontent.com/26354715/53204565-9ce58e80-3634-11e9-9472-e887f3b87702.png)

**Comment by mhutchie** [comment]
I was planning on creating a custom drop down control so it matches the colour scheme. This request should be achieved with this planned change, I'll use this item for tracking the required work.

FYI: I couldn't get a nice looking built in drop down which looked good cross-platform, as on Windows there is a yellow border around the drop down options, which is hardly noticeable if the background is left light, but it stands out harshly with dark background.

**Comment by mhutchie** [comment]
This is now completed and will be available in 1.4.1, which will be released in the next few hours.
