### ISSUE TITLE
Show diff in split vertical pane?

### ISSUE THREAD

**Issue by weynhamz** [mhutchie/vscode-git-graph#85]
**Describe the feature that you'd like**
Currently, when browsing the git commit, clicking the changed file, it opens a diff window in the same pane, it would be really great if it can be opened in a second vertical split pane by default (or configurable).

**Comment by mhutchie** [comment]
Thanks for the suggestion, this is a great idea! I'll add it in the an upcoming release.

**Comment by mhutchie** [comment]
I've added a new setting `git-graph.openDiffTabLocation` to choose which pane the Visual Studio Code Diff opens in. Currently the Visual Studio Code API doesn't allow the Diff view to be opened below the active pane (when they add support for this I can add it as an option then), but they do allow support for opening it beside the active pane. For now the options are `Active` & `Beside`. I found that `Beside` works really nicely if the user uses the non Side-By-Side VSCode Diff. The setting defaults to the `Active` pane.

This will be available in 1.6.0, which will be release within the next day.

**Comment by weynhamz** [comment]
WOW, I really live ur quick responding, GREAT work, THANKS!!!

**Comment by mhutchie** [comment]
This is available in the beta release [v1.6.0-beta.4](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.4) if you'd like to try it out. I included it with the fix for the dropdown scroll behaviour you mentioned in the other issue.

**Comment by weynhamz** [comment]
Just tried, working like Charm. MANY THANKS AGAIN!!! This is definitely gonna boost my performance today.

I think this is the BEST Git Graph tool I ever used, and to be honest, I used to contribute to GNOME gitg to improve the graph chart, but this VScode extension just feels right, exactly a developer would ever want.

GREAT WORK!!!

**Comment by hansunzner-kt** [comment]
Very nice setting, thanks!
Does the vscode API allows it to change the size of the split view when opening a new?
If I set  "git-graph.openDiffTabLocation" to "Beside" it opens the diff view in a second view with the same width as the first. But this view is already splitted so a width of 2/3 would be nice. So all views then would have the same width.

**Comment by mhutchie** [comment]
Hi @hansunzner-kt,

No, the Visual Studio Code API only allows the Editor Group to be specified, there is no mechanism to change the width. See [ViewColumn](https://code.visualstudio.com/api/references/vscode-api#ViewColumn).

**Comment by hansunzner-kt** [comment]
What a pity but thanks for you quick response!

**Comment by hansunzner-kt** [comment]
What do you think about adding an option like `git-graph.openFileTabLocation` ?
Because the diffs I like to view in a tab beside but the file I want to see in the same tab.

**Comment by mhutchie** [comment]
Hi @hansunzner-kt,

I'll gather some feedback from other users around your suggestion to split the functionality of `git-graph.openNewTabEditorGroup` into individual settings, to see how much user interest there is for it. If there's enough interest and perceived value, I'll raise it as a new feature request.

FYI: While I've deliberately made the extension extremely configurable for users, the more settings I add, the harder it is for users to find a setting they're interested in within the Visual Studio Code Settings Editor. I already get many feature requests from users for functionality that is already available in an extension setting that they didn't find. Git Graph currently has 79 extension settings. Going forward, I have to balance the value added by new settings, with the loss of value from existing settings that become less discoverable.

**Comment by hansunzner-kt** [comment]
Oh yes that's a lot of settings. I found this setting also because google pointed me to this issue. 
Let's see what the other users think about that.

**Comment by hansunzner-kt** [comment]
I had an idea. What about letting a box pop up and ask the user how he would like to view this diff when the select that for the first time? 
But supposable the vscode API do not allow that...

**Comment by mhutchie** [comment]
Hi @hansunzner-kt,

This is possible, as the Visual Studio Code's API allows Quick Pick's to be shown (I use this in the extension for several extension-contributed commands).

Although your idea is functionally workable, it's not consistent with the pattern used for settings in Visual Studio Code. Imagine if every time a user does something for the first time, they're asked what they'd like the default values to be for every setting that applies to that action - it would be a terrible user experience. It's important for all extensions to follow design patterns set in Visual Studio Code, to ensure users have a consistent experience. While exceptions can occasionally be made in extreme circumstances, this definitely isn't one.

**Comment by hansunzner-kt** [comment]
Okay you are right.
You could also open a file always in the same tab as default regardless of the setting `git-graph.openDiffTabLocation` because that should only handle the diff tab (as the name says strictly speaking ;-) )

**Comment by mhutchie** [comment]
Hi @hansunzner-kt,

The original setting implemented in this feature request `git-graph.openDiffTabLocation` has been depreciated - Visual Studio Code doesn't display it in the Settings View, and if a user has set it, they receive a depreciation message (originally users could only open the Diff View for a file). The setting was replaced by `git-graph.openNewTabEditorGroup` after the ability to open files and view files at the revision was implemented, as the setting was extended to control where new tabs are opened regardless of the action in the extension (not just the Diff View).

**Comment by hansunzner-kt** [comment]
Ah okay thats the reason why my setting is underlined :smile:

**Comment by kt-unzner** [comment]
> I'll gather some feedback from other users around your suggestion to split the functionality of `git-graph.openNewTabEditorGroup` into individual settings, to see how much user interest there is for it. If there's enough interest and perceived value, I'll raise it as a new feature request.
> 
Did you get some feedback yet?

**Comment by mhutchie** [comment]
Hi @kt-unzner,

> Did you get some feedback yet?

The consensus so far is that `git-graph.openNewTabEditorGroup` is sufficient for most users needs, and that it's not worth adding an additional extension setting. However, I'll keep monitoring the various sources of user feedback in case this changes in the future (and implement it if appropriate).

**Comment by kt-unzner** [comment]
>... the more settings I add, the harder it is for users to find a setting they're interested in within the Visual Studio Code Settings Editor.

But then you have settings like that, that are very slight fine adjustments. Sorry I can't really follow that.
But I don't want to bother you. I really appreciate that you implement our feature requests at all :-)

![grafik](https://user-images.githubusercontent.com/68994013/109650794-0242b300-7b5e-11eb-9bd9-e5cf6758748e.png)
