### ISSUE TITLE
It’s completely unusable recently.

### ISSUE THREAD

**Issue by ToonoW** [mhutchie/vscode-git-graph#86]
**Describe the bug**
It’s completely unusable recently.

**What does the bug relate to**
- Graph Rendering

**To reproduce**
Steps to reproduce the behaviour:
1. Click "Git Graph"

**Environment**
 - OS: macOS 10.14.14
 - Visual Studio Code Version: 1.35.0-insider in Remote Development on Ubuntu 16

**Screenshots (optional)**
Add any screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/12607586/58153946-f8aacc80-7ca2-11e9-90c8-2a138058735a.png)

**Comment by mhutchie** [comment]
The extension does not currently support "Remote Development", as it was announced for insider-only builds less than three weeks ago, and I was only made aware of it 2 days ago.

The existing feature request #83 is adding support for the "Remote Development" functionality of Visual Studio Code, and it is expected to be release in the next few days.

I'm closing this issue as a duplicate.
