### ISSUE TITLE
Show which branch is checked out on remote

### ISSUE THREAD

**Issue by t-gehring** [mhutchie/vscode-git-graph#87]
**Describe the feature that you'd like**
I have a remote set up for pushing code to a build server, and it would be handy to be able to see which branch is currently checked out on it. This can be achieved in git [like so](https://stackoverflow.com/questions/27480112/how-could-i-find-out-which-branch-is-checked-out-on-a-remote-machine), it would be great if that could be used to put some sort of decoration on the branch label for that remote.

A seperate issue but related - I feel like the current method of displaying which branch is checked out locally is a bit too subtle. Perhaps the name of the branch could be bolded to show that it's checked out? This would work well with the new combined local/remote labels from 1.6.0.

**Comment by mhutchie** [comment]
Thanks for these suggestions! They’re great ideas and I’ll include them in an upcoming release.

I’m releasing 1.6.0 in the next day, so this is too late for this release as I’m already doing pre-release testing.

**Comment by mhutchie** [comment]
I've bolded the current had branch label, which will be available in 1.7.0. If you'd like to use it before the next release, you can download [v1.7.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.7.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

I've implemented the main part of this issue for showing the checked out branch on remotes, I'm just not happy with how I'm currently displaying it on the UI. I'll have a think about how to differentiate it better from other remote branches and then include it in a beta release for you to look at.

**Comment by t-gehring** [comment]
Thanks for this! I'm definitely liking the bold label, I look forward to seeing the remotes once you've figured out a display you're happy with.

**Comment by mhutchie** [comment]
Hi @t-gehring,

This feature request has been left open for 16 months now, and no other Git Graph users have indicated they would like this functionality in this period. This lack of user interest, coupled with the below challenges, means that I'll close this feature request for now and move it to the backlog.
* The command you referenced `git remote show <remote-name>` is quite slow compared to most other Git commands, as it connects with the remote to retrieve various information (including the "HEAD branch", i.e. the checked-out branch). It appears that Git doesn't store this information locally within the repository, it must be fetched each time from the remote.
    * The (relatively) long runtime of this command means that it can't be a part of the existing Git Graph data loading and refresh cycles. This necessitates background polling of this Git command, and storing the value in the extensions state - so the cached value can be efficiently retrieved. This background polling behaviour is not something currently implemented in Git Graph, however I have had several ideas that may collectively warrant its implementation in the not-to-distant future.
    * The output of this command is not designed to be machine-readable, making it somewhat risky to rely on it in Git Graph. Although the current format is relatively easy to parse, Git makes no guarantee that the current format remains the same for future versions of Git - it could easily be altered in a way that breaks any specific parsing algorithm I could implement. In contrast, the majority of Git commands used by Git Graph are either machine-readable by default, or have options to make the output machine-readable - they also remain consistent in the long term.
    * I've found several alternative Git commands that at cursory inspection appear to indicate the checked-out branch on a remote, however I've found these are often just educated guesses, not something I would want to rely upon (and potentially mislead users).
    * I also checked several other common Git UI's, and they also don't display the checked-out branch on remotes. I assume this is for similar reasons to the points I'm mentioning in this reply.
* Despite trying various approaches for displaying the checked out branch on a remote, I never found a solution that was both obvious enough to spot at a glance, and didn't make the existing formatting variations harder to distinguish or confusing based on user feedback I received (non-checked-out local branch / checked-out local branch / remote branch).

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and add this feature if there was any indication it would be used by a decent number of users, and I could find a feasible solution to the above challenges.
