### ISSUE TITLE
Load More Commits broken at least for some repos

### ISSUE THREAD

**Issue by krupenja** [mhutchie/vscode-git-graph#9]
**Describe the bug**
Load More Commits is broken at least for some repos.

**What does the bug relate to**
- [x] Graph Rendering
- [ ] Git Command
- [ ] Responsiveness

**To reproduce**
Steps to reproduce the behaviour:
1. Clone this repo: https://github.com/github/government.github.com
2. Open Git Graph.
3. Click Load More Commits.
4. Wait for a while (~10 min in my case).

After a while, Git Graph tab is just black (see screenshot below), commits are not loaded properly. CPU usage is also high during loading.

**Expected behaviour**
Commits should be loaded successfully.

**Environment**
 - OS: macOS 14.0.2
 - Visual Studio Code Version: 1.31.1

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/26354715/53205941-5eea6980-3638-11e9-95c7-6f831d104144.png)

**Comment by mhutchie** [comment]
This appears to be the same issue as #3, which I'm waiting for the person who raised the issue to confirm it as fixed in a pre-release version of 1.3.3. You can try it out if you'd like to confirm that it fixes this issue https://github.com/mhutchie/vscode-git-graph/issues/3#issuecomment-465094490

**Comment by krupenja** [comment]
Yes, can confirm that this problem is fixed with the pre-release version from that comment.

**Comment by mhutchie** [comment]
Awesome, thanks for confirming that! I'll give the raiser of #3 another day to confirm it's fixed his issue. If not, I can release it pretty confidently as it's fixed it for you.
