### ISSUE TITLE
Open Git Graph to the active text document

### ISSUE THREAD

**Issue by mhutchie** [mhutchie/vscode-git-graph#91]
**Describe the feature that you'd like**
As discussed in #90, it would be good to add a setting allowing Git Graph to be opened (from the status bar item or command palette) to the repo that contains the active document being edited.

**Additional context (optional)**
See other issue.
Suggested by @SirIntruder

**Comment by mhutchie** [comment]
This will be available in v1.8.0.

If you'd like to use it before the next release, you can download [v1.8.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.8.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

FYI: @SirIntruder

**Comment by SirIntruder** [comment]
thanks @mhutchie! Will check it out tommorrow 👍

**Comment by SirIntruder** [comment]
Works perfect - and brw, thanks for the in-place spinner when loading commit details - no more blinking! 😄
