### ISSUE TITLE
Configuration of repositiory remotes

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#95]
I think, be able to change the remote URL could be nice to have.

This feature could be added here
![image](https://user-images.githubusercontent.com/44493964/58940097-e76cc000-8778-11e9-9ccc-738a3df540fc.png)

with a settings icon and a drop down menu on select (this setting could be useful in the future for another configurations)

**Comment by mhutchie** [comment]
Thanks for this suggestion! This would definitely be nice to have.

**Comment by mhutchie** [comment]
This will be available in v1.11.0, which will be released within the next day. Thank you for all your help developing this functionality.
