### ISSUE TITLE
Filter / search commits

### ISSUE THREAD

**Issue by borekb** [mhutchie/vscode-git-graph#96]
It would be great to have a text input field at the top where I could type a string and it would filter  the commits. There are some challenges like what would happen with the graph but I'd love to see this feature.

For reference, [GitLens has commit searching](https://github.com/eamodio/vscode-gitlens/blob/15c8565f5394f966f9b36ea41421920e095dbf6e/README.md#search-commits-view-) for for Git Graph, I'd probably appreciate a simpler UI, similar to the search field in Gmail or here on GitHub. I think it could suit nicely the visual character of this extension.

**Comment by mhutchie** [comment]
Thanks for this suggestion! This is definitely something I want to implement soon, and I agree it would nicely complement the existing UI & functionality of Git Graph.

The existing feature request #31 will already cover the implementation of this, so I'll close this issue for now as a duplicate (let me know if I've misunderstood what you're suggesting). I've been working on it in the background for some time now, I'm trying to come up with a really nice way of incorporating it visually in the extension.

**Comment by borekb** [comment]
Oops, you're right, and I tried searching for "search", "filter" and similar keywords 😄.

Awesome to hear about the progress!
